Clean up

In [1]:
from datetime import datetime, timedelta
import time
import pandas as pd
import os

In [ ]:
def cleanUp(df):
  #nullwaarden verwijderen
  df.dropna(inplace=True)

  #tijd aanpassen
  #tijdformaat ..:..:..
  tijd_regex = r'^\d{2}:\d{2}:\d{2}$'
  #omzetten naar datetime
  df['date'] = pd.to_datetime(df['dateDiff']).dt.date
  #filter rijen met formaat
  df = df[df['startTime'].str.match(tijd_regex, na=False) & df['rLength'].str.match(tijd_regex, na=False)].copy()
  #afleveringlengte naar seconden omzetten 
  df['Lengte_sec'] = pd.to_timedelta(df['rLength']).dt.total_seconds().astype(int)
  #kijkers naar int
  df['Kijkers'] = df['rateInK'].dropna().astype(str).str.replace('.', '', regex=False).astype(int)

  #uren met 24+
  def time_cor(rij):
    tijdArr = rij['startTime'].split(':')
    if int(tijdArr[0]) >= 24:
      tijdArr[0] = str(int(tijdArr[0]) - 24).zfill(2)
      
      rij['date'] += timedelta(days=1)
    rij['startTime'] = ':'.join(tijdArr)
    return rij
  
  df = df.apply(time_cor, axis=1)

  #1 kolom voor beide data
  df['FullDate'] = pd.to_datetime(df['date'].astype(str) 
                                  + " " + df['startTime'].astype(str))
  
  #hour en minute voor join later on
  df['hour'] = pd.to_datetime(df['startTime']).dt.hour
  df['minute'] = pd.to_datetime(df['startTime']).dt.minute

  #kolommen verwijderen die niet nodig meer zijn
  df.drop(['startTime', 'rLength', 'rateInK', 'ranking', 'live'], axis=1, inplace=True)

  #de nieuwe dataframe
  df = df[['FullDate', 'date', 'hour','minute', 'channel', 'description', 'Lengte_sec', 'Kijkers']]

  #hernoemen kolommen
  df.rename(columns={'description':'Programma', 'channel':'Kanaal'}, inplace=True)

  return df

In [3]:
Kijkcijfers = pd.read_csv('./data csv/kijkcijfersdataraw.csv')
Kijkcijfers = cleanUp(Kijkcijfers)
Kijkcijfers.sample(10)

C:\Users\krist\AppData\Local\Temp\ipykernel_638904\78328727.py:33: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['hour'] = pd.to_datetime(df['startTime']).dt.hour
C:\Users\krist\AppData\Local\Temp\ipykernel_638904\78328727.py:34: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['minute'] = pd.to_datetime(df['startTime']).dt.minute

,FullDate,date,hour,minute,Kanaal,Programma,Lengte_sec,Kijkers
60473,2024-12-25 20:18:36,2024-12-25,20,18,PLAY4,HUIZENJAGERS,2489,252786
55238,2024-04-07 13:46:44,2024-04-07,13,46,VTM,ASPE,4693,124893
26354,2020-05-13 20:17:30,2020-05-13,20,17,VTM,SARA,1512,576711
5199,2017-06-19 23:02:20,2017-06-19,23,2,EEN,HET JOURNAAL LAAT,941,458738
41034,2022-05-07 16:42:59,2022-05-07,16,42,VTM,THE VOICE KIDS - KNOCKOUT,6577,75120
7710,2017-10-23 19:00:06,2017-10-23,19,0,EEN,HET 7 UUR-JOURNAAL,2536,1120036
57352,2024-07-22 18:20:25,2024-07-22,18,20,VTM,DE KOTMADAM,1588,213779
22734,2019-11-14 20:43:33,2019-11-14,20,43,EEN,APPEL D'URGENCE,2615,591508
36621,2021-10-08 22:44:59,2021-10-08,22,44,VTM,THE GOOD DOCTOR,2392,186371
47836,2023-04-03 18:24:44,2023-04-03,18,24,VTM,LISA,1390,189545

Weerdata mergen

In [4]:
weerData = pd.read_csv('./data csv/weerdataraw.csv')
weerData['timestamp'] = pd.to_datetime(weerData['timestamp'])
#naar zelfde formaat als kijkcijfer datum
weerData['datetime'] = weerData['timestamp'].dt.strftime('%Y-%m-%d %H:%M:%S')

#hour voor join later on
weerData['hour'] = pd.to_datetime(weerData['datetime']).dt.hour
weerData['minute'] = pd.to_datetime(weerData['datetime']).dt.minute
weerData['date'] = pd.to_datetime(weerData['datetime']).dt.date

#verwijder kolom
weerData = weerData.drop(columns=['timestamp'])

weerData = weerData[['datetime', 'date' ,'hour', 'minute', 'temperature_2m', 'apparent_temperature', 
                           'rain', 'snowfall', 'weather_code', 'cloud_cover', 
                           'wind_speed_10m', 'sunshine_duration']]

#hernoemen kolommen
weerData.rename(columns={'temperature_2m':'Temperatuur', 'apparent_temperature':'Gevoelstemp', 'wind_speed_10m': 'Windsnelheid', 'rain':'Regen', 'snowfall': 'Sneeuw', 'weather_code':'Weercode', 'cloud_cover':'Bewolking', 'sunshine_duration':'Zonnenschijn'}, inplace=True)

weerData.sample(10)

,datetime,date,hour,minute,Temperatuur,Gevoelstemp,Regen,Sneeuw,Weercode,Bewolking,Windsnelheid,Zonnenschijn
40034,2021-04-26 02:00:00,2021-04-26,2,0,4.2,-0.2,0.0,0.0,0,1,15.8,0.00
1255,2016-11-22 07:00:00,2016-11-22,7,0,10.9,5.3,0.0,0.0,0,7,31.3,0.00
1744,2016-12-12 16:00:00,2016-12-12,16,0,7.3,4.0,0.0,0.0,3,100,14.0,2010.28
28717,2020-01-10 13:00:00,2020-01-10,13,0,8.5,4.3,0.0,0.0,1,38,21.4,3600.00
4582,2017-04-09 22:00:00,2017-04-09,22,0,13.5,10.6,0.0,0.0,0,0,12.4,0.00
7924,2017-08-27 04:00:00,2017-08-27,4,0,15.8,16.8,0.0,0.0,2,55,4.7,0.00
4939,2017-04-24 19:00:00,2017-04-24,19,0,12.7,9.3,0.0,0.0,3,96,15.7,0.00
14852,2018-06-11 20:00:00,2018-06-11,20,0,21.3,19.8,0.0,0.0,3,100,16.1,0.00
49397,2022-05-21 05:00:00,2022-05-21,5,0,12.0,9.5,0.0,0.0,2,68,17.3,0.00
19365,2018-12-16 21:00:00,2018-12-16,21,0,4.8,1.5,0.0,0.0,3,100,13.1,0.00

Mergen weerdata en kijkcijferdata op FullDate

In [5]:
kijkcijfersWeer = pd.merge(Kijkcijfers, weerData, on=['date', 'hour'], how='left')

kijkcijfersWeer = kijkcijfersWeer[['FullDate', 'date', 'hour', 'Kanaal', 'Programma', 'Lengte_sec', 'Kijkers', 'Temperatuur', 'Gevoelstemp', 'Regen', 'Sneeuw', 'Weercode', 'Bewolking', 'Windsnelheid', 'Zonnenschijn']]

kijkcijfersWeer.sample(10)

#kijkcijfersWeer.to_csv('./data csv/blablableble.csv')

,FullDate,date,hour,Kanaal,Programma,Lengte_sec,Kijkers,Temperatuur,Gevoelstemp,Regen,Sneeuw,Weercode,Bewolking,Windsnelheid,Zonnenschijn
59704,2025-01-15 20:19:08,2025-01-15,20,PLAY4,HUIZENJAGERS,2498,231449,7.1,5.8,0.0,0.0,3,100,2.7,0.0
43602,2022-10-14 17:46:32,2022-10-14,17,VTM,DE BUURTPOLITIE,1676,193777,15.2,14.7,0.0,0.0,3,100,7.9,0.0
38366,2022-01-24 13:00:02,2022-01-24,13,EEN,HET 1 UUR-JOURNAAL,1749,488710,2.7,0.3,0.0,0.0,3,100,3.4,3600.0
4872,2017-06-05 12:59:49,2017-06-05,12,VTM,NIEUWS 13U VTM,1864,241501,19.7,15.8,0.0,0.0,0,15,21.7,3600.0
5178,2017-06-21 20:11:59,2017-06-21,20,EEN,THUIS,1503,1093614,31.5,31.9,0.0,0.0,0,0,7.6,3600.0
15902,2018-12-10 20:43:32,2018-12-10,20,EEN,"BLOED, ZWEET & LUXEPROBLEMEN",3024,698250,6.1,2.4,0.0,0.0,2,64,12.3,0.0
38219,2022-01-17 20:13:47,2022-01-17,20,EEN,THUIS,1482,1129638,3.9,1.1,0.0,0.0,1,21,7.9,0.0
55270,2024-05-28 18:31:39,2024-05-28,18,VRT 1,BLOKKEN,1632,632950,15.4,13.7,0.1,0.0,51,100,18.6,0.0
31309,2021-02-05 22:49:01,2021-02-05,22,VTM,09/01/2001,2433,292380,4.3,2.0,0.0,0.0,3,98,5.9,0.0
3674,2017-04-05 23:04:13,2017-04-05,23,EEN,HET JOURNAAL LAAT,1049,308525,5.9,3.2,0.0,0.0,0,2,9.2,0.0

debug box

In [6]:
# Bekijk de kolomnamen in Kijkcijfers en weerData
print(Kijkcijfers.columns)
print(weerData.columns)

#nullrows aanwezig?
print(f"null-rows: \n{kijkcijfersWeer.isnull().sum()}")

Index(['FullDate', 'date', 'hour', 'minute', 'Kanaal', 'Programma',
       'Lengte_sec', 'Kijkers'],
      dtype='object')
Index(['datetime', 'date', 'hour', 'minute', 'Temperatuur', 'Gevoelstemp',
       'Regen', 'Sneeuw', 'Weercode', 'Bewolking', 'Windsnelheid',
       'Zonnenschijn'],
      dtype='object')
null-rows:
FullDate        0
date            0
hour            0
Kanaal          0
Programma       0
Lengte_sec      0
Kijkers         0
Temperatuur     0
Gevoelstemp     0
Regen           0
Sneeuw          0
Weercode        0
Bewolking       0
Windsnelheid    0
Zonnenschijn    0
dtype: int64

In [7]:
kijkcijfersWeer.dropna(inplace=True)
#csv aanmaken als het niet bestaat
csv_file_path = os.path.join('.','data csv','kijkcijfersWeerRaw.csv')
os.makedirs(os.path.dirname(csv_file_path), exist_ok=True)
#data naar csv
kijkcijfersWeer.to_csv(csv_file_path, index=False)