In [1]:
import pandas as pd
import numpy as np
import os
import pickle
import time
import optuna
import warnings

from category_encoders import TargetEncoder
from xgboost import XGBRegressor
from scipy.stats import randint, uniform
from lightgbm import LGBMRegressor


from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.linear_model import Lasso, LinearRegression
from sklearn.model_selection import train_test_split, cross_val_score, RandomizedSearchCV, _search_successive_halving, GridSearchCV
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor, ExtraTreesRegressor, HistGradientBoostingRegressor 
from sklearn.metrics import mean_absolute_error, mean_absolute_percentage_error

warnings.filterwarnings("ignore")

c:\Users\krist\Documents\Hogent_IT\2de_jaar\Machine_Learning\ML_project_kijkcijfers\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
cleanData = pd.read_csv('./data csv/kijkcijfersWeer.csv')
cleanData.sample(5)

,Unnamed: 0,FullDate,date,hour,Kanaal,Programma,Lengte_sec,Kijkers,Temperatuur,Gevoelstemp,Regen,Sneeuw,Weercode,Bewolking,Windsnelheid,Zonnenschijn,isFeestdag,Weekdag,isWeekend,Seizoen
52620,52622,2024-01-12 20:33:12,2024-01-12,20,VRT CANVAS,DE AFSPRAAK,3214,208116,2.9,0.2,0.0,0.0,3,100,5.9,0.0,0,4,0,winter
5245,5245,2017-06-24 22:54:22,2017-06-24,22,EEN,HET JOURNAAL LAAT,937,342781,18.2,16.3,0.0,0.0,3,92,21.3,0.0,0,5,1,zomer
2599,2599,2017-02-11 20:43:53,2017-02-11,20,EEN,FC DE KAMPIOENEN,1934,706090,-0.4,-3.9,0.0,0.0,3,87,7.2,0.0,0,5,1,winter
50183,50185,2023-09-11 12:59:49,2023-09-11,12,VTM,NIEUWS 13U VTM,1599,192822,25.6,26.6,0.0,0.0,0,4,8.3,3600.0,0,0,0,zomer
40612,40613,2022-05-13 13:41:42,2022-05-13,13,EEN,SOUDAL OPEN,1219,131432,18.7,15.8,0.0,0.0,3,100,18.0,3600.0,0,4,0,lente

Feature engineering

In [3]:
def lagFeatures(df, n):
  for i in range(1,n+1):
    df[f'KijkersLag{i}'] = df.sort_values('FullDate').groupby('Programma')['Kijkers'].shift(i).fillna(df.groupby('Programma')['Kijkers'].transform('mean'))
  return df

In [4]:
cleanData = lagFeatures(cleanData, 3)
cleanData['Kanaal'] = cleanData['Kanaal'].str.replace(' ', '_')

print(cleanData['Kanaal'].unique())

cleanData[cleanData['Programma'] == 'THUIS'][['FullDate', 'Kijkers', 'KijkersLag1', 'KijkersLag2', 'KijkersLag3']]

['EEN' 'VTM' 'CANVAS' 'VIER' 'VIJF' 'Q2' 'VITAYA' 'OP_12' 'ZES' 'LA_UNE'
 'RTL-TVI' 'TF1' 'AB3' 'KETNET' 'Canvas' 'CAZ' 'VTM2'
 'ELEVEN_PRO_LEAGUE_1_NL' 'VTM3' 'VTM4' 'PLAY_SPORTS_OPEN' 'PLAY4' 'PLAY5'
 'EUROSPORT_1_(NL)' 'PLAY6' 'VRT_1' 'VRT_CANVAS' 'VTM_GOLD'
 'DAZN_PRO_LEAGUE_1_(NL)']

                  FullDate  Kijkers   KijkersLag1   KijkersLag2   KijkersLag3
40     2016-10-03 20:14:23  1268561  1.059928e+06  1.059928e+06  1.059928e+06
60     2016-10-04 20:09:27  1169791  1.268561e+06  1.059928e+06  1.059928e+06
80     2016-10-05 20:13:52  1244502  1.169791e+06  1.268561e+06  1.059928e+06
121    2016-10-07 19:57:34  1156477  1.244502e+06  1.169791e+06  1.268561e+06
180    2016-10-10 19:59:00  1315826  1.156477e+06  1.244502e+06  1.169791e+06
...                    ...      ...           ...           ...           ...
61265  2025-04-04 20:24:13   779244  1.018053e+06  9.942260e+05  1.066599e+06
61325  2025-04-07 20:14:35   869193  7.792440e+05  1.018053e+06  9.942260e+05
61345  2025-04-08 20:13:09   880767  8.691930e+05  7.792440e+05  1.018053e+06
61366  2025-04-09 20:19:53   802132  8.807670e+05  8.691930e+05  7.792440e+05
61386  2025-04-10 20:14:08   799990  8.021320e+05  8.807670e+05  8.691930e+05

[1838 rows x 5 columns]

Kardinaliteiten

In [5]:
#kardinaliteiten voor betere toepassingen
for kolom in cleanData.columns:
  print(f'{kolom}: {cleanData[kolom].nunique()}')

Unnamed: 0: 61405
FullDate: 61318
date: 3051
hour: 21
Kanaal: 29
Programma: 5963
Lengte_sec: 6774
Kijkers: 58860
Temperatuur: 414
Gevoelstemp: 478
Regen: 62
Sneeuw: 25
Weercode: 13
Bewolking: 101
Windsnelheid: 456
Zonnenschijn: 3555
isFeestdag: 2
Weekdag: 7
isWeekend: 2
Seizoen: 4
KijkersLag1: 58998
KijkersLag2: 56714
KijkersLag3: 55143

One Hot Encoding

In [6]:
#one hot encoding voor lage cardinaliteit
oneHotEnc = OneHotEncoder(handle_unknown="ignore")
lageKardinaliteit = cleanData[[ 'hour','Kanaal', 'isFeestdag', 'Weekdag', 'Seizoen']]
oneHot = oneHotEnc.fit_transform(lageKardinaliteit)
dfOneHot = pd.DataFrame(oneHot.toarray(), 
                            columns=oneHotEnc.get_feature_names_out(), 
                            index=lageKardinaliteit.index)

cleanData = cleanData.drop(columns=['hour', 'Kanaal', 'isFeestdag', 'Weekdag', 'Seizoen'])
cleanData = pd.concat([cleanData, dfOneHot], axis=1)

cleanData.sample(5)

,Unnamed: 0,FullDate,date,Programma,Lengte_sec,Kijkers,Temperatuur,Gevoelstemp,Regen,Sneeuw,...,Weekdag_1,Weekdag_2,Weekdag_3,Weekdag_4,Weekdag_5,Weekdag_6,Seizoen_herfst,Seizoen_lente,Seizoen_winter,Seizoen_zomer
19525,19525,2019-06-09 19:54:03,2019-06-09,TEGEN DE STERREN OP,1469,303235,17.2,15.8,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
12925,12925,2018-07-14 18:59:53,2018-07-14,NIEUWS 19U VTM,2645,328045,26.6,25.2,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
2141,2141,2017-01-19 19:44:44,2017-01-19,IEDEREEN BEROEMD,1304,1144056,-1.5,-6.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
40216,40217,2022-04-27 18:59:37,2022-04-27,NIEUWS 19U VTM,3176,614563,15.6,12.8,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
56410,56413,2024-07-31 17:33:25,2024-07-31,O.S. 2024 JUDO D. - WILLEMS,923,443275,26.1,27.4,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [7]:
#opslaan bij models
modelsDir = os.getcwd()
modelFile = os.path.join(modelsDir, ".",
                          "models", "oneHotEncoder.pkl")
os.makedirs(os.path.dirname(modelFile), exist_ok=True)
with open(modelFile, 'wb') as m:
  pickle.dump(oneHotEnc, m)

Target Encoding

In [8]:
#target encoding voor medium kardinaliteiten
targetEncoding = TargetEncoder()
medKardinaliteit = cleanData[['date', 'Programma', 'Lengte_sec', 'Temperatuur', 'Gevoelstemp', 'Regen', 'Bewolking', 'Windsnelheid', 'Zonnenschijn']]
#verdere feature engineering op vorig model
target = targetEncoding.fit_transform(medKardinaliteit, cleanData['Programma'])
target.sample(10)

,date,Programma,Lengte_sec,Temperatuur,Gevoelstemp,Regen,Bewolking,Windsnelheid,Zonnenschijn
10319,2287.200912,1677.000000,2458,7.4,5.3,0.0,71,5.5,3600.00
22330,2117.475912,5896.000000,3291,11.1,7.7,0.0,80,13.2,3600.00
445,2499.075912,2554.000000,2689,9.3,6.1,0.0,100,14.4,3600.00
31055,2458.025912,1254.328194,2819,2.8,-0.1,0.8,100,7.9,0.00
22822,2287.000912,2603.333441,4638,7.4,4.3,0.1,100,13.1,0.00
47557,1975.925912,834.000000,903,12.5,8.5,0.0,0,17.0,3600.00
48647,2016.800912,1677.000000,2623,20.2,17.6,0.0,100,16.1,897.37
30847,2144.700912,1749.000000,1161,4.4,1.2,0.4,100,11.2,0.00
60231,2009.900912,1403.000000,1538,3.8,0.5,0.0,100,10.9,0.00
4316,2189.000912,1986.631458,2238,9.2,5.1,0.0,0,19.9,2575.78

In [9]:
cleanData = cleanData.drop(columns=['date', 'Programma', 'Lengte_sec', 'Temperatuur', 'Gevoelstemp', 'Regen', 'Bewolking', 'Windsnelheid', 'Zonnenschijn'])
cleanData = pd.concat([cleanData, target], axis=1)
cleanData.sample(5)

,Unnamed: 0,FullDate,Kijkers,Sneeuw,Weercode,isWeekend,KijkersLag1,KijkersLag2,KijkersLag3,hour_0,...,Seizoen_zomer,date,Programma,Lengte_sec,Temperatuur,Gevoelstemp,Regen,Bewolking,Windsnelheid,Zonnenschijn
40033,40034,2022-04-11 21:18:39,189400,0.0,3,0,107549.0,152331.000000,268345.000000,0.0,...,0.0,2073.271526,3336.980357,2969,12.5,9.2,0.0,97,13.9,0.00
6655,6655,2017-09-02 20:00:05,127812,0.0,1,1,202443.0,161358.333333,161358.333333,0.0,...,1.0,2594.225912,2474.053214,9172,15.7,14.6,0.0,27,7.2,3357.17
24801,24801,2020-03-01 19:58:11,908798,0.0,3,1,903932.0,884079.000000,735663.000000,0.0,...,0.0,2347.000912,583.544609,3136,7.4,3.8,0.0,100,11.7,0.00
51330,51332,2023-11-08 19:51:17,745581,0.0,61,0,727686.0,764592.000000,738447.000000,0.0,...,0.0,1921.750912,1878.000000,1519,10.1,5.3,1.9,100,29.8,0.00
38975,38975,2022-02-23 17:11:56,242514,0.0,3,0,285385.0,281967.000000,233721.000000,0.0,...,0.0,2156.675912,1454.000000,3092,10.6,6.3,0.0,100,18.8,0.00

Verbanden

In [10]:
dataOneHotTarget = cleanData.select_dtypes(include=[np.number])

verband = dataOneHotTarget.corr()

verband = verband['Kijkers'].abs().sort_values(ascending=False)

print(f'{verband.head(10)}')
dataOneHotTarget.shape

Kijkers        1.000000
KijkersLag1    0.894582
KijkersLag2    0.893195
KijkersLag3    0.875979
hour_19        0.386184
Kanaal_EEN     0.333420
hour_22        0.184308
hour_17        0.176407
hour_20        0.176109
Gevoelstemp    0.172495
Name: Kijkers, dtype: float64

(61405, 80)

In [11]:
# Eerst omzetten naar strings, daarna komma's verwijderen, en uiteindelijk naar floats
for col in ['KijkersLag1', 'KijkersLag2', 'KijkersLag3', 'Programma']:
    cleanData[col] = cleanData[col].astype(str).str.replace(',', '').astype(float)

# Print het resultaat
print(cleanData[['Kijkers', 'KijkersLag1', 'KijkersLag2', 'KijkersLag3', 'Programma']].head(10))

   Kijkers    KijkersLag1    KijkersLag2    KijkersLag3    Programma
0   721850  892001.072096  892001.072096  892001.072096  1677.000000
1   709606  628487.089971  628487.089971  628487.089971  1425.000000
2   548239  478421.179487  478421.179487  478421.179487  4807.106007
3   523610  791862.682708  791862.682708  791862.682708  1878.000000
4   496216  491224.740741  491224.740741  491224.740741   779.215215
5   447427  351454.000000  351454.000000  351454.000000  2411.204623
6   424041  585853.225914  585853.225914  585853.225914  2554.000000
7   369066  408691.165611  408691.165611  408691.165611  1676.000000
8   368549  336230.500000  336230.500000  336230.500000  2885.510725
9   360544  332870.588235  332870.588235  332870.588235  3291.702083

In [12]:
#opslaan bij models
targetModelDir = os.getcwd()
targetModelPath = os.path.join(targetModelDir, ".",
                          "models", "oneHotTarget.pkl")
os.makedirs(os.path.dirname(targetModelPath), exist_ok=True)
with open(targetModelPath, 'wb') as m:
  pickle.dump(targetEncoding, m)

Model tests

In [13]:
def test_models(models, X, y, cv=10, scoring='neg_mean_absolute_error'):
    res = {}
    for m in models:
        model = type(m).__name__
        scores = cross_val_score(m, X, y, cv=cv, scoring=scoring)
        res[model] = {
            'scores': scores,
            'mean_score': scores.mean()
        }
        print(f"Scores {model}\n{scores}\nMAE = {scores.mean()}")
    return res

Lasso Regression

In [15]:
models = [
    RandomForestRegressor(verbose=True), Lasso()
]

# Zorg ervoor dat X en y goed geschaald zijn
scaler = StandardScaler()
X = dataOneHotTarget.drop(columns=['Kijkers', 'Unnamed: 0'])
X_scaled = scaler.fit_transform(X)
y = dataOneHotTarget['Kijkers']

In [ ]:
# Run de test
results = test_models(models, X_scaled, y)

RandomForest heeft betere scores:
  
  RandomForest
  MAE = -52082.47210795064

  Lasso
  MAE = -64622.292775108515

Naar csv schrijven

In [19]:
dir = os.getcwd()
pathFile = os.path.join(dir, "./data csv/oneHotTarget.csv")

os.makedirs(os.path.dirname(pathFile), exist_ok=True)

dataOneHotTarget.to_csv(pathFile)

keuze maken voor model

In [16]:
#trainset en testset maken
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=True)

def scoreModel(model,X,y, cv=5):
    print(f"Model: {model.__class__.__name__}")
    start = time.time()
        
    # MAE
    mae_scores = cross_val_score(model, X, y, cv=cv, scoring='neg_mean_absolute_error')
    mae = -np.mean(mae_scores)

    # MAPE
    mape_scores = cross_val_score(model, X, y, cv=cv, scoring='neg_mean_absolute_percentage_error')
    mape = -np.mean(mape_scores) * 100

    duration = time.time() - start
    min, sec = divmod(duration, 60)

    print(f"MAE:  {mae:.4f}")
    print(f"MAPE: {mape:.2f}%")
    print(f"Tijd: {int(min)}m {sec:.1f}s")

    return {'Model': model.__class__.__name__, 'MAE': mae, 'MAPE': mape, 'Tijd': duration}
def startModel(models, X, y, cv=5):
    results = []
    for model in models:
        result = scoreModel(model, X, y, cv=cv)
        results.append(result)
    return results

In [17]:
linear = LinearRegression()
decision = DecisionTreeRegressor()
#randomForest = RandomForestRegressor()
gradientBoosting = GradientBoostingRegressor()
xgb = XGBRegressor()
extraTrees = ExtraTreesRegressor()
histGB = HistGradientBoostingRegressor()
lgbm = LGBMRegressor()

startModel([linear, decision, gradientBoosting, xgb, extraTrees, histGB, lgbm], X, y)

Model: LinearRegression
MAE:  66486.7244
MAPE: 20.31%
Tijd: 0m 1.6s
Model: DecisionTreeRegressor

KeyboardInterrupt:

# Best models:

## Model: ExtraTreesRegressor

MAE: 54860.2905

MAPE: 16.27%

Tijd: 11m 50.4s

## Model: HistGradientBoostingRegressor

MAE:  55206.2561

MAPE: 16.29%

Tijd: 0m 11.2s

## Model: LGBMRegressor

MAE:  55006.0849

MAPE: 16.23%

Tijd: 0m 3.4s

## RandomForest er niet bij want 18m+ traintijd voor slechts 200 MAE verschil met XGB

ExtraTrees: Beste nauwkeurigheid maar lange training tijd

HistGradientBoosting en LGBM: Veel sneller met minimale performance drop

Verbeteren van de top 2 modellen

In [19]:
warnings.filterwarnings("ignore")

#parameters
model_param = {
    'LGBMRegressor': {
        'model': LGBMRegressor(),
        'params': {
            'n_estimators': randint(100, 1000),
            'learning_rate': uniform(0.01, 0.3),
            'max_depth': randint(3, 15),
            'min_child_weight': randint(1, 10),
            'subsample': uniform(0.6, 0.4),
            'colsample_bytree': uniform(0.6, 0.4),
            'gamma': uniform(0, 0.5),
            'reg_lambda': uniform(0.1, 10),
            'reg_alpha': uniform(0, 10)
        }
    },
    'HistGradient': {
        'model': HistGradientBoostingRegressor(),
        'params': {
            'learning_rate': uniform(0.01, 0.3),
            'max_iter': randint(100, 1000),
            'max_depth': randint(3, 15),
            'l2_regularization': uniform(0.1, 10),
            'min_samples_leaf': randint(1, 10),
            'max_leaf_nodes': randint(20, 100)
        }
    }
}

extra = ExtraTreesRegressor()
hist = HistGradientBoostingRegressor()
xgb = XGBRegressor()
lgbm = LGBMRegressor()

Random Search

In [20]:
for name, config in model_param.items():
    print(f"Model: {name}")
    model = config['model']
    param = config['params']
    
    rsLoop = RandomizedSearchCV(
        estimator=model,
        param_distributions=param,
        n_iter=250,
        cv=5,
        scoring='neg_mean_absolute_error',
        n_jobs=-1,
        verbose=2
    )
    
    start = time.time()
    rsLoop.fit(X_train, y_train)
    duration = time.time() - start

    print(f"Tijd {name}: {duration:.2f}s")
    print(f"Beste param {name}: {rsLoop.best_params_}")
    print(f"Beste MAE: {rsLoop.best_score_:.4f}")

Model: LGBMRegressor
Fitting 5 folds for each of 250 candidates, totalling 1250 fits
[LightGBM] [Warning] Unknown parameter: gamma
[LightGBM] [Warning] Unknown parameter: gamma
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003941 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2817
[LightGBM] [Info] Number of data points in the train set: 49124, number of used features: 59
[LightGBM] [Info] Start training from score 446116.245705
Tijd LGBMRegressor: 914.07s
Beste param LGBMRegressor: {'colsample_bytree': np.float64(0.6159927582454119), 'gamma': np.float64(0.4252234490130524), 'learning_rate': np.float64(0.0797065159450008), 'max_depth': 11, 'min_child_weight': 6, 'n_estimators': 892, 'reg_alpha': np.float64(9.926651888227628), 'reg_lambda': np.float64(2.3831325944838744), 'subsample': np.float64(0.6189602366096897)}
Beste MAE: -50255.1396
Model: HistGradient
Fitting 5 folds for each of 250 candidates, totalling 1250 fits
Tijd HistGradient: 925.50s
Beste param HistGradient: {'l2_regularization': np.float64(1.6986797634902007), 'learning_rate': np.float64(0.06272594696514379), 'max_depth': 9, 'max_iter': 638, 'max_leaf_nodes': 90, 'min_samples_leaf': 7}
Beste MAE: -50663.9030

In [21]:
best_params = rsLoop.best_params_
tuned_model = rsLoop.best_estimator_

y_pred = tuned_model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
mape = mean_absolute_percentage_error(y_test, y_pred)
accuracy = 1 - mape

print(f'Mean absolute error: {mae}')
print(f'Mean absolute percentage error: {mape}')
print(f'Accuracy: {accuracy}')

Mean absolute error: 50662.802550964676
Mean absolute percentage error: 0.14810066764575672
Accuracy: 0.8518993323542433

In [ ]:

rsExtra = RandomizedSearchCV(
  estimator=extra,
  param_distributions=model_param['ExtraTrees']['params'],
  n_iter=150,
  cv=5,
  scoring='neg_mean_absolute_error',
  n_jobs=-1,
  verbose=2
)
    
start = time.time()
rsExtra.fit(X_train, y_train)
duration = time.time() - start

print(f"Tijd: {duration:.2f}s")
print(f"Beste param: {rsExtra.best_params_}")
print(f"Beste MAE: {rsExtra.best_score_:.4f}")

Fitting 5 folds for each of 100 candidates, totalling 500 fits
Tijd: 2857.67s
Beste param: {'max_depth': 9, 'max_features': np.float64(0.9124558702471834), 'min_samples_leaf': 2, 'min_samples_split': 4, 'n_estimators': 742}
Beste MAE: -54224.2000

### XGBoost
Tijd XGBoost: 1334.04s
Beste param XGBoost: {'colsample_bytree': np.float64(0.6550054872406584), 'gamma': np.float64(0.08367508771505777), 'learning_rate': np.float64(0.04567558428183022), 'max_depth': 8, 'min_child_weight': 2, 'n_estimators': 609, 'reg_alpha': np.float64(6.924415940372761), 'reg_lambda': np.float64(0.2620475254770348), 'subsample': np.float64(0.970829180420445)}
Beste MAE: -46309.9074
### HistGradient
Tijd HistGradient: 1145.61s
Beste param HistGradient: {'l2_regularization': np.float64(6.796320445820958), 'learning_rate': np.float64(0.02650163315092701), 'max_depth': 9, 'max_iter': 770, 'max_leaf_nodes': 96, 'min_samples_leaf': 4}
Beste MAE: -47550.1241
### ExtraTree
Tijd: 2857.67s
Beste param: {'max_depth': 9, 'max_features': np.float64(0.9124558702471834), 'min_samples_leaf': 2, 'min_samples_split': 4, 'n_estimators': 742}
Beste MAE: -54224.2000
### LightGBM
Tijd LightGBM: 448.79s
Beste param LightGBM: {'subsample': 1.0, 'reg_lambda': 0, 'reg_alpha': 0.5, 'num_leaves': 50, 'n_estimators': 500, 'min_child_samples': 10, 'max_depth': 10, 'learning_rate': 0.1, 'colsample_bytree': 0.8}
Beste MAE: -47344.7920

In [22]:
def run_optuna(model_name):
    def objective(trial):
        # if model_name == 'ExtraTrees':
        #     model = ExtraTreesRegressor(
        #         n_estimators=trial.suggest_int('n_estimators', 100, 500),
        #         max_depth=trial.suggest_int('max_depth', 5, 30),
        #         min_samples_split=trial.suggest_int('min_samples_split', 2, 10),
        #         min_samples_leaf=trial.suggest_int('min_samples_leaf', 1, 10),
        #         random_state=42
        #     )
        if model_name == 'HistGradient':
            model = HistGradientBoostingRegressor(
                learning_rate=trial.suggest_float('learning_rate', 0.01, 0.3),
                max_iter=trial.suggest_int('max_iter', 200, 500),
                max_depth=trial.suggest_int('max_depth', 3, 15),
                max_leaf_nodes=trial.suggest_int('max_leaf_nodes', 20, 100),
                random_state=42
            )
        elif model_name == 'XGBoost':
            model = XGBRegressor(
                n_estimators=trial.suggest_int('n_estimators', 200, 800),
                max_depth=trial.suggest_int('max_depth', 10, 15),
                learning_rate=trial.suggest_float('learning_rate', 0.01, 0.2, log=True),
                subsample=trial.suggest_float('subsample', 0.5, 1.0),
                colsample_bytree=trial.suggest_float('colsample_bytree', 0.5, 1.0),
                reg_alpha=trial.suggest_float('reg_alpha', 0.0, 1.0),
                reg_lambda=trial.suggest_float('reg_lambda', 0.0, 1.0),
                min_child_weight=trial.suggest_int('min_child_weight', 1, 10),
                gamma=trial.suggest_float('gamma', 0, 5),
                random_state=42,
                n_jobs=-1
        )
        elif model_name == 'LightGBM':
            model = LGBMRegressor(
                n_estimators=trial.suggest_int('n_estimators', 200, 800),
                max_depth=trial.suggest_int('max_depth', -1, 15),
                num_leaves=trial.suggest_int('num_leaves', 20, 350),
                learning_rate=trial.suggest_float('learning_rate', 0.01, 0.3, log=True),
                subsample=trial.suggest_float('subsample', 0.6, 1.0),
                colsample_bytree=trial.suggest_float('colsample_bytree', 0.6, 1.0),
                reg_alpha=trial.suggest_float('reg_alpha', 0.0, 1.0),
                reg_lambda=trial.suggest_float('reg_lambda', 0.0, 1.0),
                min_child_samples=trial.suggest_int('min_child_samples', 5, 30),
                random_state=42,
                n_jobs=-1,
                verbosity=-1
            )
        model.fit(X_train, y_train)
        trial.set_user_attr("model", model)
        pred = model.predict(X_test)
        return mean_absolute_error(y_test, pred)
    return objective

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=True)

for name, config in model_param.items():
  print(f"Optuna {name}")
  optres = optuna.create_study(direction="minimize")
  optres.optimize(run_optuna(name), n_trials=200)

  start = time.time()
  duration = time.time() - start

  print(f"Tijd: {duration:.2f}s")
  print(f"Beste params {name}: ", optres.best_params)
  print(f"Beste MAE {name}: ", optres.best_value)

[I 2025-05-15 13:19:13,781] A new study created in memory with name: no-name-bd0ac399-28d4-48fc-94b1-294f0a1cc988

Optuna XGBoost

[I 2025-05-15 13:19:17,416] Trial 0 finished with value: 51287.42578125 and parameters: {'n_estimators': 224, 'max_depth': 13, 'learning_rate': 0.09623804988536312, 'subsample': 0.7564794690614167, 'colsample_bytree': 0.756917752289691, 'reg_alpha': 0.897436335184035, 'reg_lambda': 0.45818536497730755, 'min_child_weight': 6, 'gamma': 2.0290865373425193}. Best is trial 0 with value: 51287.42578125.
[I 2025-05-15 13:19:20,395] Trial 1 finished with value: 51366.8671875 and parameters: {'n_estimators': 379, 'max_depth': 10, 'learning_rate': 0.08607915678215793, 'subsample': 0.5166155246053854, 'colsample_bytree': 0.9129427666230792, 'reg_alpha': 0.8807740127019124, 'reg_lambda': 0.33912251076941424, 'min_child_weight': 6, 'gamma': 4.042702716138605}. Best is trial 0 with value: 51287.42578125.
[I 2025-05-15 13:19:36,301] Trial 2 finished with value: 50987.59765625 and parameters: {'n_estimators': 568, 'max_depth': 15, 'learning_rate': 0.022961205646552192, 'subsample': 0.8453544603524265, 'colsample_bytree': 0.9444610620765921, 'reg_alpha': 0.652397954878338, 'reg_lambda': 0.40241735340040086, 'min_child_weight': 4, 'gamma': 2.2193260093009455}. Best is trial 2 with value: 50987.59765625.
[I 2025-05-15 13:19:44,021] Trial 3 finished with value: 49728.37890625 and parameters: {'n_estimators': 694, 'max_depth': 12, 'learning_rate': 0.034784338464117465, 'subsample': 0.7047059259189734, 'colsample_bytree': 0.6913341098004824, 'reg_alpha': 0.8959936274608582, 'reg_lambda': 0.3336065820926569, 'min_child_weight': 6, 'gamma': 2.9663774326608965}. Best is trial 3 with value: 49728.37890625.
[I 2025-05-15 13:19:50,316] Trial 4 finished with value: 50411.953125 and parameters: {'n_estimators': 644, 'max_depth': 12, 'learning_rate': 0.050640466945343764, 'subsample': 0.7032624557954539, 'colsample_bytree': 0.6565891104351664, 'reg_alpha': 0.91739417303732, 'reg_lambda': 0.1598733656997452, 'min_child_weight': 9, 'gamma': 3.453761011545705}. Best is trial 3 with value: 49728.37890625.
[I 2025-05-15 13:19:56,496] Trial 5 finished with value: 51680.69921875 and parameters: {'n_estimators': 477, 'max_depth': 12, 'learning_rate': 0.1417007851966982, 'subsample': 0.9929206398344228, 'colsample_bytree': 0.855346198743265, 'reg_alpha': 0.1532367515479669, 'reg_lambda': 0.41543207804027915, 'min_child_weight': 6, 'gamma': 0.09660698307802529}. Best is trial 3 with value: 49728.37890625.
[I 2025-05-15 13:20:03,494] Trial 6 finished with value: 50449.40234375 and parameters: {'n_estimators': 558, 'max_depth': 11, 'learning_rate': 0.09588283221378702, 'subsample': 0.9395196654866438, 'colsample_bytree': 0.830252042035276, 'reg_alpha': 0.28035710919735324, 'reg_lambda': 0.9424549869410932, 'min_child_weight': 3, 'gamma': 0.4363664463158412}. Best is trial 3 with value: 49728.37890625.
[I 2025-05-15 13:20:07,720] Trial 7 finished with value: 52297.26171875 and parameters: {'n_estimators': 467, 'max_depth': 11, 'learning_rate': 0.15862083661163678, 'subsample': 0.8531367321459061, 'colsample_bytree': 0.5443491724498912, 'reg_alpha': 0.9824257545958948, 'reg_lambda': 0.4999368279726787, 'min_child_weight': 7, 'gamma': 3.025279100147342}. Best is trial 3 with value: 49728.37890625.
[I 2025-05-15 13:20:11,527] Trial 8 finished with value: 50428.4765625 and parameters: {'n_estimators': 276, 'max_depth': 13, 'learning_rate': 0.029498246102825587, 'subsample': 0.7482117325927377, 'colsample_bytree': 0.8580744970289134, 'reg_alpha': 0.9582963347811341, 'reg_lambda': 0.46024872047074117, 'min_child_weight': 10, 'gamma': 1.8333199114379823}. Best is trial 3 with value: 49728.37890625.
[I 2025-05-15 13:20:20,814] Trial 9 finished with value: 51490.39453125 and parameters: {'n_estimators': 375, 'max_depth': 15, 'learning_rate': 0.012894904104480447, 'subsample': 0.797649344017101, 'colsample_bytree': 0.790517893729492, 'reg_alpha': 0.5647835106960437, 'reg_lambda': 0.5611437228519298, 'min_child_weight': 8, 'gamma': 2.5732289838397997}. Best is trial 3 with value: 49728.37890625.
[I 2025-05-15 13:20:46,954] Trial 10 finished with value: 50591.92578125 and parameters: {'n_estimators': 777, 'max_depth': 14, 'learning_rate': 0.013893252013706697, 'subsample': 0.6055310820274203, 'colsample_bytree': 0.6488867238307734, 'reg_alpha': 0.6805788789030182, 'reg_lambda': 0.0855998816838085, 'min_child_weight': 1, 'gamma': 4.987778249473669}. Best is trial 3 with value: 49728.37890625.
[I 2025-05-15 13:20:53,668] Trial 11 finished with value: 50054.66015625 and parameters: {'n_estimators': 716, 'max_depth': 12, 'learning_rate': 0.04684149996470545, 'subsample': 0.6771631991630221, 'colsample_bytree': 0.6579827215423861, 'reg_alpha': 0.7642851587166697, 'reg_lambda': 0.09222922308933845, 'min_child_weight': 10, 'gamma': 3.5641335192900483}. Best is trial 3 with value: 49728.37890625.
[I 2025-05-15 13:20:59,777] Trial 12 finished with value: 49819.96484375 and parameters: {'n_estimators': 786, 'max_depth': 11, 'learning_rate': 0.04438356041070211, 'subsample': 0.6554262209255981, 'colsample_bytree': 0.6499590030606136, 'reg_alpha': 0.7549233001367619, 'reg_lambda': 0.20997984993955474, 'min_child_weight': 10, 'gamma': 3.9011116257758065}. Best is trial 3 with value: 49728.37890625.
[I 2025-05-15 13:21:05,456] Trial 13 finished with value: 49750.7734375 and parameters: {'n_estimators': 782, 'max_depth': 10, 'learning_rate': 0.029267300675184113, 'subsample': 0.6114551430788718, 'colsample_bytree': 0.5741524312698543, 'reg_alpha': 0.3787626397650812, 'reg_lambda': 0.2543015453130668, 'min_child_weight': 4, 'gamma': 4.539658033243796}. Best is trial 3 with value: 49728.37890625.
[I 2025-05-15 13:21:10,313] Trial 14 finished with value: 49883.08984375 and parameters: {'n_estimators': 673, 'max_depth': 10, 'learning_rate': 0.022881123993572616, 'subsample': 0.568605244850048, 'colsample_bytree': 0.5119958257061055, 'reg_alpha': 0.3610037371260209, 'reg_lambda': 0.6769174586136929, 'min_child_weight': 4, 'gamma': 4.982114693714394}. Best is trial 3 with value: 49728.37890625.
[I 2025-05-15 13:21:16,291] Trial 15 finished with value: 49637.16015625 and parameters: {'n_estimators': 711, 'max_depth': 10, 'learning_rate': 0.03234900091681437, 'subsample': 0.6232594818553195, 'colsample_bytree': 0.5828688331531515, 'reg_alpha': 0.4509238400140364, 'reg_lambda': 0.31164472920580166, 'min_child_weight': 2, 'gamma': 1.1227133616678437}. Best is trial 15 with value: 49637.16015625.
[I 2025-05-15 13:21:37,469] Trial 16 finished with value: 51933.109375 and parameters: {'n_estimators': 601, 'max_depth': 14, 'learning_rate': 0.06287203377580756, 'subsample': 0.5100118122089539, 'colsample_bytree': 0.7062295798108446, 'reg_alpha': 0.006871044412714911, 'reg_lambda': 0.654583472360071, 'min_child_weight': 1, 'gamma': 1.1937146238416192}. Best is trial 15 with value: 49637.16015625.
[I 2025-05-15 13:21:45,674] Trial 17 finished with value: 49489.515625 and parameters: {'n_estimators': 711, 'max_depth': 11, 'learning_rate': 0.03323555544929646, 'subsample': 0.7216421333297576, 'colsample_bytree': 0.5956126209673208, 'reg_alpha': 0.4081598742147398, 'reg_lambda': 0.2817437109175915, 'min_child_weight': 2, 'gamma': 1.191075260748234}. Best is trial 17 with value: 49489.515625.
[I 2025-05-15 13:21:53,902] Trial 18 finished with value: 49856.38671875 and parameters: {'n_estimators': 727, 'max_depth': 11, 'learning_rate': 0.017484676501609286, 'subsample': 0.628964958436304, 'colsample_bytree': 0.5940434731148003, 'reg_alpha': 0.4363020675530055, 'reg_lambda': 0.00952670490351104, 'min_child_weight': 2, 'gamma': 1.2140725549760458}. Best is trial 17 with value: 49489.515625.
[I 2025-05-15 13:21:59,112] Trial 19 finished with value: 50033.51953125 and parameters: {'n_estimators': 630, 'max_depth': 10, 'learning_rate': 0.01990396861792383, 'subsample': 0.5823458973240775, 'colsample_bytree': 0.5947736915482027, 'reg_alpha': 0.5254262614621873, 'reg_lambda': 0.8450057200106545, 'min_child_weight': 2, 'gamma': 1.1490520499555748}. Best is trial 17 with value: 49489.515625.
[I 2025-05-15 13:22:04,592] Trial 20 finished with value: 50230.953125 and parameters: {'n_estimators': 523, 'max_depth': 11, 'learning_rate': 0.0659898845094902, 'subsample': 0.7892443460447653, 'colsample_bytree': 0.5145224592828345, 'reg_alpha': 0.21195976235333763, 'reg_lambda': 0.3177034355806089, 'min_child_weight': 3, 'gamma': 0.7037898764941826}. Best is trial 17 with value: 49489.515625.
[I 2025-05-15 13:22:12,824] Trial 21 finished with value: 49626.125 and parameters: {'n_estimators': 699, 'max_depth': 12, 'learning_rate': 0.032299687896534104, 'subsample': 0.7139294893715643, 'colsample_bytree': 0.7123135216259219, 'reg_alpha': 0.4719603985692971, 'reg_lambda': 0.3311386364724218, 'min_child_weight': 5, 'gamma': 2.6514952464808936}. Best is trial 17 with value: 49489.515625.
[I 2025-05-15 13:22:21,767] Trial 22 finished with value: 49712.734375 and parameters: {'n_estimators': 735, 'max_depth': 11, 'learning_rate': 0.03228895723681748, 'subsample': 0.7251561732734294, 'colsample_bytree': 0.7423611549587286, 'reg_alpha': 0.4386520327082052, 'reg_lambda': 0.24785286790219885, 'min_child_weight': 2, 'gamma': 1.5954171633907515}. Best is trial 17 with value: 49489.515625.
[I 2025-05-15 13:22:26,517] Trial 23 finished with value: 49725.58203125 and parameters: {'n_estimators': 662, 'max_depth': 10, 'learning_rate': 0.0364955572138778, 'subsample': 0.6515201072735481, 'colsample_bytree': 0.6076525356710111, 'reg_alpha': 0.5545372234742222, 'reg_lambda': 0.5642238193309423, 'min_child_weight': 5, 'gamma': 2.4048468995287}. Best is trial 17 with value: 49489.515625.
[I 2025-05-15 13:22:40,183] Trial 24 finished with value: 50051.96484375 and parameters: {'n_estimators': 743, 'max_depth': 13, 'learning_rate': 0.024634697096886628, 'subsample': 0.8171468394247513, 'colsample_bytree': 0.5604193202574829, 'reg_alpha': 0.34905853695090505, 'reg_lambda': 0.1350625596772878, 'min_child_weight': 3, 'gamma': 0.7686832395867457}. Best is trial 17 with value: 49489.515625.
[I 2025-05-15 13:22:50,738] Trial 25 finished with value: 50153.05078125 and parameters: {'n_estimators': 627, 'max_depth': 12, 'learning_rate': 0.01642993818270495, 'subsample': 0.5497981450243514, 'colsample_bytree': 0.7088215740513782, 'reg_alpha': 0.4622103913225604, 'reg_lambda': 0.3043039755376544, 'min_child_weight': 1, 'gamma': 1.5839489892549858}. Best is trial 17 with value: 49489.515625.
[I 2025-05-15 13:22:55,998] Trial 26 finished with value: 49966.55859375 and parameters: {'n_estimators': 585, 'max_depth': 11, 'learning_rate': 0.04015360778537584, 'subsample': 0.6761306621793246, 'colsample_bytree': 0.6293321765130673, 'reg_alpha': 0.6205895230397376, 'reg_lambda': 0.20401253411391312, 'min_child_weight': 5, 'gamma': 2.8374242518711386}. Best is trial 17 with value: 49489.515625.
[I 2025-05-15 13:23:02,727] Trial 27 finished with value: 50017.37890625 and parameters: {'n_estimators': 680, 'max_depth': 10, 'learning_rate': 0.059135308332319766, 'subsample': 0.8987576760795037, 'colsample_bytree': 0.9885876790912311, 'reg_alpha': 0.3014363913137672, 'reg_lambda': 0.3743910487406105, 'min_child_weight': 2, 'gamma': 1.5889207381952677}. Best is trial 17 with value: 49489.515625.
[I 2025-05-15 13:23:14,292] Trial 28 finished with value: 49845.0390625 and parameters: {'n_estimators': 799, 'max_depth': 12, 'learning_rate': 0.027224446958915, 'subsample': 0.7547585173148128, 'colsample_bytree': 0.7574847515037189, 'reg_alpha': 0.15606666514549433, 'reg_lambda': 0.010048745052545716, 'min_child_weight': 3, 'gamma': 0.20175796788904687}. Best is trial 17 with value: 49489.515625.
[I 2025-05-15 13:23:19,576] Trial 29 finished with value: 50922.6015625 and parameters: {'n_estimators': 415, 'max_depth': 13, 'learning_rate': 0.07338159316903889, 'subsample': 0.7278494014971417, 'colsample_bytree': 0.5470076521080035, 'reg_alpha': 0.48651971049166826, 'reg_lambda': 0.5745718564568122, 'min_child_weight': 7, 'gamma': 1.9483933026434068}. Best is trial 17 with value: 49489.515625.
[I 2025-05-15 13:23:31,339] Trial 30 finished with value: 51150.63671875 and parameters: {'n_estimators': 516, 'max_depth': 14, 'learning_rate': 0.010424342054632402, 'subsample': 0.6346948840338282, 'colsample_bytree': 0.7428242801765603, 'reg_alpha': 0.2599512486250328, 'reg_lambda': 0.449537138542964, 'min_child_weight': 4, 'gamma': 0.8891850531807379}. Best is trial 17 with value: 49489.515625.
[I 2025-05-15 13:23:40,737] Trial 31 finished with value: 49734.33203125 and parameters: {'n_estimators': 726, 'max_depth': 11, 'learning_rate': 0.033869463333341246, 'subsample': 0.7160940501152914, 'colsample_bytree': 0.7800766835369224, 'reg_alpha': 0.4237496352904371, 'reg_lambda': 0.26228810612696185, 'min_child_weight': 2, 'gamma': 1.5019959796247304}. Best is trial 17 with value: 49489.515625.
[I 2025-05-15 13:23:51,028] Trial 32 finished with value: 50127.515625 and parameters: {'n_estimators': 761, 'max_depth': 11, 'learning_rate': 0.05089946932516195, 'subsample': 0.7642634301649348, 'colsample_bytree': 0.6774115357788587, 'reg_alpha': 0.4114783906428895, 'reg_lambda': 0.23669549204149778, 'min_child_weight': 1, 'gamma': 2.0771343344695468}. Best is trial 17 with value: 49489.515625.
[I 2025-05-15 13:23:57,324] Trial 33 finished with value: 49345.2890625 and parameters: {'n_estimators': 704, 'max_depth': 10, 'learning_rate': 0.029798649237202657, 'subsample': 0.6883666691667314, 'colsample_bytree': 0.7292485261663177, 'reg_alpha': 0.5850108693346683, 'reg_lambda': 0.3816051320106688, 'min_child_weight': 2, 'gamma': 1.7791174442386202}. Best is trial 33 with value: 49345.2890625.
[I 2025-05-15 13:24:03,281] Trial 34 finished with value: 49630.7578125 and parameters: {'n_estimators': 706, 'max_depth': 10, 'learning_rate': 0.020377824570478834, 'subsample': 0.6712623617487845, 'colsample_bytree': 0.7185498359954947, 'reg_alpha': 0.6059261168549036, 'reg_lambda': 0.35479867707749774, 'min_child_weight': 3, 'gamma': 2.5275433091033106}. Best is trial 33 with value: 49345.2890625.
[I 2025-05-15 13:24:05,432] Trial 35 finished with value: 51817.1328125 and parameters: {'n_estimators': 208, 'max_depth': 10, 'learning_rate': 0.02160971173443671, 'subsample': 0.6840087538206886, 'colsample_bytree': 0.8171417575131626, 'reg_alpha': 0.6029463136425923, 'reg_lambda': 0.3702107555743753, 'min_child_weight': 5, 'gamma': 2.6852837328961385}. Best is trial 33 with value: 49345.2890625.
[I 2025-05-15 13:24:10,329] Trial 36 finished with value: 49578.87890625 and parameters: {'n_estimators': 622, 'max_depth': 10, 'learning_rate': 0.019370073087075886, 'subsample': 0.7016478950144542, 'colsample_bytree': 0.7137601736419462, 'reg_alpha': 0.6954131005324977, 'reg_lambda': 0.4209076708280781, 'min_child_weight': 4, 'gamma': 3.2364219864043466}. Best is trial 33 with value: 49345.2890625.
[I 2025-05-15 13:24:18,282] Trial 37 finished with value: 49845.39453125 and parameters: {'n_estimators': 625, 'max_depth': 12, 'learning_rate': 0.01631248381225591, 'subsample': 0.6972661304481557, 'colsample_bytree': 0.8903254344408769, 'reg_alpha': 0.7631652847256557, 'reg_lambda': 0.43067011182693515, 'min_child_weight': 5, 'gamma': 3.201563511849354}. Best is trial 33 with value: 49345.2890625.
[I 2025-05-15 13:24:22,445] Trial 38 finished with value: 49565.4609375 and parameters: {'n_estimators': 540, 'max_depth': 10, 'learning_rate': 0.025510866342854772, 'subsample': 0.7755673619214812, 'colsample_bytree': 0.6836965770694784, 'reg_alpha': 0.8154135491010012, 'reg_lambda': 0.47813978142323377, 'min_child_weight': 6, 'gamma': 3.360736287468343}. Best is trial 33 with value: 49345.2890625.
[I 2025-05-15 13:24:26,902] Trial 39 finished with value: 50308.6640625 and parameters: {'n_estimators': 554, 'max_depth': 10, 'learning_rate': 0.013398896974964944, 'subsample': 0.8452585089434272, 'colsample_bytree': 0.6249667851846528, 'reg_alpha': 0.835636203159716, 'reg_lambda': 0.5036359436753715, 'min_child_weight': 7, 'gamma': 3.723379124451}. Best is trial 33 with value: 49345.2890625.
[I 2025-05-15 13:24:30,466] Trial 40 finished with value: 49985.83984375 and parameters: {'n_estimators': 451, 'max_depth': 10, 'learning_rate': 0.026129710242512774, 'subsample': 0.7846835793536966, 'colsample_bytree': 0.6764898201462581, 'reg_alpha': 0.7132130350450505, 'reg_lambda': 0.6803594533842792, 'min_child_weight': 6, 'gamma': 3.2720999039900263}. Best is trial 33 with value: 49345.2890625.
[I 2025-05-15 13:24:36,052] Trial 41 finished with value: 49385.8671875 and parameters: {'n_estimators': 600, 'max_depth': 11, 'learning_rate': 0.03761214380864935, 'subsample': 0.7405748037331769, 'colsample_bytree': 0.7224961040834587, 'reg_alpha': 0.8571371755790723, 'reg_lambda': 0.4952493379995139, 'min_child_weight': 6, 'gamma': 4.249911839583942}. Best is trial 33 with value: 49345.2890625.
[I 2025-05-15 13:24:41,468] Trial 42 finished with value: 49850.8984375 and parameters: {'n_estimators': 598, 'max_depth': 11, 'learning_rate': 0.03967947321119905, 'subsample': 0.7490773909320373, 'colsample_bytree': 0.7728794898338657, 'reg_alpha': 0.8639071437329824, 'reg_lambda': 0.5036565213055186, 'min_child_weight': 8, 'gamma': 4.255323736533235}. Best is trial 33 with value: 49345.2890625.
[I 2025-05-15 13:24:45,927] Trial 43 finished with value: 49593.6484375 and parameters: {'n_estimators': 557, 'max_depth': 10, 'learning_rate': 0.025802045248096407, 'subsample': 0.8187848216108591, 'colsample_bytree': 0.7997125097121035, 'reg_alpha': 0.8315549457269285, 'reg_lambda': 0.41259042208348184, 'min_child_weight': 6, 'gamma': 4.235119339385043}. Best is trial 33 with value: 49345.2890625.
[I 2025-05-15 13:24:52,576] Trial 44 finished with value: 54233.328125 and parameters: {'n_estimators': 650, 'max_depth': 11, 'learning_rate': 0.19808884269204857, 'subsample': 0.7367017829752734, 'colsample_bytree': 0.732017622826834, 'reg_alpha': 0.6844315826168287, 'reg_lambda': 0.6216656249378265, 'min_child_weight': 7, 'gamma': 2.3144098425542867}. Best is trial 33 with value: 49345.2890625.
[I 2025-05-15 13:24:56,295] Trial 45 finished with value: 49522.3671875 and parameters: {'n_estimators': 492, 'max_depth': 10, 'learning_rate': 0.044791951168231606, 'subsample': 0.769136114243704, 'colsample_bytree': 0.7596002331926244, 'reg_alpha': 0.933839289836672, 'reg_lambda': 0.48128271966417213, 'min_child_weight': 8, 'gamma': 3.4546167925478897}. Best is trial 33 with value: 49345.2890625.
[I 2025-05-15 13:25:00,800] Trial 46 finished with value: 49757.23046875 and parameters: {'n_estimators': 493, 'max_depth': 11, 'learning_rate': 0.04755254328286775, 'subsample': 0.8762644945464139, 'colsample_bytree': 0.8355351703868916, 'reg_alpha': 0.9308882799564768, 'reg_lambda': 0.47923499387209045, 'min_child_weight': 8, 'gamma': 4.003825790448558}. Best is trial 33 with value: 49345.2890625.
[I 2025-05-15 13:25:03,202] Trial 47 finished with value: 49872.1015625 and parameters: {'n_estimators': 310, 'max_depth': 10, 'learning_rate': 0.05390715514185389, 'subsample': 0.7802708455350034, 'colsample_bytree': 0.6885700132053645, 'reg_alpha': 0.8101243559952127, 'reg_lambda': 0.7495624398942582, 'min_child_weight': 9, 'gamma': 4.731235655769802}. Best is trial 33 with value: 49345.2890625.
[I 2025-05-15 13:25:06,436] Trial 48 finished with value: 49752.91015625 and parameters: {'n_estimators': 438, 'max_depth': 10, 'learning_rate': 0.041800733231216504, 'subsample': 0.8214765699232349, 'colsample_bytree': 0.7597579036728498, 'reg_alpha': 0.8980260609475206, 'reg_lambda': 0.5196522396442345, 'min_child_weight': 9, 'gamma': 3.5595430901690572}. Best is trial 33 with value: 49345.2890625.

Tijd: 0.00s
Beste params XGBoost:  {'n_estimators': 702, 'max_depth': 11, 'learning_rate': 0.03341587956729562, 'subsample': 0.9067542838662811, 'colsample_bytree': 0.5427907826581247, 'reg_alpha': 0.059647169243809806, 'reg_lambda': 0.6797096185328306, 'min_child_weight': 8, 'gamma': 2.218523626972447}

[I 2025-05-15 13:41:09,427] A new study created in memory with name: no-name-c866fb08-43b3-4960-8232-e77463cea1d3

Beste MAE XGBoost:  49130.40625
Optuna HistGradient

[I 2025-05-15 13:41:23,153] Trial 0 finished with value: 52210.39688075906 and parameters: {'learning_rate': 0.11762437885132311, 'max_iter': 459, 'max_depth': 6, 'max_leaf_nodes': 22}. Best is trial 0 with value: 52210.39688075906.
[I 2025-05-15 13:41:25,739] Trial 1 finished with value: 52082.17943708045 and parameters: {'learning_rate': 0.24681928891582963, 'max_iter': 320, 'max_depth': 9, 'max_leaf_nodes': 97}. Best is trial 1 with value: 52082.17943708045.
[I 2025-05-15 13:41:28,997] Trial 2 finished with value: 51742.001149638505 and parameters: {'learning_rate': 0.1713456762402684, 'max_iter': 248, 'max_depth': 8, 'max_leaf_nodes': 91}. Best is trial 2 with value: 51742.001149638505.
[I 2025-05-15 13:41:35,383] Trial 3 finished with value: 50774.33283384302 and parameters: {'learning_rate': 0.11879206313857182, 'max_iter': 444, 'max_depth': 13, 'max_leaf_nodes': 60}. Best is trial 3 with value: 50774.33283384302.
[I 2025-05-15 13:41:37,254] Trial 4 finished with value: 52126.70280917336 and parameters: {'learning_rate': 0.243425112359207, 'max_iter': 433, 'max_depth': 15, 'max_leaf_nodes': 64}. Best is trial 3 with value: 50774.33283384302.
[I 2025-05-15 13:41:38,882] Trial 5 finished with value: 54550.39673862402 and parameters: {'learning_rate': 0.24528778938925058, 'max_iter': 266, 'max_depth': 3, 'max_leaf_nodes': 46}. Best is trial 3 with value: 50774.33283384302.
[I 2025-05-15 13:41:41,013] Trial 6 finished with value: 52122.24784528653 and parameters: {'learning_rate': 0.2624163536362986, 'max_iter': 280, 'max_depth': 15, 'max_leaf_nodes': 94}. Best is trial 3 with value: 50774.33283384302.
[I 2025-05-15 13:41:43,021] Trial 7 finished with value: 52659.67939435447 and parameters: {'learning_rate': 0.29648011636055077, 'max_iter': 235, 'max_depth': 10, 'max_leaf_nodes': 56}. Best is trial 3 with value: 50774.33283384302.
[I 2025-05-15 13:41:45,497] Trial 8 finished with value: 52136.29207123382 and parameters: {'learning_rate': 0.21901766065179418, 'max_iter': 309, 'max_depth': 11, 'max_leaf_nodes': 31}. Best is trial 3 with value: 50774.33283384302.
[I 2025-05-15 13:41:47,994] Trial 9 finished with value: 51822.96279218227 and parameters: {'learning_rate': 0.17190990577809737, 'max_iter': 402, 'max_depth': 6, 'max_leaf_nodes': 80}. Best is trial 3 with value: 50774.33283384302.
[I 2025-05-15 13:42:02,519] Trial 10 finished with value: 51043.868887168275 and parameters: {'learning_rate': 0.025962717847053715, 'max_iter': 500, 'max_depth': 13, 'max_leaf_nodes': 72}. Best is trial 3 with value: 50774.33283384302.
[I 2025-05-15 13:42:16,226] Trial 11 finished with value: 51112.247939962544 and parameters: {'learning_rate': 0.025765195510466146, 'max_iter': 490, 'max_depth': 13, 'max_leaf_nodes': 70}. Best is trial 3 with value: 50774.33283384302.
[I 2025-05-15 13:42:25,533] Trial 12 finished with value: 54628.86596537459 and parameters: {'learning_rate': 0.01094777816201338, 'max_iter': 382, 'max_depth': 12, 'max_leaf_nodes': 49}. Best is trial 3 with value: 50774.33283384302.
[I 2025-05-15 13:42:35,079] Trial 13 finished with value: 50536.508072450226 and parameters: {'learning_rate': 0.08126967456312562, 'max_iter': 494, 'max_depth': 13, 'max_leaf_nodes': 75}. Best is trial 13 with value: 50536.508072450226.
[I 2025-05-15 13:42:40,065] Trial 14 finished with value: 50954.10854538376 and parameters: {'learning_rate': 0.10144467345419064, 'max_iter': 445, 'max_depth': 14, 'max_leaf_nodes': 80}. Best is trial 13 with value: 50536.508072450226.
[I 2025-05-15 13:42:45,521] Trial 15 finished with value: 51055.11625193332 and parameters: {'learning_rate': 0.07447625857785403, 'max_iter': 375, 'max_depth': 11, 'max_leaf_nodes': 37}. Best is trial 13 with value: 50536.508072450226.
[I 2025-05-15 13:42:52,133] Trial 16 finished with value: 50961.93005219873 and parameters: {'learning_rate': 0.062687268115343, 'max_iter': 416, 'max_depth': 13, 'max_leaf_nodes': 57}. Best is trial 13 with value: 50536.508072450226.
[I 2025-05-15 13:42:55,477] Trial 17 finished with value: 51525.34386728777 and parameters: {'learning_rate': 0.1332482633025183, 'max_iter': 468, 'max_depth': 8, 'max_leaf_nodes': 83}. Best is trial 13 with value: 50536.508072450226.
[I 2025-05-15 13:43:02,451] Trial 18 finished with value: 50807.23896907666 and parameters: {'learning_rate': 0.07633125883077213, 'max_iter': 474, 'max_depth': 11, 'max_leaf_nodes': 67}. Best is trial 13 with value: 50536.508072450226.
[I 2025-05-15 13:43:06,317] Trial 19 finished with value: 51179.298475103795 and parameters: {'learning_rate': 0.14389164060816598, 'max_iter': 342, 'max_depth': 14, 'max_leaf_nodes': 46}. Best is trial 13 with value: 50536.508072450226.
[I 2025-05-15 13:43:13,695] Trial 20 finished with value: 50674.234010805165 and parameters: {'learning_rate': 0.09936938855484674, 'max_iter': 424, 'max_depth': 12, 'max_leaf_nodes': 75}. Best is trial 13 with value: 50536.508072450226.
[I 2025-05-15 13:43:21,546] Trial 21 finished with value: 50639.70674258021 and parameters: {'learning_rate': 0.10107881171366187, 'max_iter': 421, 'max_depth': 12, 'max_leaf_nodes': 76}. Best is trial 13 with value: 50536.508072450226.
[I 2025-05-15 13:43:29,373] Trial 22 finished with value: 50852.25954878774 and parameters: {'learning_rate': 0.057561325713957404, 'max_iter': 403, 'max_depth': 12, 'max_leaf_nodes': 78}. Best is trial 13 with value: 50536.508072450226.
[I 2025-05-15 13:43:34,936] Trial 23 finished with value: 50897.83121354776 and parameters: {'learning_rate': 0.09025756538299405, 'max_iter': 366, 'max_depth': 10, 'max_leaf_nodes': 87}. Best is trial 13 with value: 50536.508072450226.
[I 2025-05-15 13:43:45,178] Trial 24 finished with value: 50688.44876261684 and parameters: {'learning_rate': 0.04846796382135036, 'max_iter': 421, 'max_depth': 12, 'max_leaf_nodes': 73}. Best is trial 13 with value: 50536.508072450226.
[I 2025-05-15 13:43:49,297] Trial 25 finished with value: 51640.07228142276 and parameters: {'learning_rate': 0.18825477401427942, 'max_iter': 485, 'max_depth': 14, 'max_leaf_nodes': 75}. Best is trial 13 with value: 50536.508072450226.
[I 2025-05-15 13:43:54,060] Trial 26 finished with value: 50901.89935245609 and parameters: {'learning_rate': 0.10236949553982845, 'max_iter': 391, 'max_depth': 10, 'max_leaf_nodes': 87}. Best is trial 13 with value: 50536.508072450226.
[I 2025-05-15 13:44:00,826] Trial 27 finished with value: 50558.04785494637 and parameters: {'learning_rate': 0.12069685792057966, 'max_iter': 348, 'max_depth': 12, 'max_leaf_nodes': 64}. Best is trial 13 with value: 50536.508072450226.
[I 2025-05-15 13:44:03,519] Trial 28 finished with value: 51577.590521412385 and parameters: {'learning_rate': 0.15784134022078575, 'max_iter': 361, 'max_depth': 9, 'max_leaf_nodes': 63}. Best is trial 13 with value: 50536.508072450226.
[I 2025-05-15 13:44:06,567] Trial 29 finished with value: 51509.98158603592 and parameters: {'learning_rate': 0.12723559503488574, 'max_iter': 342, 'max_depth': 6, 'max_leaf_nodes': 100}. Best is trial 13 with value: 50536.508072450226.
[I 2025-05-15 13:44:08,412] Trial 30 finished with value: 51838.7798561782 and parameters: {'learning_rate': 0.1987131921903965, 'max_iter': 458, 'max_depth': 15, 'max_leaf_nodes': 51}. Best is trial 13 with value: 50536.508072450226.
[I 2025-05-15 13:44:12,509] Trial 31 finished with value: 51126.41916561829 and parameters: {'learning_rate': 0.1055567201113551, 'max_iter': 205, 'max_depth': 12, 'max_leaf_nodes': 70}. Best is trial 13 with value: 50536.508072450226.
[I 2025-05-15 13:44:17,042] Trial 32 finished with value: 51367.21615534791 and parameters: {'learning_rate': 0.08807888283476846, 'max_iter': 333, 'max_depth': 11, 'max_leaf_nodes': 66}. Best is trial 13 with value: 50536.508072450226.
[I 2025-05-15 13:44:20,385] Trial 33 finished with value: 51452.68757931474 and parameters: {'learning_rate': 0.14914775470058284, 'max_iter': 307, 'max_depth': 8, 'max_leaf_nodes': 87}. Best is trial 13 with value: 50536.508072450226.
[I 2025-05-15 13:44:23,448] Trial 34 finished with value: 51214.17895007846 and parameters: {'learning_rate': 0.11636608597313974, 'max_iter': 454, 'max_depth': 14, 'max_leaf_nodes': 76}. Best is trial 13 with value: 50536.508072450226.
[I 2025-05-15 13:44:31,442] Trial 35 finished with value: 50912.18810522967 and parameters: {'learning_rate': 0.04386413888483005, 'max_iter': 423, 'max_depth': 9, 'max_leaf_nodes': 60}. Best is trial 13 with value: 50536.508072450226.
[I 2025-05-15 13:44:35,962] Trial 36 finished with value: 51515.976519117234 and parameters: {'learning_rate': 0.08022636341119369, 'max_iter': 438, 'max_depth': 12, 'max_leaf_nodes': 22}. Best is trial 13 with value: 50536.508072450226.
[I 2025-05-15 13:44:39,071] Trial 37 finished with value: 51231.13734676383 and parameters: {'learning_rate': 0.1251077300809006, 'max_iter': 289, 'max_depth': 13, 'max_leaf_nodes': 83}. Best is trial 13 with value: 50536.508072450226.
[I 2025-05-15 13:44:43,826] Trial 38 finished with value: 51120.32265010398 and parameters: {'learning_rate': 0.10863487899207297, 'max_iter': 354, 'max_depth': 10, 'max_leaf_nodes': 93}. Best is trial 13 with value: 50536.508072450226.
[I 2025-05-15 13:44:45,764] Trial 39 finished with value: 54224.62032048515 and parameters: {'learning_rate': 0.16720627209784328, 'max_iter': 321, 'max_depth': 3, 'max_leaf_nodes': 55}. Best is trial 13 with value: 50536.508072450226.
[I 2025-05-15 13:44:48,158] Trial 40 finished with value: 51487.241285371856 and parameters: {'learning_rate': 0.13648960795346182, 'max_iter': 402, 'max_depth': 15, 'max_leaf_nodes': 68}. Best is trial 13 with value: 50536.508072450226.
[I 2025-05-15 13:44:54,422] Trial 41 finished with value: 51081.76408998608 and parameters: {'learning_rate': 0.04968620646379196, 'max_iter': 422, 'max_depth': 12, 'max_leaf_nodes': 74}. Best is trial 13 with value: 50536.508072450226.
[I 2025-05-15 13:45:01,540] Trial 42 finished with value: 50581.991135119344 and parameters: {'learning_rate': 0.06419847033969242, 'max_iter': 387, 'max_depth': 11, 'max_leaf_nodes': 64}. Best is trial 13 with value: 50536.508072450226.
[I 2025-05-15 13:45:07,547] Trial 43 finished with value: 50893.39795689936 and parameters: {'learning_rate': 0.06740067033172646, 'max_iter': 384, 'max_depth': 11, 'max_leaf_nodes': 62}. Best is trial 13 with value: 50536.508072450226.
[I 2025-05-15 13:45:13,961] Trial 44 finished with value: 50768.929008987376 and parameters: {'learning_rate': 0.0952590227128185, 'max_iter': 398, 'max_depth': 13, 'max_leaf_nodes': 66}. Best is trial 13 with value: 50536.508072450226.
[I 2025-05-15 13:45:24,061] Trial 45 finished with value: 50800.04932979499 and parameters: {'learning_rate': 0.03170902568916614, 'max_iter': 446, 'max_depth': 11, 'max_leaf_nodes': 82}. Best is trial 13 with value: 50536.508072450226.
[I 2025-05-15 13:45:28,042] Trial 46 finished with value: 51068.53536628252 and parameters: {'learning_rate': 0.11888074135707072, 'max_iter': 374, 'max_depth': 13, 'max_leaf_nodes': 59}. Best is trial 13 with value: 50536.508072450226.
[I 2025-05-15 13:45:35,175] Trial 47 finished with value: 50750.84344346594 and parameters: {'learning_rate': 0.08455986517676692, 'max_iter': 411, 'max_depth': 14, 'max_leaf_nodes': 71}. Best is trial 13 with value: 50536.508072450226.
[I 2025-05-15 13:45:41,721] Trial 48 finished with value: 50802.128438706546 and parameters: {'learning_rate': 0.06640319015742702, 'max_iter': 499, 'max_depth': 12, 'max_leaf_nodes': 53}. Best is trial 13 with value: 50536.508072450226.
[I 2025-05-15 13:45:51,829] Trial 49 finished with value: 50778.91622944888 and parameters: {'learning_rate': 0.032839845504097326, 'max_iter': 475, 'max_depth': 11, 'max_leaf_nodes': 78}. Best is trial 13 with value: 50536.508072450226.
[I 2025-05-15 13:45:53,427] Trial 50 finished with value: 52984.040360025545 and parameters: {'learning_rate': 0.29725593411967477, 'max_iter': 439, 'max_depth': 10, 'max_leaf_nodes': 64}. Best is trial 13 with value: 50536.508072450226.
[I 2025-05-15 13:46:01,007] Trial 51 finished with value: 50682.53298448628 and parameters: {'learning_rate': 0.04707203807319636, 'max_iter': 428, 'max_depth': 12, 'max_leaf_nodes': 73}. Best is trial 13 with value: 50536.508072450226.
[I 2025-05-15 13:46:07,315] Trial 52 finished with value: 50704.04020452703 and parameters: {'learning_rate': 0.07390610855033761, 'max_iter': 428, 'max_depth': 13, 'max_leaf_nodes': 78}. Best is trial 13 with value: 50536.508072450226.
[I 2025-05-15 13:46:16,835] Trial 53 finished with value: 52201.72368491844 and parameters: {'learning_rate': 0.016302751160326506, 'max_iter': 384, 'max_depth': 12, 'max_leaf_nodes': 72}. Best is trial 13 with value: 50536.508072450226.
[I 2025-05-15 13:46:26,187] Trial 54 finished with value: 50640.35894547893 and parameters: {'learning_rate': 0.05601304654312449, 'max_iter': 467, 'max_depth': 11, 'max_leaf_nodes': 69}. Best is trial 13 with value: 50536.508072450226.
[I 2025-05-15 13:46:31,812] Trial 55 finished with value: 50688.94445705785 and parameters: {'learning_rate': 0.11373159505923855, 'max_iter': 469, 'max_depth': 11, 'max_leaf_nodes': 69}. Best is trial 13 with value: 50536.508072450226.
[I 2025-05-15 13:46:35,922] Trial 56 finished with value: 50925.46375681494 and parameters: {'learning_rate': 0.09515486320608019, 'max_iter': 485, 'max_depth': 14, 'max_leaf_nodes': 57}. Best is trial 13 with value: 50536.508072450226.
[I 2025-05-15 13:46:37,230] Trial 57 finished with value: 52748.23996482149 and parameters: {'learning_rate': 0.2662922041802718, 'max_iter': 453, 'max_depth': 9, 'max_leaf_nodes': 62}. Best is trial 13 with value: 50536.508072450226.
[I 2025-05-15 13:46:44,485] Trial 58 finished with value: 50783.42496844581 and parameters: {'learning_rate': 0.06482686573782374, 'max_iter': 410, 'max_depth': 10, 'max_leaf_nodes': 76}. Best is trial 13 with value: 50536.508072450226.
[I 2025-05-15 13:46:51,067] Trial 59 finished with value: 50931.536766025376 and parameters: {'learning_rate': 0.057481022330458736, 'max_iter': 465, 'max_depth': 13, 'max_leaf_nodes': 81}. Best is trial 13 with value: 50536.508072450226.
[I 2025-05-15 13:46:54,547] Trial 60 finished with value: 51178.878317795235 and parameters: {'learning_rate': 0.09748861799499824, 'max_iter': 364, 'max_depth': 13, 'max_leaf_nodes': 45}. Best is trial 13 with value: 50536.508072450226.
[I 2025-05-15 13:47:03,138] Trial 61 finished with value: 50877.505345890095 and parameters: {'learning_rate': 0.038559911453280846, 'max_iter': 431, 'max_depth': 12, 'max_leaf_nodes': 65}. Best is trial 13 with value: 50536.508072450226.
[I 2025-05-15 13:47:09,273] Trial 62 finished with value: 50752.11200738776 and parameters: {'learning_rate': 0.0795893997644917, 'max_iter': 493, 'max_depth': 12, 'max_leaf_nodes': 85}. Best is trial 13 with value: 50536.508072450226.
[I 2025-05-15 13:47:16,938] Trial 63 finished with value: 50854.91389938438 and parameters: {'learning_rate': 0.04925200868944588, 'max_iter': 481, 'max_depth': 11, 'max_leaf_nodes': 73}. Best is trial 13 with value: 50536.508072450226.
[I 2025-05-15 13:47:24,098] Trial 64 finished with value: 50455.68245976384 and parameters: {'learning_rate': 0.07258695355653169, 'max_iter': 393, 'max_depth': 11, 'max_leaf_nodes': 69}. Best is trial 64 with value: 50455.68245976384.
[I 2025-05-15 13:47:27,862] Trial 65 finished with value: 51094.95922732739 and parameters: {'learning_rate': 0.08577251415605291, 'max_iter': 374, 'max_depth': 10, 'max_leaf_nodes': 68}. Best is trial 64 with value: 50455.68245976384.
[I 2025-05-15 13:47:34,445] Trial 66 finished with value: 50923.81710525602 and parameters: {'learning_rate': 0.05784350072000586, 'max_iter': 336, 'max_depth': 11, 'max_leaf_nodes': 70}. Best is trial 64 with value: 50455.68245976384.
[I 2025-05-15 13:47:38,241] Trial 67 finished with value: 51155.047941185054 and parameters: {'learning_rate': 0.13252214137829846, 'max_iter': 395, 'max_depth': 11, 'max_leaf_nodes': 90}. Best is trial 64 with value: 50455.68245976384.
[I 2025-05-15 13:47:44,516] Trial 68 finished with value: 50637.30500702515 and parameters: {'learning_rate': 0.07404957265404946, 'max_iter': 410, 'max_depth': 10, 'max_leaf_nodes': 79}. Best is trial 64 with value: 50455.68245976384.
[I 2025-05-15 13:47:47,678] Trial 69 finished with value: 51311.77771058501 and parameters: {'learning_rate': 0.10799731238342158, 'max_iter': 357, 'max_depth': 9, 'max_leaf_nodes': 79}. Best is trial 64 with value: 50455.68245976384.
[I 2025-05-15 13:47:52,337] Trial 70 finished with value: 50997.446019198476 and parameters: {'learning_rate': 0.07315843847298462, 'max_iter': 408, 'max_depth': 8, 'max_leaf_nodes': 60}. Best is trial 64 with value: 50455.68245976384.
[I 2025-05-15 13:47:56,656] Trial 71 finished with value: 50994.089681912395 and parameters: {'learning_rate': 0.0714668511090034, 'max_iter': 389, 'max_depth': 10, 'max_leaf_nodes': 76}. Best is trial 64 with value: 50455.68245976384.
[I 2025-05-15 13:48:01,300] Trial 72 finished with value: 50942.39602739618 and parameters: {'learning_rate': 0.0911186961894017, 'max_iter': 417, 'max_depth': 12, 'max_leaf_nodes': 67}. Best is trial 64 with value: 50455.68245976384.
[I 2025-05-15 13:48:07,766] Trial 73 finished with value: 50820.29084756132 and parameters: {'learning_rate': 0.05856334937858386, 'max_iter': 376, 'max_depth': 11, 'max_leaf_nodes': 85}. Best is trial 64 with value: 50455.68245976384.
[I 2025-05-15 13:48:13,484] Trial 74 finished with value: 50701.77209403835 and parameters: {'learning_rate': 0.08221519446058043, 'max_iter': 447, 'max_depth': 10, 'max_leaf_nodes': 75}. Best is trial 64 with value: 50455.68245976384.
[I 2025-05-15 13:48:19,969] Trial 75 finished with value: 50710.264258500814 and parameters: {'learning_rate': 0.10265267885441874, 'max_iter': 463, 'max_depth': 12, 'max_leaf_nodes': 71}. Best is trial 64 with value: 50455.68245976384.
[I 2025-05-15 13:48:28,544] Trial 76 finished with value: 51864.42860129605 and parameters: {'learning_rate': 0.020196660783128872, 'max_iter': 345, 'max_depth': 13, 'max_leaf_nodes': 81}. Best is trial 64 with value: 50455.68245976384.
[I 2025-05-15 13:48:30,881] Trial 77 finished with value: 52736.54736836634 and parameters: {'learning_rate': 0.12563284448442158, 'max_iter': 319, 'max_depth': 4, 'max_leaf_nodes': 63}. Best is trial 64 with value: 50455.68245976384.
[I 2025-05-15 13:48:34,326] Trial 78 finished with value: 51138.410660756665 and parameters: {'learning_rate': 0.14406204866539074, 'max_iter': 437, 'max_depth': 10, 'max_leaf_nodes': 78}. Best is trial 64 with value: 50455.68245976384.
[I 2025-05-15 13:48:41,345] Trial 79 finished with value: 50747.45072902968 and parameters: {'learning_rate': 0.05485831066160849, 'max_iter': 393, 'max_depth': 11, 'max_leaf_nodes': 68}. Best is trial 64 with value: 50455.68245976384.
[I 2025-05-15 13:48:47,509] Trial 80 finished with value: 51199.08998607488 and parameters: {'learning_rate': 0.03974249090935755, 'max_iter': 400, 'max_depth': 7, 'max_leaf_nodes': 65}. Best is trial 64 with value: 50455.68245976384.
[I 2025-05-15 13:48:55,742] Trial 81 finished with value: 50539.576703487335 and parameters: {'learning_rate': 0.04805604040766171, 'max_iter': 412, 'max_depth': 12, 'max_leaf_nodes': 73}. Best is trial 64 with value: 50455.68245976384.
[I 2025-05-15 13:49:02,804] Trial 82 finished with value: 50699.460983251316 and parameters: {'learning_rate': 0.06569003439482385, 'max_iter': 410, 'max_depth': 12, 'max_leaf_nodes': 75}. Best is trial 64 with value: 50455.68245976384.
[I 2025-05-15 13:49:07,823] Trial 83 finished with value: 50900.85373010828 and parameters: {'learning_rate': 0.07930004060820824, 'max_iter': 417, 'max_depth': 13, 'max_leaf_nodes': 71}. Best is trial 64 with value: 50455.68245976384.

Tijd: 0.00s
Beste params HistGradient:  {'learning_rate': 0.07132678642273478, 'max_iter': 450, 'max_depth': 11, 'max_leaf_nodes': 73}
Beste MAE HistGradient:  50422.51862966884
Optuna LightGBM

[I 2025-05-15 14:00:46,099] Trial 0 finished with value: 52442.64215295251 and parameters: {'n_estimators': 560, 'max_depth': 7, 'num_leaves': 308, 'learning_rate': 0.010570694558407333, 'subsample': 0.923762201281982, 'colsample_bytree': 0.7122198078544845, 'reg_alpha': 0.5108866535957972, 'reg_lambda': 0.6134670956962479, 'min_child_samples': 13}. Best is trial 0 with value: 52442.64215295251.
[I 2025-05-15 14:00:46,865] Trial 1 finished with value: 50324.088413883765 and parameters: {'n_estimators': 349, 'max_depth': 15, 'num_leaves': 26, 'learning_rate': 0.13764783660663482, 'subsample': 0.944110658839844, 'colsample_bytree': 0.8488271034744499, 'reg_alpha': 0.4780033377362457, 'reg_lambda': 0.1654647297987396, 'min_child_samples': 19}. Best is trial 1 with value: 50324.088413883765.
[I 2025-05-15 14:00:47,088] Trial 2 finished with value: 78447.31391168895 and parameters: {'n_estimators': 208, 'max_depth': 1, 'num_leaves': 151, 'learning_rate': 0.017689589652966905, 'subsample': 0.6298771790078115, 'colsample_bytree': 0.8760544167339692, 'reg_alpha': 0.16655502558427393, 'reg_lambda': 0.3074636758928194, 'min_child_samples': 26}. Best is trial 1 with value: 50324.088413883765.
[I 2025-05-15 14:00:51,817] Trial 3 finished with value: 51096.57697470102 and parameters: {'n_estimators': 537, 'max_depth': 0, 'num_leaves': 150, 'learning_rate': 0.011497722449465765, 'subsample': 0.8657345860230857, 'colsample_bytree': 0.7497912978736726, 'reg_alpha': 0.09184906172976781, 'reg_lambda': 0.685880564369044, 'min_child_samples': 21}. Best is trial 1 with value: 50324.088413883765.
[I 2025-05-15 14:00:55,753] Trial 4 finished with value: 49780.913767340826 and parameters: {'n_estimators': 343, 'max_depth': 12, 'num_leaves': 342, 'learning_rate': 0.040101845508293155, 'subsample': 0.9795619578323432, 'colsample_bytree': 0.7779205013030291, 'reg_alpha': 0.9189518125202376, 'reg_lambda': 0.32402432750231147, 'min_child_samples': 26}. Best is trial 4 with value: 49780.913767340826.
[I 2025-05-15 14:00:59,217] Trial 5 finished with value: 50533.08251752421 and parameters: {'n_estimators': 524, 'max_depth': 9, 'num_leaves': 117, 'learning_rate': 0.018302856691924, 'subsample': 0.9697905132965833, 'colsample_bytree': 0.6545022136141977, 'reg_alpha': 0.5770785750332665, 'reg_lambda': 0.254664905287902, 'min_child_samples': 20}. Best is trial 4 with value: 49780.913767340826.
[I 2025-05-15 14:01:00,215] Trial 6 finished with value: 56340.973927948435 and parameters: {'n_estimators': 492, 'max_depth': 4, 'num_leaves': 78, 'learning_rate': 0.01366888160536383, 'subsample': 0.9456588199016471, 'colsample_bytree': 0.9350853036922937, 'reg_alpha': 0.40026726968136705, 'reg_lambda': 0.39579742848602073, 'min_child_samples': 12}. Best is trial 4 with value: 49780.913767340826.
[I 2025-05-15 14:01:01,175] Trial 7 finished with value: 52823.22032606527 and parameters: {'n_estimators': 366, 'max_depth': 7, 'num_leaves': 21, 'learning_rate': 0.03338518977213293, 'subsample': 0.7593557171552145, 'colsample_bytree': 0.9962984960372606, 'reg_alpha': 0.37359478738009144, 'reg_lambda': 0.05758582779363397, 'min_child_samples': 12}. Best is trial 4 with value: 49780.913767340826.
[I 2025-05-15 14:01:02,581] Trial 8 finished with value: 51439.85329876069 and parameters: {'n_estimators': 789, 'max_depth': 4, 'num_leaves': 277, 'learning_rate': 0.08043085839550707, 'subsample': 0.7157610401697067, 'colsample_bytree': 0.8619297519068572, 'reg_alpha': 0.28988267903037157, 'reg_lambda': 0.5672597727451941, 'min_child_samples': 26}. Best is trial 4 with value: 49780.913767340826.
[I 2025-05-15 14:01:03,157] Trial 9 finished with value: 70068.01045949174 and parameters: {'n_estimators': 552, 'max_depth': 1, 'num_leaves': 213, 'learning_rate': 0.01151102522123266, 'subsample': 0.7723487700882631, 'colsample_bytree': 0.8232667411171543, 'reg_alpha': 0.8743824550276205, 'reg_lambda': 0.40883238267834343, 'min_child_samples': 15}. Best is trial 4 with value: 49780.913767340826.
[I 2025-05-15 14:01:07,587] Trial 10 finished with value: 52480.957583579206 and parameters: {'n_estimators': 271, 'max_depth': 15, 'num_leaves': 344, 'learning_rate': 0.22687056137870273, 'subsample': 0.8563042992033184, 'colsample_bytree': 0.6356063518932707, 'reg_alpha': 0.9548387991280731, 'reg_lambda': 0.9764391712195432, 'min_child_samples': 5}. Best is trial 4 with value: 49780.913767340826.
[I 2025-05-15 14:01:10,796] Trial 11 finished with value: 50242.69719736399 and parameters: {'n_estimators': 357, 'max_depth': 15, 'num_leaves': 237, 'learning_rate': 0.08888214761278318, 'subsample': 0.9989968121519417, 'colsample_bytree': 0.766630459342785, 'reg_alpha': 0.709028518001527, 'reg_lambda': 0.05026748265109912, 'min_child_samples': 30}. Best is trial 4 with value: 49780.913767340826.
[I 2025-05-15 14:01:14,054] Trial 12 finished with value: 49630.484522034916 and parameters: {'n_estimators': 397, 'max_depth': 12, 'num_leaves': 235, 'learning_rate': 0.05209497376626379, 'subsample': 0.9978511817512125, 'colsample_bytree': 0.7593218927716151, 'reg_alpha': 0.7875457282662562, 'reg_lambda': 0.005751333103406739, 'min_child_samples': 30}. Best is trial 12 with value: 49630.484522034916.
[I 2025-05-15 14:01:17,503] Trial 13 finished with value: 49843.200575065115 and parameters: {'n_estimators': 452, 'max_depth': 11, 'num_leaves': 258, 'learning_rate': 0.04026047049547009, 'subsample': 0.887551609163235, 'colsample_bytree': 0.703338507290478, 'reg_alpha': 0.7766924429056097, 'reg_lambda': 0.8311360938986395, 'min_child_samples': 30}. Best is trial 12 with value: 49630.484522034916.
[I 2025-05-15 14:01:21,731] Trial 14 finished with value: 49654.974754725554 and parameters: {'n_estimators': 411, 'max_depth': 12, 'num_leaves': 328, 'learning_rate': 0.031419496288655265, 'subsample': 0.9998191648785, 'colsample_bytree': 0.7882830161744421, 'reg_alpha': 0.6743935513692683, 'reg_lambda': 1.8776884151651928e-05, 'min_child_samples': 25}. Best is trial 12 with value: 49630.484522034916.
[I 2025-05-15 14:01:27,595] Trial 15 finished with value: 49455.42492799487 and parameters: {'n_estimators': 625, 'max_depth': 12, 'num_leaves': 297, 'learning_rate': 0.026565910462345285, 'subsample': 0.8221633678746825, 'colsample_bytree': 0.7153314181238855, 'reg_alpha': 0.6680848723673068, 'reg_lambda': 0.0077459718607366355, 'min_child_samples': 23}. Best is trial 15 with value: 49455.42492799487.
[I 2025-05-15 14:01:31,558] Trial 16 finished with value: 49327.83733463355 and parameters: {'n_estimators': 675, 'max_depth': 10, 'num_leaves': 195, 'learning_rate': 0.057345155411504464, 'subsample': 0.6853409082070077, 'colsample_bytree': 0.6023042259998731, 'reg_alpha': 0.7973316454517856, 'reg_lambda': 0.1646950459376859, 'min_child_samples': 23}. Best is trial 16 with value: 49327.83733463355.
[I 2025-05-15 14:01:35,205] Trial 17 finished with value: 49787.2208285767 and parameters: {'n_estimators': 655, 'max_depth': 9, 'num_leaves': 183, 'learning_rate': 0.024868020830690014, 'subsample': 0.6650222210174105, 'colsample_bytree': 0.6152771586724141, 'reg_alpha': 0.6148541521970634, 'reg_lambda': 0.1701335541179031, 'min_child_samples': 23}. Best is trial 16 with value: 49327.83733463355.
[I 2025-05-15 14:01:39,831] Trial 18 finished with value: 49724.38865297847 and parameters: {'n_estimators': 665, 'max_depth': 10, 'num_leaves': 276, 'learning_rate': 0.07775594501777928, 'subsample': 0.8292482111121245, 'colsample_bytree': 0.6844025657710949, 'reg_alpha': 0.7779989497609513, 'reg_lambda': 0.17861421956703374, 'min_child_samples': 17}. Best is trial 16 with value: 49327.83733463355.
[I 2025-05-15 14:01:41,148] Trial 19 finished with value: 50518.451150974 and parameters: {'n_estimators': 650, 'max_depth': 5, 'num_leaves': 185, 'learning_rate': 0.12530151946834472, 'subsample': 0.7215470625908702, 'colsample_bytree': 0.6122261419278375, 'reg_alpha': 0.8394890362111919, 'reg_lambda': 0.11370500567074315, 'min_child_samples': 23}. Best is trial 16 with value: 49327.83733463355.
[I 2025-05-15 14:01:49,212] Trial 20 finished with value: 49382.44847742236 and parameters: {'n_estimators': 762, 'max_depth': 13, 'num_leaves': 296, 'learning_rate': 0.05919304201755945, 'subsample': 0.6141522274602849, 'colsample_bytree': 0.6717806015160414, 'reg_alpha': 0.9952046889453515, 'reg_lambda': 0.4504648976764752, 'min_child_samples': 17}. Best is trial 16 with value: 49327.83733463355.
[I 2025-05-15 14:01:57,381] Trial 21 finished with value: 49544.372525172505 and parameters: {'n_estimators': 781, 'max_depth': 13, 'num_leaves': 298, 'learning_rate': 0.06124764717985876, 'subsample': 0.6195262036657765, 'colsample_bytree': 0.6665487493389478, 'reg_alpha': 0.9991231929986397, 'reg_lambda': 0.4787059107444933, 'min_child_samples': 17}. Best is trial 16 with value: 49327.83733463355.
[I 2025-05-15 14:02:03,867] Trial 22 finished with value: 50431.183380233204 and parameters: {'n_estimators': 724, 'max_depth': 13, 'num_leaves': 216, 'learning_rate': 0.12209596170501219, 'subsample': 0.6715463294470513, 'colsample_bytree': 0.7248382664457937, 'reg_alpha': 0.6713953585081072, 'reg_lambda': 0.24312165433800617, 'min_child_samples': 9}. Best is trial 16 with value: 49327.83733463355.
[I 2025-05-15 14:02:08,110] Trial 23 finished with value: 49593.62033920332 and parameters: {'n_estimators': 615, 'max_depth': 10, 'num_leaves': 303, 'learning_rate': 0.05500909109712337, 'subsample': 0.8053465152164309, 'colsample_bytree': 0.656656879621108, 'reg_alpha': 0.8734414370204092, 'reg_lambda': 0.7195022603242889, 'min_child_samples': 22}. Best is trial 16 with value: 49327.83733463355.
[I 2025-05-15 14:02:15,528] Trial 24 finished with value: 49348.20682727331 and parameters: {'n_estimators': 721, 'max_depth': 13, 'num_leaves': 263, 'learning_rate': 0.024391883801327223, 'subsample': 0.6050465263793843, 'colsample_bytree': 0.6156203060276548, 'reg_alpha': 0.997539350538861, 'reg_lambda': 0.4639416393166119, 'min_child_samples': 16}. Best is trial 16 with value: 49327.83733463355.
[I 2025-05-15 14:02:23,289] Trial 25 finished with value: 49258.1202089372 and parameters: {'n_estimators': 726, 'max_depth': 14, 'num_leaves': 252, 'learning_rate': 0.02140300612942801, 'subsample': 0.600716811409515, 'colsample_bytree': 0.6019816224523655, 'reg_alpha': 0.9785053040209186, 'reg_lambda': 0.5017203232766904, 'min_child_samples': 15}. Best is trial 25 with value: 49258.1202089372.
[I 2025-05-15 14:02:30,015] Trial 26 finished with value: 49490.425357470325 and parameters: {'n_estimators': 712, 'max_depth': 14, 'num_leaves': 208, 'learning_rate': 0.019580193314539262, 'subsample': 0.6576332720180535, 'colsample_bytree': 0.6031539004575368, 'reg_alpha': 0.9138841943704475, 'reg_lambda': 0.5381040060791282, 'min_child_samples': 9}. Best is trial 25 with value: 49258.1202089372.
[I 2025-05-15 14:02:34,575] Trial 27 finished with value: 49630.881159441255 and parameters: {'n_estimators': 712, 'max_depth': 9, 'num_leaves': 247, 'learning_rate': 0.023792524601195852, 'subsample': 0.7028685089017586, 'colsample_bytree': 0.634161166676432, 'reg_alpha': 0.8289273356877769, 'reg_lambda': 0.6702424674763686, 'min_child_samples': 15}. Best is trial 25 with value: 49258.1202089372.
[I 2025-05-15 14:02:39,308] Trial 28 finished with value: 50131.62955950776 and parameters: {'n_estimators': 588, 'max_depth': 14, 'num_leaves': 153, 'learning_rate': 0.01488811007863074, 'subsample': 0.6444432449557453, 'colsample_bytree': 0.630537511389408, 'reg_alpha': 0.9383343400404963, 'reg_lambda': 0.7857396227664939, 'min_child_samples': 19}. Best is trial 25 with value: 49258.1202089372.
[I 2025-05-15 14:02:42,028] Trial 29 finished with value: 49805.97073348941 and parameters: {'n_estimators': 736, 'max_depth': 7, 'num_leaves': 269, 'learning_rate': 0.042124430670586896, 'subsample': 0.6138567854188179, 'colsample_bytree': 0.6016602553300484, 'reg_alpha': 0.7257278698308097, 'reg_lambda': 0.36402945019493993, 'min_child_samples': 14}. Best is trial 25 with value: 49258.1202089372.
[I 2025-05-15 14:02:45,634] Trial 30 finished with value: 49970.81070551943 and parameters: {'n_estimators': 679, 'max_depth': 8, 'num_leaves': 172, 'learning_rate': 0.022861928495147503, 'subsample': 0.6019264686744321, 'colsample_bytree': 0.6928606787266613, 'reg_alpha': 0.5360305311271403, 'reg_lambda': 0.6145762116917709, 'min_child_samples': 10}. Best is trial 25 with value: 49258.1202089372.
[I 2025-05-15 14:02:52,148] Trial 31 finished with value: 49684.89199632844 and parameters: {'n_estimators': 751, 'max_depth': 13, 'num_leaves': 223, 'learning_rate': 0.06672639095094549, 'subsample': 0.6830923145615451, 'colsample_bytree': 0.6679845978688962, 'reg_alpha': 0.968763323901537, 'reg_lambda': 0.46328336916838103, 'min_child_samples': 17}. Best is trial 25 with value: 49258.1202089372.
[I 2025-05-15 14:02:58,147] Trial 32 finished with value: 50067.93409725834 and parameters: {'n_estimators': 770, 'max_depth': 11, 'num_leaves': 321, 'learning_rate': 0.0961727201114958, 'subsample': 0.6393476457324271, 'colsample_bytree': 0.6448369185526851, 'reg_alpha': 0.9788102047596382, 'reg_lambda': 0.4883627886656686, 'min_child_samples': 19}. Best is trial 25 with value: 49258.1202089372.
[I 2025-05-15 14:03:05,546] Trial 33 finished with value: 49471.34706838288 and parameters: {'n_estimators': 692, 'max_depth': 14, 'num_leaves': 281, 'learning_rate': 0.048256169199925834, 'subsample': 0.6102166960631823, 'colsample_bytree': 0.6005779947051427, 'reg_alpha': 0.8816472740256317, 'reg_lambda': 0.576506407816105, 'min_child_samples': 14}. Best is trial 25 with value: 49258.1202089372.
[I 2025-05-15 14:03:11,219] Trial 34 finished with value: 49352.69233147279 and parameters: {'n_estimators': 588, 'max_depth': 11, 'num_leaves': 260, 'learning_rate': 0.03596660186114959, 'subsample': 0.6936989647160596, 'colsample_bytree': 0.6817056198765788, 'reg_alpha': 0.819561474865327, 'reg_lambda': 0.26922021386470746, 'min_child_samples': 16}. Best is trial 25 with value: 49258.1202089372.
[I 2025-05-15 14:03:16,022] Trial 35 finished with value: 49404.389299396076 and parameters: {'n_estimators': 586, 'max_depth': 11, 'num_leaves': 198, 'learning_rate': 0.03306305549973302, 'subsample': 0.744897509013917, 'colsample_bytree': 0.7356456062397723, 'reg_alpha': 0.8251485216118102, 'reg_lambda': 0.27285369544637583, 'min_child_samples': 15}. Best is trial 25 with value: 49258.1202089372.
[I 2025-05-15 14:03:20,540] Trial 36 finished with value: 49490.64817320899 and parameters: {'n_estimators': 601, 'max_depth': 10, 'num_leaves': 253, 'learning_rate': 0.02871111792794975, 'subsample': 0.6895236781316966, 'colsample_bytree': 0.6279683001276635, 'reg_alpha': 0.9093622802395664, 'reg_lambda': 0.33441262827414925, 'min_child_samples': 19}. Best is trial 25 with value: 49258.1202089372.
[I 2025-05-15 14:03:25,106] Trial 37 finished with value: 49856.48305505443 and parameters: {'n_estimators': 637, 'max_depth': 15, 'num_leaves': 127, 'learning_rate': 0.019918103338920183, 'subsample': 0.6400640691894569, 'colsample_bytree': 0.8168264690996947, 'reg_alpha': 0.03749873322457142, 'reg_lambda': 0.22861602390562805, 'min_child_samples': 11}. Best is trial 25 with value: 49258.1202089372.
[I 2025-05-15 14:03:27,258] Trial 38 finished with value: 51646.561183351594 and parameters: {'n_estimators': 507, 'max_depth': 8, 'num_leaves': 62, 'learning_rate': 0.016484648964435408, 'subsample': 0.7377139158866421, 'colsample_bytree': 0.6468943130743179, 'reg_alpha': 0.47911027489995334, 'reg_lambda': 0.10297544131878894, 'min_child_samples': 21}. Best is trial 25 with value: 49258.1202089372.
[I 2025-05-15 14:03:29,464] Trial 39 finished with value: 50497.00861016128 and parameters: {'n_estimators': 800, 'max_depth': 6, 'num_leaves': 229, 'learning_rate': 0.037509825959028, 'subsample': 0.7758561430205062, 'colsample_bytree': 0.902525765857859, 'reg_alpha': 0.19645216113486796, 'reg_lambda': 0.4204462785719961, 'min_child_samples': 13}. Best is trial 25 with value: 49258.1202089372.
[I 2025-05-15 14:03:34,086] Trial 40 finished with value: 50459.61979935607 and parameters: {'n_estimators': 566, 'max_depth': 11, 'num_leaves': 163, 'learning_rate': 0.012656767670655515, 'subsample': 0.6568766958352057, 'colsample_bytree': 0.6837456815241253, 'reg_alpha': 0.7628894911140408, 'reg_lambda': 0.2873063118449921, 'min_child_samples': 16}. Best is trial 25 with value: 49258.1202089372.
[I 2025-05-15 14:03:41,821] Trial 41 finished with value: 49347.639199847865 and parameters: {'n_estimators': 747, 'max_depth': 13, 'num_leaves': 290, 'learning_rate': 0.04515745407781205, 'subsample': 0.6020310751351925, 'colsample_bytree': 0.6713382810423487, 'reg_alpha': 0.9991712166847466, 'reg_lambda': 0.36135310497662715, 'min_child_samples': 18}. Best is trial 25 with value: 49258.1202089372.
[I 2025-05-15 14:03:48,071] Trial 42 finished with value: 49431.50251795406 and parameters: {'n_estimators': 680, 'max_depth': 14, 'num_leaves': 262, 'learning_rate': 0.04683787170432047, 'subsample': 0.6001508225436188, 'colsample_bytree': 0.620501148818405, 'reg_alpha': 0.9385658535184882, 'reg_lambda': 0.35962592026153173, 'min_child_samples': 28}. Best is trial 25 with value: 49258.1202089372.
[I 2025-05-15 14:03:55,784] Trial 43 finished with value: 49374.438192451926 and parameters: {'n_estimators': 737, 'max_depth': 13, 'num_leaves': 323, 'learning_rate': 0.035389503535583317, 'subsample': 0.6322906791568618, 'colsample_bytree': 0.6519640338630665, 'reg_alpha': 0.8697214703365308, 'reg_lambda': 0.5225849535390118, 'min_child_samples': 20}. Best is trial 25 with value: 49258.1202089372.
[I 2025-05-15 14:04:02,795] Trial 44 finished with value: 49348.43612289046 and parameters: {'n_estimators': 702, 'max_depth': 12, 'num_leaves': 280, 'learning_rate': 0.02149798472042991, 'subsample': 0.6815921986566544, 'colsample_bytree': 0.7034287463297271, 'reg_alpha': 0.9329898619099807, 'reg_lambda': 0.2085424911802164, 'min_child_samples': 18}. Best is trial 25 with value: 49258.1202089372.
[I 2025-05-15 14:04:10,908] Trial 45 finished with value: 50155.13814832465 and parameters: {'n_estimators': 688, 'max_depth': 12, 'num_leaves': 285, 'learning_rate': 0.010790956990697133, 'subsample': 0.6249797553318058, 'colsample_bytree': 0.7392532607094982, 'reg_alpha': 0.903493531716442, 'reg_lambda': 0.1899168087373302, 'min_child_samples': 18}. Best is trial 25 with value: 49258.1202089372.
[I 2025-05-15 14:04:21,856] Trial 46 finished with value: 49394.98913883582 and parameters: {'n_estimators': 717, 'max_depth': 15, 'num_leaves': 315, 'learning_rate': 0.02194815640681765, 'subsample': 0.6696964505740032, 'colsample_bytree': 0.7045618272488721, 'reg_alpha': 0.9533032138851472, 'reg_lambda': 0.1116734190995676, 'min_child_samples': 25}. Best is trial 25 with value: 49258.1202089372.
[I 2025-05-15 14:04:26,058] Trial 47 finished with value: 53919.29043828805 and parameters: {'n_estimators': 215, 'max_depth': -1, 'num_leaves': 343, 'learning_rate': 0.015479768769194983, 'subsample': 0.6504844530671864, 'colsample_bytree': 0.6221976391545719, 'reg_alpha': 0.3969905912695837, 'reg_lambda': 0.38023314674998654, 'min_child_samples': 21}. Best is trial 25 with value: 49258.1202089372.
[I 2025-05-15 14:04:33,804] Trial 48 finished with value: 52584.92863753034 and parameters: {'n_estimators': 756, 'max_depth': 12, 'num_leaves': 244, 'learning_rate': 0.2123346781627942, 'subsample': 0.7145979772898905, 'colsample_bytree': 0.9631717047073276, 'reg_alpha': 0.9970012221560031, 'reg_lambda': 0.21733884684889854, 'min_child_samples': 13}. Best is trial 25 with value: 49258.1202089372.

Tijd: 0.00s
Beste params LightGBM:  {'n_estimators': 725, 'max_depth': 13, 'num_leaves': 203, 'learning_rate': 0.03441489414795745, 'subsample': 0.9607189226837076, 'colsample_bytree': 0.600584267464685, 'reg_alpha': 0.0367710312215926, 'reg_lambda': 0.05482079934133707, 'min_child_samples': 19}
Beste MAE LightGBM:  48961.120502551305

extratrees word verder genegeerd door de zeer lange trainingtijden en slechte finetuning resultaten, hierdoor heb ik dit vervamgen met LGBM doordat dit gelijkaardig zou moetten testen als XGB op mijn model

Optuna XGBoost

Tijd: 0.00s
Beste params XGBoost:  {'n_estimators': 702, 'max_depth': 11, 'learning_rate': 0.03341587956729562, 'subsample': 0.9067542838662811, 'colsample_bytree': 0.5427907826581247, 'reg_alpha': 0.059647169243809806, 'reg_lambda': 0.6797096185328306, 'min_child_weight': 8, 'gamma': 2.218523626972447}
[I 2025-05-15 13:41:09,427] A new study created in memory with name: no-name-c866fb08-43b3-4960-8232-e77463cea1d3
Beste MAE XGBoost:  49130.40625

Optuna HistGradient

Tijd: 0.00s
Beste params HistGradient:  {'learning_rate': 0.07132678642273478, 'max_iter': 450, 'max_depth': 11, 'max_leaf_nodes': 73}
Beste MAE HistGradient:  50422.51862966884

Optuna LightGBM

Beste params LightGBM:  {'n_estimators': 725, 'max_depth': 13, 'num_leaves': 203, 'learning_rate': 0.03441489414795745, 'subsample': 0.9607189226837076, 'colsample_bytree': 0.600584267464685, 'reg_alpha': 0.0367710312215926, 'reg_lambda': 0.05482079934133707, 'min_child_samples': 19}
Beste MAE LightGBM:  48961.120502551305

In [26]:
print(optres.best_trial.user_attrs)

{'model': LGBMRegressor(colsample_bytree=0.600584267464685,
              learning_rate=0.03441489414795745, max_depth=13,
              min_child_samples=19, n_estimators=725, n_jobs=-1, num_leaves=203,
              random_state=42, reg_alpha=0.0367710312215926,
              reg_lambda=0.05482079934133707, subsample=0.9607189226837076,
              verbosity=-1)}

In [27]:
best_params = optres.best_params
tuned_model = optres.best_trial.user_attrs['model']

y_pred = tuned_model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
mape = mean_absolute_percentage_error(y_test, y_pred)
accuracy = 1 - mape

print(f'Mean absolute error: {mae}')
print(f'Mean absolute percentage error: {mape}')
print(f'Accuracy: {accuracy}')

Mean absolute error: 48961.120502551305
Mean absolute percentage error: 0.14284014800967923
Accuracy: 0.8571598519903207

In [29]:
besteModel = optres.best_trial
#opslaan bij models
lgbmModelDir = os.getcwd()
lgbmModelPath = os.path.join(lgbmModelDir, ".",
                          "models", "lightGBM.pkl")
os.makedirs(os.path.dirname(lgbmModelPath), exist_ok=True)
with open(lgbmModelPath, 'wb') as m:
    pickle.dump(besteModel.user_attrs['model'], m)

## Best so far
### LightGBM
Mean absolute error: 45337.28982557999
Mean absolute percentage error: 0.1334235812403486
Accuracy: 0.8665764187596514

GridsearchCV

In [24]:

#parameters
model_param = {
    'XGBoost': {
        'model': XGBRegressor(),
        'params': {
            'n_estimators': [850],
            'learning_rate': [0.025, 0.03],
            'max_depth': [8, 9],
            'min_child_weight': [1,2],
            'subsample': [1.0],
            'colsample_bytree': [0.8],
            'gamma': [0.035, 0.04],
            'reg_lambda': [3],
            'reg_alpha': range(0, 5, 1)
        }
    },
    'HistGradient': {
        'model': HistGradientBoostingRegressor(),
        'params': {
            'n_estimators': [850],
            'learning_rate': [0.01, 0.1],
            'max_iter': [100, 200],
            'max_depth': [3, 5],
            'l2_regularization': [0.1, 1],
            'min_samples_leaf': [1, 2],
            'max_leaf_nodes': [20, 40]
        }
    },
    'LightGBM': {
        'model': LGBMRegressor(),
        'params': {
            'n_estimators': [850],
            'num_leaves': [31, 50],
            'learning_rate': [0.01, 0.1],
            'n_estimators': [100, 200],
            'max_depth': [-1, 5],
            'min_child_samples': [10, 20],
            'subsample': [0.6, 0.8],
            'colsample_bytree': [0.6, 0.8],
            'reg_alpha': [0, 0.1],
            'reg_lambda': [0, 0.1]
        }
    }
}

hist = HistGradientBoostingRegressor()
xgb = XGBRegressor()
lgbm = LGBMRegressor()

In [ ]:
for name, config in model_param.items():
    print(f"Model: {name}")
    model = config['model']
    param = config['params']
    
    gs = GridSearchCV(
        estimator=model,
        param_grid=param,
        cv=5,
        scoring='neg_mean_absolute_error',
        n_jobs=-1,
        verbose=2
    )
    
    start = time.time()
    gs.fit(X_train, y_train)
    duration = time.time() - start

    print(f"Tijd {name}: {duration:.2f}s")
    print(f"Beste param {name}: {gs.best_params_}")
    print(f"Beste MAE: {gs.best_score_:.4f}")

Model: XGBoost
Fitting 5 folds for each of 80 candidates, totalling 400 fits

KeyboardInterrupt:

Resultaten tuned model

In [75]:
best_params = gs.best_params_
tuned_model = gs.best_estimator_

y_pred = tuned_model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
mape = mean_absolute_percentage_error(y_test, y_pred)
accuracy = 1 - mape

print(f'Mean absolute error: {mae}')
print(f'Mean absolute percentage error: {mape}')
print(f'Accuracy: {accuracy}')

NameError: name 'gs' is not defined

### model opslaan met beste parameters

In [27]:
besteModel = LGBMRegressor(
    n_estimators=788,
    max_depth=0,
    num_leaves=213,
    learning_rate=0.027352468420388434,
    subsample=0.8257111258276627,
    colsample_bytree=0.7709277343834496,
    reg_alpha=0.7512362258288539,
    reg_lambda=0.23466677100487698,
    min_child_samples=8,
    random_state=42,
    n_jobs=-1,
    verbosity=-1
)

besteModel.fit(X_train, y_train)
pred = besteModel.predict(X_test)
mae = mean_absolute_error(y_test, pred)
print(f"MAE: {mae:.4f}")

MAE: 48910.7069

In [78]:
#opslaan bij models
lgbmModelDir = os.getcwd()
lgbmModelPath = os.path.join(lgbmModelDir, ".",
                          "models", "lightGBM.pkl")
os.makedirs(os.path.dirname(lgbmModelPath), exist_ok=True)
with open(lgbmModelPath, 'wb') as m:
    pickle.dump(besteModel, m)