In [54]:
import pandas as pd
import numpy as np
import os
import pickle
import time
import optuna
import warnings

from category_encoders import TargetEncoder
from xgboost import XGBRegressor
from scipy.stats import randint, uniform
from lightgbm import LGBMRegressor


from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.linear_model import Lasso, LinearRegression
from sklearn.model_selection import train_test_split, cross_val_score, RandomizedSearchCV, _search_successive_halving, GridSearchCV
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor, ExtraTreesRegressor, HistGradientBoostingRegressor 
from sklearn.metrics import mean_absolute_error, mean_absolute_percentage_error

warnings.filterwarnings("ignore")

In [55]:
cleanData = pd.read_csv('./data csv/kijkcijfersWeer.csv')
cleanData.sample(5)

,Unnamed: 0,FullDate,date,hour,Kanaal,Programma,Lengte_sec,Kijkers,Temperatuur,Gevoelstemp,Regen,Sneeuw,Weercode,Bewolking,Windsnelheid,Zonnenschijn,isFeestdag,Weekdag,isWeekend,Seizoen
37149,37149,2021-11-24 21:00:38,2021-11-24,21,VTM2,VB. C1 UEFA - CL.BRUGGE/LEIPZIG,5760,482798,4.3,1.9,0.0,0.0,3,100,6.4,0.0,0,2,0,herfst
19695,19695,2019-06-17 18:20:15,2019-06-17,18,VTM,DE BUURTPOLITIE,1582,203679,23.6,22.9,0.0,0.0,1,31,12.4,3600.0,0,0,0,lente
25490,25490,2020-04-04 21:34:12,2020-04-04,21,EEN,PRIDE & PREJUDICE,7231,290136,10.9,8.4,0.0,0.0,2,51,7.7,0.0,0,5,1,lente
31663,31663,2021-02-23 21:27:50,2021-02-23,21,EEN,WAAR IS MARK?,2040,675676,14.0,10.4,0.0,0.0,0,0,23.1,0.0,0,1,0,winter
3284,3284,2017-03-17 18:59:50,2017-03-17,18,VTM,NIEUWS 19U VTM,3092,606984,10.2,5.2,0.0,0.0,3,98,19.0,3600.0,0,4,0,winter

Feature engineering

In [56]:
def lagFeatures(df, n):
  for i in range(1,n+1):
    df[f'KijkersLag{i}'] = df.sort_values('FullDate').groupby('Programma')['Kijkers'].shift(i).fillna(df.groupby('Programma')['Kijkers'].transform('mean'))
  return df

In [57]:
cleanData = lagFeatures(cleanData, 3)
cleanData[cleanData['Programma'] == 'THUIS'][['FullDate', 'Kijkers', 'KijkersLag1', 'KijkersLag2', 'KijkersLag3']]

                  FullDate  Kijkers   KijkersLag1   KijkersLag2   KijkersLag3
40     2016-10-03 20:14:23  1268561  1.059928e+06  1.059928e+06  1.059928e+06
60     2016-10-04 20:09:27  1169791  1.268561e+06  1.059928e+06  1.059928e+06
80     2016-10-05 20:13:52  1244502  1.169791e+06  1.268561e+06  1.059928e+06
121    2016-10-07 19:57:34  1156477  1.244502e+06  1.169791e+06  1.268561e+06
180    2016-10-10 19:59:00  1315826  1.156477e+06  1.244502e+06  1.169791e+06
...                    ...      ...           ...           ...           ...
61265  2025-04-04 20:24:13   779244  1.018053e+06  9.942260e+05  1.066599e+06
61325  2025-04-07 20:14:35   869193  7.792440e+05  1.018053e+06  9.942260e+05
61345  2025-04-08 20:13:09   880767  8.691930e+05  7.792440e+05  1.018053e+06
61366  2025-04-09 20:19:53   802132  8.807670e+05  8.691930e+05  7.792440e+05
61386  2025-04-10 20:14:08   799990  8.021320e+05  8.807670e+05  8.691930e+05

[1838 rows x 5 columns]

Kardinaliteiten

In [58]:
#kardinaliteiten voor betere toepassingen
for kolom in cleanData.columns:
  print(f'{kolom}: {cleanData[kolom].nunique()}')

Unnamed: 0: 61405
FullDate: 61318
date: 3051
hour: 21
Kanaal: 29
Programma: 5963
Lengte_sec: 6774
Kijkers: 58860
Temperatuur: 414
Gevoelstemp: 478
Regen: 62
Sneeuw: 25
Weercode: 13
Bewolking: 101
Windsnelheid: 456
Zonnenschijn: 3555
isFeestdag: 2
Weekdag: 7
isWeekend: 2
Seizoen: 4
KijkersLag1: 58998
KijkersLag2: 56714
KijkersLag3: 55143

One Hot Encoding

In [59]:
#one hot encoding voor lage cardinaliteit
oneHotEnc = OneHotEncoder(handle_unknown="ignore")
lageKardinaliteit = cleanData[[ 'hour','Kanaal', 'isFeestdag', 'Weekdag', 'Seizoen']]
oneHot = oneHotEnc.fit_transform(lageKardinaliteit)
dfOneHot = pd.DataFrame(oneHot.toarray(), 
                            columns=oneHotEnc.get_feature_names_out(), 
                            index=lageKardinaliteit.index)

cleanData = cleanData.drop(columns=['hour', 'Kanaal', 'isFeestdag', 'Weekdag', 'Seizoen'])
cleanData = pd.concat([cleanData, dfOneHot], axis=1)

cleanData.sample(5)

,Unnamed: 0,FullDate,date,Programma,Lengte_sec,Kijkers,Temperatuur,Gevoelstemp,Regen,Sneeuw,...,Weekdag_1,Weekdag_2,Weekdag_3,Weekdag_4,Weekdag_5,Weekdag_6,Seizoen_herfst,Seizoen_lente,Seizoen_winter,Seizoen_zomer
24592,24592,2020-02-19 20:30:57,2020-02-19,DE AFSPRAAK,3220,288366,6.4,2.4,0.1,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
51336,51338,2023-11-08 21:58:13,2023-11-08,"MOORDZAKEN, WETSDOKTERS",3287,379224,10.7,6.2,0.3,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
17230,17230,2019-02-14 22:50:56,2019-02-14,HET JOURNAAL LAAT,931,340188,3.6,0.7,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
18037,18037,2019-03-26 21:20:33,2019-03-26,TERUG NAAR RWANDA,2739,169798,5.1,2.4,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
21630,21630,2019-09-24 22:52:47,2019-09-24,HET JOURNAAL LAAT,1139,356263,15.0,14.1,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [60]:
#opslaan bij models
modelsDir = os.getcwd()
modelFile = os.path.join(modelsDir, ".",
                          "models", "oneHotEncoder.pkl")
os.makedirs(os.path.dirname(modelFile), exist_ok=True)
with open(modelFile, 'wb') as m:
  pickle.dump(oneHotEnc, m)

Target Encoding

In [61]:
#target encoding voor medium kardinaliteiten
targetEncoding = TargetEncoder()
medKardinaliteit = cleanData[['date', 'Programma', 'Lengte_sec', 'Temperatuur', 'Gevoelstemp', 'Regen', 'Bewolking', 'Windsnelheid', 'Zonnenschijn']]
#verdere feature engineering op vorig model
target = targetEncoding.fit_transform(medKardinaliteit, cleanData['Kijkers'])
target.sample(10)

,date,Programma,Lengte_sec,Temperatuur,Gevoelstemp,Regen,Bewolking,Windsnelheid,Zonnenschijn
53040,446625.82396,242060.656727,1657,9.2,5.1,0.0,100,22.4,0.00
33443,428042.67396,585853.225914,2803,14.4,9.6,0.0,100,23.7,2087.08
29832,501105.59896,317279.214567,6072,10.2,8.1,0.6,100,13.1,0.00
4947,448956.87396,273924.285714,1608,17.7,14.3,0.0,23,19.9,3600.00
30303,542070.39896,585853.225914,3316,8.6,5.3,0.0,44,16.1,0.00
12257,400990.27396,318450.257376,3429,20.6,20.1,0.0,81,15.9,3600.00
50059,435892.77396,233684.866438,1063,22.2,24.5,0.0,0,8.3,0.00
13860,414252.67396,697551.381773,1751,16.2,15.7,0.0,97,5.4,3397.82
19640,366118.17396,585853.225914,2518,18.1,18.4,0.0,43,3.2,3600.00
9955,498279.57396,427876.980663,5576,4.7,1.2,0.0,2,12.5,0.00

In [62]:
cleanData = cleanData.drop(columns=['date', 'Programma', 'Lengte_sec', 'Temperatuur', 'Gevoelstemp', 'Regen', 'Bewolking', 'Windsnelheid', 'Zonnenschijn'])
cleanData = pd.concat([cleanData, target], axis=1)
cleanData.sample(5)

,Unnamed: 0,FullDate,Kijkers,Sneeuw,Weercode,isWeekend,KijkersLag1,KijkersLag2,KijkersLag3,hour_0,...,Seizoen_zomer,date,Programma,Lengte_sec,Temperatuur,Gevoelstemp,Regen,Bewolking,Windsnelheid,Zonnenschijn
49509,49511,2023-08-09 19:41:31,600604,0.0,0,0,690291.000000,764542.000000,728610.000000,0.0,...,1.0,409610.92396,628487.089971,2195,18.9,17.2,0.0,0,9.9,3600.0
46492,46494,2023-03-10 20:06:04,518214,0.0,51,0,527890.000000,571927.000000,533312.000000,0.0,...,0.0,450105.59896,617095.220955,1515,2.9,-3.0,0.1,96,23.7,0.0
5073,5073,2017-06-15 23:09:13,192135,0.0,1,0,154203.333333,154203.333333,154203.333333,0.0,...,0.0,446149.44896,400821.814655,1759,17.3,14.5,0.0,38,19.6,0.0
15431,15431,2018-11-16 23:07:36,210736,0.0,0,0,191372.000000,376254.000000,250303.000000,0.0,...,0.0,445478.84896,289674.236832,973,4.8,2.3,0.0,0,7.7,0.0
43941,43942,2022-10-31 12:59:37,235901,0.0,3,0,195514.000000,173822.000000,181779.000000,0.0,...,0.0,445354.47396,242060.656727,1720,14.3,13.9,0.0,86,8.2,3600.0

Verbanden

In [63]:
dataOneHotTarget = cleanData.select_dtypes(include=[np.number])

verband = dataOneHotTarget.corr()

verband = verband['Kijkers'].abs().sort_values(ascending=False)

print(f'{verband.head(10)}')
dataOneHotTarget.shape

Kijkers        1.000000
KijkersLag1    0.894582
KijkersLag2    0.893195
KijkersLag3    0.875979
Programma      0.827215
hour_19        0.386184
Kanaal_EEN     0.333420
date           0.333361
hour_22        0.184308
hour_17        0.176407
Name: Kijkers, dtype: float64

(61405, 80)

In [64]:
# Eerst omzetten naar strings, daarna komma's verwijderen, en uiteindelijk naar floats
for col in ['KijkersLag1', 'KijkersLag2', 'KijkersLag3', 'Programma']:
    cleanData[col] = cleanData[col].astype(str).str.replace(',', '').astype(float)

# Print het resultaat
print(cleanData[['Kijkers', 'KijkersLag1', 'KijkersLag2', 'KijkersLag3', 'Programma']].head(10))

   Kijkers    KijkersLag1    KijkersLag2    KijkersLag3      Programma
0   721850  892001.072096  892001.072096  892001.072096  892001.072096
1   709606  628487.089971  628487.089971  628487.089971  628487.089971
2   548239  478421.179487  478421.179487  478421.179487  474186.638952
3   523610  791862.682708  791862.682708  791862.682708  791862.682708
4   496216  491224.740741  491224.740741  491224.740741  491217.906057
5   447427  351454.000000  351454.000000  351454.000000  431290.191170
6   424041  585853.225914  585853.225914  585853.225914  585853.225914
7   369066  408691.165611  408691.165611  408691.165611  408691.165611
8   368549  336230.500000  336230.500000  336230.500000  424185.509591
9   360544  332870.588235  332870.588235  332870.588235  332901.616764

In [65]:
#opslaan bij models
targetModelDir = os.getcwd()
targetModelPath = os.path.join(targetModelDir, ".",
                          "models", "oneHotTarget.pkl")
os.makedirs(os.path.dirname(targetModelPath), exist_ok=True)
with open(targetModelPath, 'wb') as m:
  pickle.dump(targetEncoding, m)

Model tests

In [53]:
def test_models(models, X, y, cv=10, scoring='neg_mean_absolute_error'):
    res = {}
    for m in models:
        model = type(m).__name__
        scores = cross_val_score(m, X, y, cv=cv, scoring=scoring)
        res[model] = {
            'scores': scores,
            'mean_score': scores.mean()
        }
        print(f"Scores {model}\n{scores}\nMAE = {scores.mean()}")
    return res

Lasso Regression

In [28]:
models = [
    RandomForestRegressor(verbose=True), Lasso()
]

# Zorg ervoor dat X en y goed geschaald zijn
scaler = StandardScaler()
X = dataOneHotTarget.drop(columns=['Kijkers', 'Unnamed: 0'])
X_scaled = scaler.fit_transform(X)
y = dataOneHotTarget['Kijkers']

# Run de test
results = test_models(models, X_scaled, y)

[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:  1.0min

KeyboardInterrupt:

RandomForest heeft betere scores:
  
  RandomForest
  MAE = -52082.47210795064

  Lasso
  MAE = -64622.292775108515

Naar csv schrijven

In [ ]:
dir = os.getcwd()
pathFile = os.path.join(dir, "./data csv/oneHotTarget.csv")

os.makedirs(os.path.dirname(pathFile), exist_ok=True)

dataOneHotTarget.to_csv(pathFile)

keuze maken voor model

In [ ]:
#trainset en testset maken
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=True)

def scoreModel(model,X,y, cv=5):
    print(f"Model: {model.__class__.__name__}")
    start = time.time()
        
    # MAE
    mae_scores = cross_val_score(model, X, y, cv=cv, scoring='neg_mean_absolute_error')
    mae = -np.mean(mae_scores)

    # MAPE
    mape_scores = cross_val_score(model, X, y, cv=cv, scoring='neg_mean_absolute_percentage_error')
    mape = -np.mean(mape_scores) * 100

    duration = time.time() - start
    min, sec = divmod(duration, 60)

    print(f"MAE:  {mae:.4f}")
    print(f"MAPE: {mape:.2f}%")
    print(f"Tijd: {int(min)}m {sec:.1f}s")

    return {'Model': model.__class__.__name__, 'MAE': mae, 'MAPE': mape, 'Tijd': duration}
def startModel(models, X, y, cv=5):
    results = []
    for model in models:
        result = scoreModel(model, X, y, cv=cv)
        results.append(result)
    return results

In [ ]:
linear = LinearRegression()
decision = DecisionTreeRegressor()
randomForest = RandomForestRegressor()
gradientBoosting = GradientBoostingRegressor()
xgb = XGBRegressor()
extraTrees = ExtraTreesRegressor()
histGB = HistGradientBoostingRegressor()

startModel([linear, decision, randomForest, gradientBoosting, xgb, extraTrees, histGB], X, y)

Model: LinearRegression
MAE:  65143.6876
MAPE: 20.22%
Tijd: 0m 1.5s
Model: DecisionTreeRegressor

KeyboardInterrupt:

# Best models:

## Model: ExtraTreesRegressor

MAE:  51912.1192

MAPE: 15.50%

Tijd: 11m 29.4s

## Model: HistGradientBoostingRegressor

MAE:  52753.3521

MAPE: 15.64%

Tijd: 0m 11.3s

## Model: XGBRegressor

MAE:  53561.6539

MAPE: 15.62%

Tijd: 0m 4.2s

## RandomForest er niet bij want 18m+ traintijd voor slechts 200 MAE verschil met XGB

LGBM zou ook een goede optie moetten zijn

ExtraTrees: Beste nauwkeurigheid maar lange training tijd

HistGradientBoosting en XGB: Veel sneller met minimale performance drop

Verbeteren van de top 3 modellen

In [66]:
warnings.filterwarnings("ignore")

#parameters
model_param = {
    # 'XGBoost': {
    #     'model': XGBRegressor(),
    #     'params': {
    #         'n_estimators': randint(100, 1000),
    #         'learning_rate': uniform(0.01, 0.3),
    #         'max_depth': randint(3, 15),
    #         'min_child_weight': randint(1, 10),
    #         'subsample': uniform(0.6, 0.4),
    #         'colsample_bytree': uniform(0.6, 0.4),
    #         'gamma': uniform(0, 0.5),
    #         'reg_lambda': uniform(0.1, 10),
    #         'reg_alpha': uniform(0, 10)
    #     }
    # },
    # 'HistGradient': {
    #     'model': HistGradientBoostingRegressor(),
    #     'params': {
    #         'learning_rate': uniform(0.01, 0.3),
    #         'max_iter': randint(100, 1000),
    #         'max_depth': randint(3, 15),
    #         'l2_regularization': uniform(0.1, 10),
    #         'min_samples_leaf': randint(1, 10),
    #         'max_leaf_nodes': randint(20, 100)
    #     }
    # },
    "LightGBM": {
        "model": LGBMRegressor(),
        "params": {
            "num_leaves": [31, 50, 70],
            "learning_rate": [0.01, 0.05, 0.1, 0.15],
            "n_estimators": [100, 200, 500],
            "max_depth": [-1, 5, 10, 20],
            "min_child_samples": [10, 20, 30],
            "subsample": [0.6, 0.8, 1.0],
            "colsample_bytree": [0.6, 0.8, 1.0],
            "reg_alpha": [0, 0.1, 0.5],
            "reg_lambda": [0, 0.1, 0.5]
        }
    }
}

extra = ExtraTreesRegressor()
hist = HistGradientBoostingRegressor()
xgb = XGBRegressor()
lgbm = LGBMRegressor()

Random Search

In [ ]:
for name, config in model_param.items():
    print(f"Model: {name}")
    model = config['model']
    param = config['params']
    
    rsLoop = RandomizedSearchCV(
        estimator=model,
        param_distributions=param,
        n_iter=250,
        cv=5,
        scoring='neg_mean_absolute_error',
        n_jobs=-1,
        verbose=2
    )
    
    start = time.time()
    rsLoop.fit(X_train, y_train)
    duration = time.time() - start

    print(f"Tijd {name}: {duration:.2f}s")
    print(f"Beste param {name}: {rsLoop.best_params_}")
    print(f"Beste MAE: {rsLoop.best_score_:.4f}")

Model: XGBoost
Fitting 5 folds for each of 250 candidates, totalling 1250 fits

KeyboardInterrupt:

In [ ]:
best_params = rsLoop.best_params_
tuned_model = rsLoop.best_estimator_

y_pred = tuned_model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
mape = mean_absolute_percentage_error(y_test, y_pred)
accuracy = 1 - mape

print(f'Mean absolute error: {mae}')
print(f'Mean absolute percentage error: {mape}')
print(f'Accuracy: {accuracy}')

Mean absolute error: 47585.56428634255
Mean absolute percentage error: 0.14202693123140966
Accuracy: 0.8579730687685904

In [ ]:

rsExtra = RandomizedSearchCV(
  estimator=extra,
  param_distributions=model_param['ExtraTrees']['params'],
  n_iter=150,
  cv=5,
  scoring='neg_mean_absolute_error',
  n_jobs=-1,
  verbose=2
)
    
start = time.time()
rsExtra.fit(X_train, y_train)
duration = time.time() - start

print(f"Tijd: {duration:.2f}s")
print(f"Beste param: {rsExtra.best_params_}")
print(f"Beste MAE: {rsExtra.best_score_:.4f}")

Fitting 5 folds for each of 100 candidates, totalling 500 fits
Tijd: 2857.67s
Beste param: {'max_depth': 9, 'max_features': np.float64(0.9124558702471834), 'min_samples_leaf': 2, 'min_samples_split': 4, 'n_estimators': 742}
Beste MAE: -54224.2000

### XGBoost
Tijd XGBoost: 1334.04s
Beste param XGBoost: {'colsample_bytree': np.float64(0.6550054872406584), 'gamma': np.float64(0.08367508771505777), 'learning_rate': np.float64(0.04567558428183022), 'max_depth': 8, 'min_child_weight': 2, 'n_estimators': 609, 'reg_alpha': np.float64(6.924415940372761), 'reg_lambda': np.float64(0.2620475254770348), 'subsample': np.float64(0.970829180420445)}
Beste MAE: -46309.9074
### HistGradient
Tijd HistGradient: 1145.61s
Beste param HistGradient: {'l2_regularization': np.float64(6.796320445820958), 'learning_rate': np.float64(0.02650163315092701), 'max_depth': 9, 'max_iter': 770, 'max_leaf_nodes': 96, 'min_samples_leaf': 4}
Beste MAE: -47550.1241
### ExtraTree
Tijd: 2857.67s
Beste param: {'max_depth': 9, 'max_features': np.float64(0.9124558702471834), 'min_samples_leaf': 2, 'min_samples_split': 4, 'n_estimators': 742}
Beste MAE: -54224.2000
### LightGBM
Tijd LightGBM: 448.79s
Beste param LightGBM: {'subsample': 1.0, 'reg_lambda': 0, 'reg_alpha': 0.5, 'num_leaves': 50, 'n_estimators': 500, 'min_child_samples': 10, 'max_depth': 10, 'learning_rate': 0.1, 'colsample_bytree': 0.8}
Beste MAE: -47344.7920

In [ ]:
def run_optuna(model_name):
    def objective(trial):
        # if model_name == 'ExtraTrees':
        #     model = ExtraTreesRegressor(
        #         n_estimators=trial.suggest_int('n_estimators', 100, 500),
        #         max_depth=trial.suggest_int('max_depth', 5, 30),
        #         min_samples_split=trial.suggest_int('min_samples_split', 2, 10),
        #         min_samples_leaf=trial.suggest_int('min_samples_leaf', 1, 10),
        #         random_state=42
        #     )
        # if model_name == 'HistGradient':
        #     model = HistGradientBoostingRegressor(
        #         learning_rate=trial.suggest_float('learning_rate', 0.01, 0.3),
        #         max_iter=trial.suggest_int('max_iter', 200, 500),
        #         max_depth=trial.suggest_int('max_depth', 3, 15),
        #         max_leaf_nodes=trial.suggest_int('max_leaf_nodes', 20, 100),
        #         random_state=42
        #     )
        # if model_name == 'XGBoost':
        #     model = XGBRegressor(
        #         n_estimators=trial.suggest_int('n_estimators', 200, 800),
        #         max_depth=trial.suggest_int('max_depth', 10, 15),
        #         learning_rate=trial.suggest_float('learning_rate', 0.01, 0.2, log=True),
        #         subsample=trial.suggest_float('subsample', 0.5, 1.0),
        #         colsample_bytree=trial.suggest_float('colsample_bytree', 0.5, 1.0),
        #         reg_alpha=trial.suggest_float('reg_alpha', 0.0, 1.0),
        #         reg_lambda=trial.suggest_float('reg_lambda', 0.0, 1.0),
        #         min_child_weight=trial.suggest_int('min_child_weight', 1, 10),
        #         gamma=trial.suggest_float('gamma', 0, 5),
        #         random_state=42,
        #         n_jobs=-1
        # )
        if model_name == 'LightGBM':
            model = LGBMRegressor(
                n_estimators=trial.suggest_int('n_estimators', 200, 800),
                max_depth=trial.suggest_int('max_depth', -1, 15),
                num_leaves=trial.suggest_int('num_leaves', 20, 350),
                learning_rate=trial.suggest_float('learning_rate', 0.01, 0.3, log=True),
                subsample=trial.suggest_float('subsample', 0.6, 1.0),
                colsample_bytree=trial.suggest_float('colsample_bytree', 0.6, 1.0),
                reg_alpha=trial.suggest_float('reg_alpha', 0.0, 1.0),
                reg_lambda=trial.suggest_float('reg_lambda', 0.0, 1.0),
                min_child_samples=trial.suggest_int('min_child_samples', 5, 30),
                random_state=42,
                n_jobs=-1,
                verbosity=-1
            )
        model.fit(X_train, y_train)
        trial.set_user_attr("model", model)
        pred = model.predict(X_test)
        return mean_absolute_error(y_test, pred)
    return objective

In [69]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=True)

for name, config in model_param.items():
  print(f"Optuna {name}")
  optres = optuna.create_study(direction="minimize")
  optres.optimize(run_optuna(name), n_trials=500)

  start = time.time()
  duration = time.time() - start

  print(f"Tijd: {duration:.2f}s")
  print(f"Beste params {name}: ", optres.best_params)
  print(f"Beste MAE {name}: ", optres.best_value)

[I 2025-05-14 15:13:38,022] A new study created in memory with name: no-name-c1627124-3e85-4816-a02a-9c79f04ed5ca

Optuna LightGBM

[I 2025-05-14 15:13:42,795] Trial 0 finished with value: 46462.8167704101 and parameters: {'n_estimators': 398, 'max_depth': 0, 'num_leaves': 203, 'learning_rate': 0.03244517265075398, 'subsample': 0.9933888676453719, 'colsample_bytree': 0.9549076598560055, 'reg_alpha': 0.20281431559477792, 'reg_lambda': 0.04197211344371865, 'min_child_samples': 8}. Best is trial 0 with value: 46462.8167704101.
[I 2025-05-14 15:13:45,672] Trial 1 finished with value: 46908.45233684311 and parameters: {'n_estimators': 609, 'max_depth': 8, 'num_leaves': 174, 'learning_rate': 0.04654607232809103, 'subsample': 0.7492974928497977, 'colsample_bytree': 0.6794608308583151, 'reg_alpha': 0.39758018305888365, 'reg_lambda': 0.2968434062789498, 'min_child_samples': 26}. Best is trial 0 with value: 46462.8167704101.
[I 2025-05-14 15:13:48,166] Trial 2 finished with value: 48015.29177987524 and parameters: {'n_estimators': 234, 'max_depth': 10, 'num_leaves': 319, 'learning_rate': 0.03184236484473436, 'subsample': 0.7988558826272731, 'colsample_bytree': 0.870073940949504, 'reg_alpha': 0.9957901833829335, 'reg_lambda': 0.20617785138103373, 'min_child_samples': 29}. Best is trial 0 with value: 46462.8167704101.
[I 2025-05-14 15:13:48,755] Trial 3 finished with value: 63358.244095693386 and parameters: {'n_estimators': 455, 'max_depth': 1, 'num_leaves': 350, 'learning_rate': 0.06410899517154461, 'subsample': 0.6897056562691508, 'colsample_bytree': 0.9935227768297719, 'reg_alpha': 0.48993496813586723, 'reg_lambda': 0.997344474795041, 'min_child_samples': 15}. Best is trial 0 with value: 46462.8167704101.
[I 2025-05-14 15:13:53,437] Trial 4 finished with value: 48995.3574855812 and parameters: {'n_estimators': 659, 'max_depth': 10, 'num_leaves': 194, 'learning_rate': 0.1937966236752538, 'subsample': 0.8840282595650086, 'colsample_bytree': 0.8015352616686331, 'reg_alpha': 0.2870489282167591, 'reg_lambda': 0.1962531771817111, 'min_child_samples': 20}. Best is trial 0 with value: 46462.8167704101.
[I 2025-05-14 15:13:55,243] Trial 5 finished with value: 47969.07180674096 and parameters: {'n_estimators': 210, 'max_depth': 10, 'num_leaves': 136, 'learning_rate': 0.03760144319511442, 'subsample': 0.6198512051966342, 'colsample_bytree': 0.9138446287951849, 'reg_alpha': 0.3568879484248758, 'reg_lambda': 0.5939584144937151, 'min_child_samples': 23}. Best is trial 0 with value: 46462.8167704101.
[I 2025-05-14 15:13:59,069] Trial 6 finished with value: 46458.73324637904 and parameters: {'n_estimators': 255, 'max_depth': -1, 'num_leaves': 251, 'learning_rate': 0.04407506465423059, 'subsample': 0.6006997700940891, 'colsample_bytree': 0.8486060316493546, 'reg_alpha': 0.3145869638515355, 'reg_lambda': 0.2957849624499447, 'min_child_samples': 13}. Best is trial 6 with value: 46458.73324637904.
[I 2025-05-14 15:13:59,781] Trial 7 finished with value: 62967.03105596609 and parameters: {'n_estimators': 716, 'max_depth': 1, 'num_leaves': 63, 'learning_rate': 0.051647703385910834, 'subsample': 0.6105227444079279, 'colsample_bytree': 0.6206176661702375, 'reg_alpha': 0.7614659068071313, 'reg_lambda': 0.4200587741086359, 'min_child_samples': 5}. Best is trial 6 with value: 46458.73324637904.
[I 2025-05-14 15:14:01,280] Trial 8 finished with value: 51946.11389435248 and parameters: {'n_estimators': 354, 'max_depth': -1, 'num_leaves': 27, 'learning_rate': 0.018545381390172783, 'subsample': 0.6016019053861726, 'colsample_bytree': 0.7699770620948934, 'reg_alpha': 0.5288419639422206, 'reg_lambda': 0.9947734967285132, 'min_child_samples': 13}. Best is trial 6 with value: 46458.73324637904.
[I 2025-05-14 15:14:06,043] Trial 9 finished with value: 46425.715126136594 and parameters: {'n_estimators': 509, 'max_depth': 14, 'num_leaves': 219, 'learning_rate': 0.043892237954813736, 'subsample': 0.8844549594417632, 'colsample_bytree': 0.7887292868987547, 'reg_alpha': 0.1115842311593338, 'reg_lambda': 0.1060776832965763, 'min_child_samples': 29}. Best is trial 9 with value: 46425.715126136594.
[I 2025-05-14 15:14:11,078] Trial 10 finished with value: 47822.14627951083 and parameters: {'n_estimators': 514, 'max_depth': 15, 'num_leaves': 274, 'learning_rate': 0.11952713034207914, 'subsample': 0.9128311823683748, 'colsample_bytree': 0.7188506040800177, 'reg_alpha': 0.03917158745912644, 'reg_lambda': 0.6279954105064722, 'min_child_samples': 30}. Best is trial 9 with value: 46425.715126136594.
[I 2025-05-14 15:14:19,841] Trial 11 finished with value: 46877.16064507903 and parameters: {'n_estimators': 536, 'max_depth': 15, 'num_leaves': 259, 'learning_rate': 0.013326988839576113, 'subsample': 0.8715214539339969, 'colsample_bytree': 0.8335223376027665, 'reg_alpha': 0.00891210819611915, 'reg_lambda': 0.024765586142727863, 'min_child_samples': 12}. Best is trial 9 with value: 46425.715126136594.
[I 2025-05-14 15:14:21,264] Trial 12 finished with value: 48647.55580633432 and parameters: {'n_estimators': 790, 'max_depth': 4, 'num_leaves': 252, 'learning_rate': 0.09488024653989556, 'subsample': 0.809139142515161, 'colsample_bytree': 0.7396248923852936, 'reg_alpha': 0.15910492349459532, 'reg_lambda': 0.3999663849054961, 'min_child_samples': 19}. Best is trial 9 with value: 46425.715126136594.
[I 2025-05-14 15:14:22,264] Trial 13 finished with value: 52736.30316435003 and parameters: {'n_estimators': 322, 'max_depth': 5, 'num_leaves': 228, 'learning_rate': 0.02007617906587829, 'subsample': 0.9681674406149602, 'colsample_bytree': 0.8553858787736246, 'reg_alpha': 0.6540699819194984, 'reg_lambda': 0.18703382195781504, 'min_child_samples': 23}. Best is trial 9 with value: 46425.715126136594.
[I 2025-05-14 15:14:24,979] Trial 14 finished with value: 46660.838364200674 and parameters: {'n_estimators': 444, 'max_depth': 13, 'num_leaves': 102, 'learning_rate': 0.08529450978675455, 'subsample': 0.6932887756664718, 'colsample_bytree': 0.8964869690232444, 'reg_alpha': 0.17830109488355916, 'reg_lambda': 0.7451966694015039, 'min_child_samples': 10}. Best is trial 9 with value: 46425.715126136594.
[I 2025-05-14 15:14:26,019] Trial 15 finished with value: 48597.448882959914 and parameters: {'n_estimators': 575, 'max_depth': 4, 'num_leaves': 288, 'learning_rate': 0.23984380714101755, 'subsample': 0.817503317436561, 'colsample_bytree': 0.778460007852486, 'reg_alpha': 0.13317061879338576, 'reg_lambda': 0.28880543415368987, 'min_child_samples': 16}. Best is trial 9 with value: 46425.715126136594.
[I 2025-05-14 15:14:29,350] Trial 16 finished with value: 47677.70177559247 and parameters: {'n_estimators': 295, 'max_depth': 12, 'num_leaves': 151, 'learning_rate': 0.023097275011127124, 'subsample': 0.9355948148290425, 'colsample_bytree': 0.8180246638459127, 'reg_alpha': 0.29781053775552596, 'reg_lambda': 0.10316515122055556, 'min_child_samples': 22}. Best is trial 9 with value: 46425.715126136594.
[I 2025-05-14 15:14:30,943] Trial 17 finished with value: 47396.0767391689 and parameters: {'n_estimators': 433, 'max_depth': 7, 'num_leaves': 223, 'learning_rate': 0.06678862657348275, 'subsample': 0.7434411495538773, 'colsample_bytree': 0.6718945925013965, 'reg_alpha': 0.4839038921202533, 'reg_lambda': 0.352850473168577, 'min_child_samples': 27}. Best is trial 9 with value: 46425.715126136594.
[I 2025-05-14 15:14:32,428] Trial 18 finished with value: 53801.365542883614 and parameters: {'n_estimators': 370, 'max_depth': 6, 'num_leaves': 299, 'learning_rate': 0.010014743495910602, 'subsample': 0.8401251605595681, 'colsample_bytree': 0.9260064899868884, 'reg_alpha': 0.6363767759435781, 'reg_lambda': 0.49843675731991055, 'min_child_samples': 17}. Best is trial 9 with value: 46425.715126136594.
[I 2025-05-14 15:14:32,947] Trial 19 finished with value: 51641.15871726157 and parameters: {'n_estimators': 293, 'max_depth': 3, 'num_leaves': 118, 'learning_rate': 0.14940444266803526, 'subsample': 0.6644028558007735, 'colsample_bytree': 0.7480563050051937, 'reg_alpha': 0.0851803777379643, 'reg_lambda': 0.15160250352434973, 'min_child_samples': 8}. Best is trial 9 with value: 46425.715126136594.
[I 2025-05-14 15:14:40,383] Trial 20 finished with value: 46521.36778120948 and parameters: {'n_estimators': 496, 'max_depth': 13, 'num_leaves': 237, 'learning_rate': 0.025283829233694582, 'subsample': 0.7583484169454612, 'colsample_bytree': 0.868408207393466, 'reg_alpha': 0.26075237668988993, 'reg_lambda': 0.2748121544444685, 'min_child_samples': 14}. Best is trial 9 with value: 46425.715126136594.
[I 2025-05-14 15:14:46,590] Trial 21 finished with value: 46872.09134515232 and parameters: {'n_estimators': 389, 'max_depth': -1, 'num_leaves': 190, 'learning_rate': 0.034618768199501465, 'subsample': 0.9997442116835195, 'colsample_bytree': 0.9815872007597141, 'reg_alpha': 0.1794282977203976, 'reg_lambda': 0.05136971024222808, 'min_child_samples': 6}. Best is trial 9 with value: 46425.715126136594.
[I 2025-05-14 15:14:47,099] Trial 22 finished with value: 65619.92853629614 and parameters: {'n_estimators': 241, 'max_depth': 1, 'num_leaves': 210, 'learning_rate': 0.043020454353331294, 'subsample': 0.94440089776232, 'colsample_bytree': 0.9553313329385832, 'reg_alpha': 0.23720149742057575, 'reg_lambda': 0.08920981209268869, 'min_child_samples': 9}. Best is trial 9 with value: 46425.715126136594.
[I 2025-05-14 15:14:47,942] Trial 23 finished with value: 59265.9004169432 and parameters: {'n_estimators': 387, 'max_depth': 2, 'num_leaves': 167, 'learning_rate': 0.0286107746732989, 'subsample': 0.9930389264838964, 'colsample_bytree': 0.9438006057017434, 'reg_alpha': 0.3706771624761131, 'reg_lambda': 0.04212149923689078, 'min_child_samples': 11}. Best is trial 9 with value: 46425.715126136594.
[I 2025-05-14 15:14:52,523] Trial 24 finished with value: 46637.81579531973 and parameters: {'n_estimators': 267, 'max_depth': -1, 'num_leaves': 210, 'learning_rate': 0.06443645034806783, 'subsample': 0.8897502502029585, 'colsample_bytree': 0.8904112466546894, 'reg_alpha': 0.0877092122202679, 'reg_lambda': 0.13153927548962677, 'min_child_samples': 8}. Best is trial 9 with value: 46425.715126136594.
[I 2025-05-14 15:15:03,524] Trial 25 finished with value: 46758.34497678091 and parameters: {'n_estimators': 481, 'max_depth': 0, 'num_leaves': 252, 'learning_rate': 0.014973590512026696, 'subsample': 0.8543981710247324, 'colsample_bytree': 0.844035374307689, 'reg_alpha': 0.22496813179781322, 'reg_lambda': 0.007286236652159703, 'min_child_samples': 6}. Best is trial 9 with value: 46425.715126136594.
[I 2025-05-14 15:15:09,753] Trial 26 finished with value: 46880.72756674732 and parameters: {'n_estimators': 577, 'max_depth': 9, 'num_leaves': 316, 'learning_rate': 0.08331339730433993, 'subsample': 0.9269013492866286, 'colsample_bytree': 0.7996679231815661, 'reg_alpha': 0.42787523569386143, 'reg_lambda': 0.2386535013733685, 'min_child_samples': 12}. Best is trial 9 with value: 46425.715126136594.
[I 2025-05-14 15:15:10,679] Trial 27 finished with value: 53836.277499352036 and parameters: {'n_estimators': 414, 'max_depth': 3, 'num_leaves': 200, 'learning_rate': 0.053122292311226935, 'subsample': 0.9563557051772364, 'colsample_bytree': 0.9587605635887311, 'reg_alpha': 0.3250659276577261, 'reg_lambda': 0.35100092632871893, 'min_child_samples': 19}. Best is trial 9 with value: 46425.715126136594.
[I 2025-05-14 15:15:12,243] Trial 28 finished with value: 49313.43499087631 and parameters: {'n_estimators': 341, 'max_depth': 6, 'num_leaves': 164, 'learning_rate': 0.04020443549853674, 'subsample': 0.779585941680971, 'colsample_bytree': 0.7039493943467343, 'reg_alpha': 0.11186812843300122, 'reg_lambda': 0.10554318789926287, 'min_child_samples': 26}. Best is trial 9 with value: 46425.715126136594.
[I 2025-05-14 15:15:20,858] Trial 29 finished with value: 46070.170180806665 and parameters: {'n_estimators': 633, 'max_depth': 0, 'num_leaves': 178, 'learning_rate': 0.046265690194042496, 'subsample': 0.9103855174963631, 'colsample_bytree': 0.7741090306636207, 'reg_alpha': 0.43116009681562023, 'reg_lambda': 0.45254869997199976, 'min_child_samples': 15}. Best is trial 29 with value: 46070.170180806665.
[I 2025-05-14 15:15:26,426] Trial 30 finished with value: 46416.746542571665 and parameters: {'n_estimators': 648, 'max_depth': 0, 'num_leaves': 138, 'learning_rate': 0.07014436071671623, 'subsample': 0.9077081643811635, 'colsample_bytree': 0.7731416123879505, 'reg_alpha': 0.6392223896187343, 'reg_lambda': 0.48873519291825995, 'min_child_samples': 15}. Best is trial 29 with value: 46070.170180806665.
[I 2025-05-14 15:15:30,506] Trial 31 finished with value: 46403.756355181955 and parameters: {'n_estimators': 666, 'max_depth': 0, 'num_leaves': 89, 'learning_rate': 0.06981353271890611, 'subsample': 0.8890071065932174, 'colsample_bytree': 0.776570855968728, 'reg_alpha': 0.5922362537767231, 'reg_lambda': 0.494985539345422, 'min_child_samples': 15}. Best is trial 29 with value: 46070.170180806665.
[I 2025-05-14 15:15:31,180] Trial 32 finished with value: 54736.087326445515 and parameters: {'n_estimators': 670, 'max_depth': 2, 'num_leaves': 98, 'learning_rate': 0.10425825124681684, 'subsample': 0.9026761212549085, 'colsample_bytree': 0.7685831129886579, 'reg_alpha': 0.7386497538446626, 'reg_lambda': 0.5199354658661324, 'min_child_samples': 17}. Best is trial 29 with value: 46070.170180806665.
[I 2025-05-14 15:15:34,477] Trial 33 finished with value: 46683.3574103093 and parameters: {'n_estimators': 652, 'max_depth': 0, 'num_leaves': 83, 'learning_rate': 0.07010193741710954, 'subsample': 0.8481989500255517, 'colsample_bytree': 0.7999430590348596, 'reg_alpha': 0.6055454287580992, 'reg_lambda': 0.7441773179299331, 'min_child_samples': 15}. Best is trial 29 with value: 46070.170180806665.
[I 2025-05-14 15:15:35,204] Trial 34 finished with value: 54023.153467335535 and parameters: {'n_estimators': 727, 'max_depth': 2, 'num_leaves': 138, 'learning_rate': 0.119353046427024, 'subsample': 0.9144142935858279, 'colsample_bytree': 0.7401851585038142, 'reg_alpha': 0.8726164412277028, 'reg_lambda': 0.48323331799290575, 'min_child_samples': 21}. Best is trial 29 with value: 46070.170180806665.
[I 2025-05-14 15:15:35,967] Trial 35 finished with value: 63173.929085432515 and parameters: {'n_estimators': 614, 'max_depth': 1, 'num_leaves': 123, 'learning_rate': 0.056866438710580794, 'subsample': 0.8698746833042917, 'colsample_bytree': 0.6901016107774735, 'reg_alpha': 0.7134877899108801, 'reg_lambda': 0.6674985432144729, 'min_child_samples': 18}. Best is trial 29 with value: 46070.170180806665.
[I 2025-05-14 15:15:38,706] Trial 36 finished with value: 47261.76516611201 and parameters: {'n_estimators': 707, 'max_depth': 8, 'num_leaves': 62, 'learning_rate': 0.029955727115092808, 'subsample': 0.9703773896419233, 'colsample_bytree': 0.6535512892844952, 'reg_alpha': 0.8001709507713881, 'reg_lambda': 0.587661671238485, 'min_child_samples': 15}. Best is trial 29 with value: 46070.170180806665.
[I 2025-05-14 15:15:43,744] Trial 37 finished with value: 46402.07825881493 and parameters: {'n_estimators': 619, 'max_depth': 0, 'num_leaves': 153, 'learning_rate': 0.07590135803754314, 'subsample': 0.8288541828307399, 'colsample_bytree': 0.8195423564605958, 'reg_alpha': 0.5549267118772979, 'reg_lambda': 0.8805298736764002, 'min_child_samples': 24}. Best is trial 29 with value: 46070.170180806665.
[I 2025-05-14 15:15:51,148] Trial 38 finished with value: 48066.29029330758 and parameters: {'n_estimators': 765, 'max_depth': 0, 'num_leaves': 180, 'learning_rate': 0.146521408455108, 'subsample': 0.8286973513481308, 'colsample_bytree': 0.8291279865193955, 'reg_alpha': 0.5645310690594996, 'reg_lambda': 0.8618497244517336, 'min_child_samples': 25}. Best is trial 29 with value: 46070.170180806665.
[I 2025-05-14 15:15:53,329] Trial 39 finished with value: 48039.0150704707 and parameters: {'n_estimators': 610, 'max_depth': 0, 'num_leaves': 29, 'learning_rate': 0.055734725449363975, 'subsample': 0.7894905404999684, 'colsample_bytree': 0.7518845511554739, 'reg_alpha': 0.46677023538504236, 'reg_lambda': 0.4471682526414302, 'min_child_samples': 16}. Best is trial 29 with value: 46070.170180806665.
[I 2025-05-14 15:15:54,495] Trial 40 finished with value: 51638.759582247214 and parameters: {'n_estimators': 642, 'max_depth': 3, 'num_leaves': 147, 'learning_rate': 0.0744468622752817, 'subsample': 0.8985689230837182, 'colsample_bytree': 0.8157022503499813, 'reg_alpha': 0.5504847007955437, 'reg_lambda': 0.5610178877108876, 'min_child_samples': 20}. Best is trial 29 with value: 46070.170180806665.
[I 2025-05-14 15:15:55,209] Trial 41 finished with value: 63129.626394420025 and parameters: {'n_estimators': 687, 'max_depth': 1, 'num_leaves': 162, 'learning_rate': 0.04829475063081317, 'subsample': 0.870055427084792, 'colsample_bytree': 0.7785488026460956, 'reg_alpha': 0.674039225485795, 'reg_lambda': 0.6995284268418624, 'min_child_samples': 28}. Best is trial 29 with value: 46070.170180806665.
[I 2025-05-14 15:15:58,484] Trial 42 finished with value: 46892.73595073054 and parameters: {'n_estimators': 555, 'max_depth': 11, 'num_leaves': 112, 'learning_rate': 0.03596601475154244, 'subsample': 0.8826229040661399, 'colsample_bytree': 0.7187832039947016, 'reg_alpha': 0.5876107717596101, 'reg_lambda': 0.9269645316343988, 'min_child_samples': 30}. Best is trial 29 with value: 46070.170180806665.
[I 2025-05-14 15:16:01,028] Trial 43 finished with value: 46948.696323424374 and parameters: {'n_estimators': 624, 'max_depth': -1, 'num_leaves': 62, 'learning_rate': 0.08214032467025124, 'subsample': 0.9241229284324901, 'colsample_bytree': 0.7990449228476856, 'reg_alpha': 0.41666313658088217, 'reg_lambda': 0.3855366061645417, 'min_child_samples': 28}. Best is trial 29 with value: 46070.170180806665.
[I 2025-05-14 15:16:01,745] Trial 44 finished with value: 55072.85700104598 and parameters: {'n_estimators': 582, 'max_depth': 2, 'num_leaves': 84, 'learning_rate': 0.10108063227630214, 'subsample': 0.8569282176569107, 'colsample_bytree': 0.7812854998013656, 'reg_alpha': 0.8065861299582872, 'reg_lambda': 0.5414904156445585, 'min_child_samples': 24}. Best is trial 29 with value: 46070.170180806665.
[I 2025-05-14 15:16:07,991] Trial 45 finished with value: 46236.97375895986 and parameters: {'n_estimators': 682, 'max_depth': 0, 'num_leaves': 134, 'learning_rate': 0.04539889115461887, 'subsample': 0.9019160247942235, 'colsample_bytree': 0.7643052630979813, 'reg_alpha': 0.522059120233269, 'reg_lambda': 0.8483876461059523, 'min_child_samples': 13}. Best is trial 29 with value: 46070.170180806665.
[I 2025-05-14 15:16:15,575] Trial 46 finished with value: 46256.12674605236 and parameters: {'n_estimators': 743, 'max_depth': 0, 'num_leaves': 137, 'learning_rate': 0.06280523059326786, 'subsample': 0.945957872465555, 'colsample_bytree': 0.7606542761082862, 'reg_alpha': 0.5276403681599383, 'reg_lambda': 0.863467128518902, 'min_child_samples': 13}. Best is trial 29 with value: 46070.170180806665.
[I 2025-05-14 15:16:21,513] Trial 47 finished with value: 46343.717963758216 and parameters: {'n_estimators': 745, 'max_depth': -1, 'num_leaves': 129, 'learning_rate': 0.059240881716448146, 'subsample': 0.9497100914793978, 'colsample_bytree': 0.7225521365025758, 'reg_alpha': 0.5211497836225314, 'reg_lambda': 0.8531008365936595, 'min_child_samples': 13}. Best is trial 29 with value: 46070.170180806665.
[I 2025-05-14 15:16:28,924] Trial 48 finished with value: 46267.91099962551 and parameters: {'n_estimators': 742, 'max_depth': -1, 'num_leaves': 178, 'learning_rate': 0.05689890886894814, 'subsample': 0.9832748566580286, 'colsample_bytree': 0.726828817478353, 'reg_alpha': 0.5134488335417654, 'reg_lambda': 0.844107870088892, 'min_child_samples': 13}. Best is trial 29 with value: 46070.170180806665.

Tijd: 0.00s
Beste params LightGBM:  {'n_estimators': 783, 'max_depth': 14, 'num_leaves': 332, 'learning_rate': 0.031065357902710616, 'subsample': 0.6982593215455819, 'colsample_bytree': 0.717273545134999, 'reg_alpha': 0.7803700200347652, 'reg_lambda': 0.6629991966878577, 'min_child_samples': 9}
Beste MAE LightGBM:  45693.15149266192

extratrees word verder genegeerd door de zeer lange trainingtijden en slechte finetuning resultaten, hierdoor heb ik dit vervamgen met LGBM doordat dit gelijkaardig zou moetten testen als XGB op mijn model

Optuna XGBoost

Beste params XGBoost:  {'n_estimators': 800, 'max_depth': 11, 'learning_rate': 0.024791795598051402, 'subsample': 0.9152182561342729, 'colsample_bytree': 0.628872599960794, 'reg_alpha': 0.4587526558642877, 'reg_lambda': 0.9054148915932084, 'min_child_weight': 9, 'gamma': 0.03130859570095774}
[I 2025-04-16 18:45:13,612] A new study created in memory with name: no-name-047d6f2c-8d88-466b-bb37-959ef292a0b9
Beste MAE XGBoost:  45756.13671875

Optuna HistGradient

Beste params HistGradient:  {'learning_rate': 0.09360779076213302, 'max_iter': 403, 'max_depth': 12, 'max_leaf_nodes': 83}
Beste MAE HistGradient:  47610.78728722957

Optuna ExtraTrees

Beste params ExtraTrees:  {'n_estimators': 351, 'max_depth': 27, 'min_samples_split': 8, 'min_samples_leaf': 1}
Beste MAE ExtraTrees:  48229.70593565771

Optuna LightGBM

Beste params LightGBM:  {'n_estimators': 791, 'max_depth': 14, 'num_leaves': 334, 'learning_rate': 0.029456000685140836, 'subsample': 0.8303507682774592, 'colsample_bytree': 0.6505159652741844, 'reg_alpha': 0.20430689348688258, 'reg_lambda': 0.3218993752340186, 'min_child_samples': 13}
Beste MAE LightGBM:  45536.17331152257

In [77]:
print(optres.best_trial.user_attrs)

{'model': LGBMRegressor(colsample_bytree=0.717273545134999,
              learning_rate=0.031065357902710616, max_depth=14,
              min_child_samples=9, n_estimators=783, n_jobs=-1, num_leaves=332,
              random_state=42, reg_alpha=0.7803700200347652,
              reg_lambda=0.6629991966878577, subsample=0.6982593215455819,
              verbosity=-1)}

In [76]:
best_params = optres.best_params
tuned_model = optres.best_trial.user_attrs['model']

y_pred = tuned_model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
mape = mean_absolute_percentage_error(y_test, y_pred)
accuracy = 1 - mape

print(f'Mean absolute error: {mae}')
print(f'Mean absolute percentage error: {mape}')
print(f'Accuracy: {accuracy}')

Mean absolute error: 45693.15149266192
Mean absolute percentage error: 0.13544911193090078
Accuracy: 0.8645508880690992

## Best so far
### LightGBM
Mean absolute error: 45337.28982557999
Mean absolute percentage error: 0.1334235812403486
Accuracy: 0.8665764187596514

GridsearchCV

In [ ]:

#parameters
model_param = {
    'XGBoost': {
        'model': XGBRegressor(),
        'params': {
            'n_estimators': [850],
            'learning_rate': [0.025, 0.03],
            'max_depth': [8, 9],
            'min_child_weight': [1,2],
            'subsample': [1.0],
            'colsample_bytree': [0.8],
            'gamma': [0.035, 0.04],
            'reg_lambda': [3],
            'reg_alpha': range(0, 5, 1)
        }
    },
    'HistGradient': {
        'model': HistGradientBoostingRegressor(),
        'params': {
            'n_estimators': [850],
            'learning_rate': [0.01, 0.1],
            'max_iter': [100, 200],
            'max_depth': [3, 5],
            'l2_regularization': [0.1, 1],
            'min_samples_leaf': [1, 2],
            'max_leaf_nodes': [20, 40]
        }
    },
    'LightGBM': {
        'model': LGBMRegressor(),
        'params': {
            'n_estimators': [850],
            'num_leaves': [31, 50],
            'learning_rate': [0.01, 0.1],
            'n_estimators': [100, 200],
            'max_depth': [-1, 5],
            'min_child_samples': [10, 20],
            'subsample': [0.6, 0.8],
            'colsample_bytree': [0.6, 0.8],
            'reg_alpha': [0, 0.1],
            'reg_lambda': [0, 0.1]
        }
    }
}

hist = HistGradientBoostingRegressor()
xgb = XGBRegressor()
lgbm = LGBMRegressor()

In [ ]:
for name, config in model_param.items():
    print(f"Model: {name}")
    model = config['model']
    param = config['params']
    
    gs = GridSearchCV(
        estimator=model,
        param_grid=param,
        cv=5,
        scoring='neg_mean_absolute_error',
        n_jobs=-1,
        verbose=2
    )
    
    start = time.time()
    gs.fit(X_train, y_train)
    duration = time.time() - start

    print(f"Tijd {name}: {duration:.2f}s")
    print(f"Beste param {name}: {gs.best_params_}")
    print(f"Beste MAE: {gs.best_score_:.4f}")

Model: XGBoost
Fitting 5 folds for each of 80 candidates, totalling 400 fits

KeyboardInterrupt:

Resultaten tuned model

In [75]:
best_params = gs.best_params_
tuned_model = gs.best_estimator_

y_pred = tuned_model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
mape = mean_absolute_percentage_error(y_test, y_pred)
accuracy = 1 - mape

print(f'Mean absolute error: {mae}')
print(f'Mean absolute percentage error: {mape}')
print(f'Accuracy: {accuracy}')

NameError: name 'gs' is not defined

### model opslaan met beste parameters

In [73]:
besteModel = LGBMRegressor(
    n_estimators=788,
    max_depth=0,
    num_leaves=213,
    learning_rate=0.027352468420388434,
    subsample=0.8257111258276627,
    colsample_bytree=0.7709277343834496,
    reg_alpha=0.7512362258288539,
    reg_lambda=0.23466677100487698,
    min_child_samples=8,
    random_state=42,
    n_jobs=-1,
    verbosity=-1
)

besteModel.fit(X_train, y_train)
pred = besteModel.predict(X_test)
mae = mean_absolute_error(y_test, pred)
print(f"MAE: {mae:.4f}")

MAE: 46021.7181

In [78]:
#opslaan bij models
lgbmModelDir = os.getcwd()
lgbmModelPath = os.path.join(lgbmModelDir, ".",
                          "models", "lightGBM.pkl")
os.makedirs(os.path.dirname(lgbmModelPath), exist_ok=True)
with open(lgbmModelPath, 'wb') as m:
    pickle.dump(besteModel, m)