In [2]:
from datetime import datetime, timedelta, date
import requests
import pandas as pd
import pickle
import numpy as np
import holidays

csv_te_voorspellen = './data csv/Input_voor_examen (1).csv'

In [3]:
def ophalenKijkcijferData(startDate, endDate):
  print(f"Ophalen kijkcijfer-data van {startDate.year}-{startDate.month}-{startDate.day} tot {endDate.year}-{endDate.month}-{endDate.day}")
  kijkcijfersData = []
  #elke dag ophalen (startDate is huidige dag)
  while startDate <= endDate:
    datum = f"{startDate.year}-{startDate.month}-{startDate.day}"
    url = f"https://api.cim.be/api/cim_tv_public_results_daily_views?dateDiff={datum}&reportType=north"

    try:
      response = requests.get(url)
      if response.status_code == 200:
        data = response.json()
        programmaLijst = data.get('hydra:member', [])
                        
        for programma in programmaLijst:
          try:
            kijkcijfersData.append({
              'dateDiff': programma.get('dateDiff'),
              'ranking': programma.get('ranking'),
              'description': programma.get('description'),
              'channel': programma.get('channel'),
              'startTime': programma.get('startTime'),
              'rLength': programma.get('rLength'),
              'rateInK': programma.get('rateInK'),
              'live': programma.get('live')
            })
                                   
          except Exception as e:
            print(f"error {datum}: {e}")         
      else:
        print(f"no data {datum}")
                        
    except Exception as e:
      print(f"error: {e}")
    
    startDate += timedelta(days=1)

  print("KijkcijferData opgehaald")
  df = pd.DataFrame(kijkcijfersData)

  return df

def ophalenWeerData(startDate, endDate):
    latitude = 51.05
    longitude = 3.7167
    today = datetime.today().date()

    hourly_vars = [
        "temperature_2m", "apparent_temperature", "weather_code", "precipitation",
        "rain", "snowfall", "cloud_cover", "windspeed_10m", "sunshine_duration"
    ]
    
    common_params = {
        "latitude": latitude,
        "longitude": longitude,
        "hourly": hourly_vars,
        "timezone": "Europe/Brussels",
        "temperature_unit": "celsius",
        "precipitation_unit": "mm",
        "windspeed_unit": "kmh"
    }

    def fetch_weather_data(api_url, start, end):
        params = common_params.copy()
        params.update({
            "start_date": start.strftime('%Y-%m-%d'),
            "end_date": end.strftime('%Y-%m-%d')
        })
        response = requests.get(api_url, params=params)
        if response.status_code == 200:
            data = response.json().get("hourly", {})
            df = pd.DataFrame({var: data.get(var, []) for var in hourly_vars})
            df["timestamp"] = pd.to_datetime(data.get("time", []))
            if not df.empty:
                df["hour"] = df["timestamp"].dt.hour
                df["day_of_week"] = df["timestamp"].dt.dayofweek
                df["month"] = df["timestamp"].dt.month
                df["year"] = df["timestamp"].dt.year
            return df
        else:
            print(f"Fout bij ophalen data: {response.status_code}")
            print(response.text)
            return pd.DataFrame()

    dataframes = []

    # Historische data
    if startDate.date() < today:
        print("Ophalen historische data")
        hist_end = min(endDate.date(), today - timedelta(days=1))
        dataframes.append(fetch_weather_data(
            "https://archive-api.open-meteo.com/v1/archive",
            startDate, datetime.combine(hist_end, datetime.min.time())
        ))

    # Forecast data
    if endDate.date() >= today:
        print("Ophalen forecast data")
        forecast_start = max(endDate, datetime.combine(today, datetime.min.time()))
        print(forecast_start)
        dataframes.append(fetch_weather_data(
            "https://api.open-meteo.com/v1/forecast",
            forecast_start, endDate
        ))

    if dataframes:
        print("Weerdata opgehaald")
        return pd.concat(dataframes).sort_values("timestamp").reset_index(drop=True)
    else:
        return pd.DataFrame()

In [4]:
def testCSV(csv):
    df = pd.read_csv(csv, delimiter=';')
    # Kolommen hernoemen
    df = df.rename(columns={
        'Programma': 'description',
        'Zender': 'channel',
        'Datum': 'dateDiff',
        'Start': 'startTime',
        'Duur': 'rLength'
    })
    # Datum en tijd samenvoegen tot datetime
    df['dateDiff'] = pd.to_datetime(df['dateDiff'], dayfirst=True)
    # Starttijd naar HH:MM:SS
    df['startTime'] = df['startTime'].str[:8]
    # Duur naar HH:MM:SS
    df['rLength'] = df['rLength'].apply(lambda x: str(pd.to_timedelta(x)))
    # Voeg dummy kolommen toe als nodig
    df['ranking'] = 0
    df['live'] = 0
    df['Kijkers'] = None

    return df[['dateDiff', 'ranking', 'description', 'channel', 'startTime', 'rLength', 'live']]

In [5]:
teVoorspellen = testCSV(csv_te_voorspellen)

teVoorspellen['dateDiff'] = pd.to_datetime(teVoorspellen['dateDiff'])

end_date = teVoorspellen['dateDiff'].max()
start_date = end_date - timedelta(weeks=3)
histKijkcijfers = ophalenKijkcijferData(start_date, end_date - timedelta(days=1))
histWeerdata = ophalenWeerData(start_date, end_date)

Ophalen kijkcijfer-data van 2025-5-16 tot 2025-6-5
KijkcijferData opgehaald
Ophalen historische data
Ophalen forecast data
2025-06-06 00:00:00
Weerdata opgehaald

In [6]:
def cleanKijkcijferData(df):

    # Zet 'Kijkers' kolom, als 'rateInK' bestaat
    if 'rateInK' in df.columns:
        df['Kijkers'] = (
            df['rateInK']
            .dropna()
            .astype(str)
            .str.replace('.', '', regex=False)
            .astype(int)
        )
    else:
        df['Kijkers'] = None

    # rLength aanpassen
    df['rLength'] = df['rLength'].astype(str).apply(
    lambda x: x[-8:] if 'days' in x else x.zfill(8)
    )

    # Tijd aanpassen
    tijd_regex = r'^\d{2}:\d{2}:\d{2}$'
    # Omzetten naar datetime
    df['date'] = pd.to_datetime(df['dateDiff']).dt.date
    # Filter rijen met formaat
    df = df[df['startTime'].str.match(tijd_regex, na=False) & df['rLength'].str.match(tijd_regex, na=False)].copy()
    
    # Afleveringlengte naar seconden omzetten 
    df['Lengte_sec'] = pd.to_timedelta(df['rLength']).dt.total_seconds().astype(int)

    # Uren met 24+
    def time_cor(rij):
        tijdArr = rij['startTime'].split(':')
        if int(tijdArr[0]) >= 24:
            tijdArr[0] = str(int(tijdArr[0]) - 24).zfill(2)
            rij['date'] += timedelta(days=1)
        rij['startTime'] = ':'.join(tijdArr)
        return rij
    
    df = df.apply(time_cor, axis=1)

    # 1 kolom voor beide data
    df['FullDate'] = pd.to_datetime(df['date'].astype(str) 
                                    + " " + df['startTime'].astype(str))
    
    # Hour en minute voor join later on
    df['hour'] = pd.to_datetime(df['startTime'], format='%H:%M:%S').dt.hour
    df['minute'] = 0

    # Kolommen verwijderen die niet nodig meer zijn, als ze bestaan
    columns_to_drop = ['startTime', 'rLength', 'rateInK', 'ranking', 'live']
    df.drop([col for col in columns_to_drop if col in df.columns], axis=1, inplace=True)


    # De nieuwe dataframe
    df = df[['FullDate', 'date', 'hour', 'minute', 'channel', 'description', 'Lengte_sec', 'Kijkers']]

    # Hernoemen kolommen
    df.rename(columns={'description': 'Programma', 'channel': 'Kanaal'}, inplace=True)

    return df


def cleanWeerData(df):
  weerData = df
  weerData['timestamp'] = pd.to_datetime(weerData['timestamp'])
  #naar zelfde formaat als kijkcijfer datum
  weerData['datetime'] = weerData['timestamp'].dt.strftime('%Y-%m-%d %H:%M:%S')

  #hour voor join later on
  weerData['hour'] = pd.to_datetime(weerData['datetime']).dt.hour
  weerData['minute'] = pd.to_datetime(weerData['datetime']).dt.minute
  weerData['date'] = pd.to_datetime(weerData['datetime']).dt.date

  #verwijder kolom
  weerData = weerData.drop(columns=['timestamp'])

  weerData = weerData[['datetime', 'date' ,'hour', 'minute', 'temperature_2m', 'apparent_temperature', 
                            'rain', 'snowfall', 'weather_code', 'cloud_cover', 
                            'windspeed_10m', 'sunshine_duration']]

  #hernoemen kolommen
  weerData.rename(columns={'temperature_2m':'Temperatuur', 'apparent_temperature':'Gevoelstemp', 'windspeed_10m': 'Windsnelheid', 'rain':'Regen', 'snowfall': 'Sneeuw', 'weather_code':'Weercode', 'cloud_cover':'Bewolking', 'sunshine_duration':'Zonnenschijn'}, inplace=True)

  return weerData

In [19]:
histWeerdataClean = cleanWeerData(histWeerdata)
histKijkcijfersClean = cleanKijkcijferData(histKijkcijfers)
teVoorspellenClean = cleanKijkcijferData(teVoorspellen)
display(histWeerdataClean)
display(histKijkcijfersClean)
display(teVoorspellenClean)

,datetime,date,hour,minute,Temperatuur,Gevoelstemp,Regen,Sneeuw,Weercode,Bewolking,Windsnelheid,Zonnenschijn
0,2025-05-16 00:00:00,2025-05-16,0,0,11.6,8.6,0.0,0.0,0.0,0.0,12.7,0.00
1,2025-05-16 01:00:00,2025-05-16,1,0,11.1,8.0,0.0,0.0,0.0,0.0,12.1,0.00
2,2025-05-16 02:00:00,2025-05-16,2,0,10.3,7.2,0.0,0.0,0.0,0.0,11.5,0.00
3,2025-05-16 03:00:00,2025-05-16,3,0,9.1,6.2,0.0,0.0,0.0,0.0,10.5,0.00
4,2025-05-16 04:00:00,2025-05-16,4,0,8.4,5.7,0.0,0.0,0.0,0.0,10.0,0.00
5,2025-05-16 05:00:00,2025-05-16,5,0,7.7,5.3,0.0,0.0,0.0,0.0,8.7,0.00
6,2025-05-16 06:00:00,2025-05-16,6,0,7.1,4.8,0.0,0.0,0.0,0.0,8.6,0.00
7,2025-05-16 07:00:00,2025-05-16,7,0,7.6,5.2,0.0,0.0,0.0,0.0,9.0,1690.92
8,2025-05-16 08:00:00,2025-05-16,8,0,9.4,7.3,0.0,0.0,0.0,0.0,7.4,3600.00
9,2025-05-16 09:00:00,2025-05-16,9,0,11.7,9.3,0.0,0.0,0.0,0.0,8.7,3600.00
10,2025-05-16 10:00:00,2025-05-16,10,0,13.8,11.1,0.0,0.0,0.0,0.0,9.4,3600.00
11,2025-05-16 11:00:00,2025-05-16,11,0,15.3,12.4,0.0,0.0,0.0,0.0,11.5,3600.00
12,2025-05-16 12:00:00,2025-05-16,12,0,16.0,13.3,0.0,0.0,0.0,2.0,14.1,3600.00
13,2025-05-16 13:00:00,2025-05-16,13,0,16.2,14.3,0.0,0.0,1.0,22.0,14.2,3600.00
14,2025-05-16 14:00:00,2025-05-16,14,0,16.7,14.4,0.0,0.0,2.0,64.0,15.1,3600.00
15,2025-05-16 15:00:00,2025-05-16,15,0,16.5,13.6,0.0,0.0,2.0,68.0,16.8,3600.00
16,2025-05-16 16:00:00,2025-05-16,16,0,16.2,13.1,0.0,0.0,1.0,40.0,17.6,3600.00
17,2025-05-16 17:00:00,2025-05-16,17,0,15.0,11.3,0.0,0.0,2.0,77.0,18.9,3600.00
18,2025-05-16 18:00:00,2025-05-16,18,0,13.7,10.0,0.0,0.0,3.0,99.0,18.8,3600.00
19,2025-05-16 19:00:00,2025-05-16,19,0,12.6,9.0,0.0,0.0,3.0,100.0,18.8,1895.07
20,2025-05-16 20:00:00,2025-05-16,20,0,12.3,8.6,0.0,0.0,3.0,100.0,18.4,0.00
21,2025-05-16 21:00:00,2025-05-16,21,0,11.8,8.2,0.0,0.0,3.0,100.0,17.9,0.00
22,2025-05-16 22:00:00,2025-05-16,22,0,11.7,8.2,0.0,0.0,3.0,100.0,17.8,0.00
23,2025-05-16 23:00:00,2025-05-16,23,0,11.8,8.9,0.0,0.0,3.0,100.0,14.8,0.00
24,2025-05-17 00:00:00,2025-05-17,0,0,11.2,9.1,0.0,0.0,3.0,100.0,10.0,0.00
25,2025-05-17 01:00:00,2025-05-17,1,0,10.6,8.8,0.0,0.0,3.0,96.0,8.6,0.00
26,2025-05-17 02:00:00,2025-05-17,2,0,10.5,8.8,0.0,0.0,1.0,40.0,8.9,0.00
27,2025-05-17 03:00:00,2025-05-17,3,0,11.2,9.3,0.0,0.0,3.0,100.0,8.8,0.00
28,2025-05-17 04:00:00,2025-05-17,4,0,11.1,9.3,0.0,0.0,3.0,100.0,7.8,0.00
29,2025-05-17 05:00:00,2025-05-17,5,0,11.1,9.1,0.0,0.0,3.0,99.0,9.4,0.00
30,2025-05-17 06:00:00,2025-05-17,6,0,11.1,9.3,0.0,0.0,3.0,94.0,9.4,0.00
31,2025-05-17 07:00:00,2025-05-17,7,0,11.1,9.3,0.0,0.0,3.0,81.0,9.5,0.00
32,2025-05-17 08:00:00,2025-05-17,8,0,12.1,9.8,0.0,0.0,2.0,53.0,13.1,3600.00
33,2025-05-17 09:00:00,2025-05-17,9,0,13.6,10.8,0.0,0.0,2.0,79.0,14.7,3600.00
34,2025-05-17 10:00:00,2025-05-17,10,0,15.3,12.6,0.0,0.0,0.0,16.0,12.6,3600.00
35,2025-05-17 11:00:00,2025-05-17,11,0,16.8,14.4,0.0,0.0,1.0,23.0,11.3,3600.00
36,2025-05-17 12:00:00,2025-05-17,12,0,18.3,15.9,0.0,0.0,2.0,53.0,12.9,3600.00
37,2025-05-17 13:00:00,2025-05-17,13,0,18.9,16.0,0.0,0.0,3.0,100.0,14.5,3600.00
38,2025-05-17 14:00:00,2025-05-17,14,0,18.0,14.3,0.0,0.0,2.0,68.0,16.2,2263.42
39,2025-05-17 15:00:00,2025-05-17,15,0,18.5,15.4,0.0,0.0,1.0,28.0,15.5,3600.00
40,2025-05-17 16:00:00,2025-05-17,16,0,17.9,14.6,0.0,0.0,1.0,24.0,17.5,3600.00
41,2025-05-17 17:00:00,2025-05-17,17,0,16.8,13.9,0.0,0.0,0.0,11.0,18.0,3600.00
42,2025-05-17 18:00:00,2025-05-17,18,0,15.7,12.3,0.0,0.0,0.0,1.0,16.8,3600.00
43,2025-05-17 19:00:00,2025-05-17,19,0,14.7,11.5,0.0,0.0,0.0,5.0,15.2,3600.00
44,2025-05-17 20:00:00,2025-05-17,20,0,13.5,10.7,0.0,0.0,0.0,3.0,13.5,3600.00
45,2025-05-17 21:00:00,2025-05-17,21,0,12.3,9.8,0.0,0.0,0.0,7.0,12.0,3318.27
46,2025-05-17 22:00:00,2025-05-17,22,0,11.0,8.7,0.0,0.0,0.0,15.0,11.9,0.00
47,2025-05-17 23:00:00,2025-05-17,23,0,10.5,8.5,0.0,0.0,1.0,43.0,10.1,0.00
48,2025-05-18 00:00:00,2025-05-18,0,0,10.6,8.6,0.0,0.0,3.0,100.0,10.3,0.00
49,2025-05-18 01:00:00,2025-05-18,1,0,11.2,8.5,0.0,0.0,3.0,100.0,15.7,0.00
50,2025-05-18 02:00:00,2025-05-18,2,0,11.4,8.9,0.0,0.0,3.0,100.0,14.1,0.00
51,2025-05-18 03:00:00,2025-05-18,3,0,10.8,8.3,0.0,0.0,3.0,100.0,13.3,0.00
52,2025-05-18 04:00:00,2025-05-18,4,0,10.5,8.1,0.0,0.0,3.0,100.0,12.7,0.00
53,2025-05-18 05:00:00,2025-05-18,5,0,10.5,8.0,0.0,0.0,3.0,100.0,12.6,0.00
54,2025-05-18 06:00:00,2025-05-18,6,0,10.3,7.8,0.0,0.0,3.0,100.0,12.2,0.00
55,2025-05-18 07:00:00,2025-05-18,7,0,10.1,7.4,0.0,0.0,3.0,100.0,12.4,0.00
56,2025-05-18 08:00:00,2025-05-18,8,0,10.2,7.6,0.0,0.0,3.0,100.0,11.3,0.00
57,2025-05-18 09:00:00,2025-05-18,9,0,10.7,7.9,0.0,0.0,3.0,100.0,11.8,0.00
58,2025-05-18 10:00:00,2025-05-18,10,0,12.0,9.5,0.0,0.0,3.0,100.0,9.6,350.53
59,2025-05-18 11:00:00,2025-05-18,11,0,13.3,11.3,0.0,0.0,3.0,100.0,7.6,1396.27
60,2025-05-18 12:00:00,2025-05-18,12,0,14.3,12.4,0.1,0.0,51.0,100.0,7.2,0.00
61,2025-05-18 13:00:00,2025-05-18,13,0,15.4,13.2,0.1,0.0,51.0,100.0,8.8,896.98
62,2025-05-18 14:00:00,2025-05-18,14,0,16.5,14.2,0.0,0.0,3.0,92.0,8.4,1337.26
63,2025-05-18 15:00:00,2025-05-18,15,0,15.1,13.0,0.0,0.0,3.0,100.0,6.9,953.85
64,2025-05-18 16:00:00,2025-05-18,16,0,15.8,13.7,0.0,0.0,3.0,99.0,6.2,562.57
65,2025-05-18 17:00:00,2025-05-18,17,0,16.3,14.1,0.0,0.0,3.0,91.0,6.5,428.72
66,2025-05-18 18:00:00,2025-05-18,18,0,15.9,13.4,0.0,0.0,3.0,98.0,9.4,0.00
67,2025-05-18 19:00:00,2025-05-18,19,0,15.3,12.8,0.0,0.0,3.0,100.0,11.8,1376.89
68,2025-05-18 20:00:00,2025-05-18,20,0,14.3,12.0,0.0,0.0,3.0,100.0,11.8,3600.00
69,2025-05-18 21:00:00,2025-05-18,21,0,13.9,11.8,0.0,0.0,0.0,14.0,10.1,1459.69
70,2025-05-18 22:00:00,2025-05-18,22,0,13.4,11.4,0.0,0.0,0.0,3.0,10.4,0.00
71,2025-05-18 23:00:00,2025-05-18,23,0,12.0,10.3,0.0,0.0,0.0,18.0,9.4,0.00
72,2025-05-19 00:00:00,2025-05-19,0,0,11.1,9.5,0.0,0.0,0.0,12.0,9.0,0.00
73,2025-05-19 01:00:00,2025-05-19,1,0,10.6,9.2,0.0,0.0,0.0,2.0,8.1,0.00
74,2025-05-19 02:00:00,2025-05-19,2,0,10.2,9.1,0.0,0.0,0.0,1.0,6.5,0.00
75,2025-05-19 03:00:00,2025-05-19,3,0,9.3,7.9,0.0,0.0,0.0,1.0,7.6,0.00
76,2025-05-19 04:00:00,2025-05-19,4,0,9.2,7.7,0.0,0.0,0.0,1.0,7.8,0.00
77,2025-05-19 05:00:00,2025-05-19,5,0,9.0,7.5,0.0,0.0,0.0,3.0,8.0,0.00
78,2025-05-19 06:00:00,2025-05-19,6,0,8.8,7.1,0.0,0.0,0.0,1.0,8.3,0.00
79,2025-05-19 07:00:00,2025-05-19,7,0,9.2,7.4,0.0,0.0,0.0,2.0,8.4,1936.92
80,2025-05-19 08:00:00,2025-05-19,8,0,10.7,9.2,0.0,0.0,0.0,2.0,7.4,3600.00
81,2025-05-19 09:00:00,2025-05-19,9,0,12.7,11.0,0.0,0.0,0.0,4.0,7.7,3600.00
82,2025-05-19 10:00:00,2025-05-19,10,0,14.8,13.0,0.0,0.0,0.0,6.0,7.8,3600.00
83,2025-05-19 11:00:00,2025-05-19,11,0,17.1,15.7,0.0,0.0,0.0,0.0,8.4,3600.00
84,2025-05-19 12:00:00,2025-05-19,12,0,19.0,17.8,0.0,0.0,0.0,0.0,10.4,3600.00
85,2025-05-19 13:00:00,2025-05-19,13,0,20.5,19.1,0.0,0.0,2.0,74.0,12.7,3600.00
86,2025-05-19 14:00:00,2025-05-19,14,0,20.8,17.8,0.0,0.0,3.0,86.0,11.5,3600.00
87,2025-05-19 15:00:00,2025-05-19,15,0,21.1,18.2,0.0,0.0,2.0,78.0,11.3,3600.00
88,2025-05-19 16:00:00,2025-05-19,16,0,21.8,18.9,0.0,0.0,2.0,57.0,10.5,3600.00
89,2025-05-19 17:00:00,2025-05-19,17,0,22.4,19.3,0.0,0.0,2.0,51.0,10.0,3600.00
90,2025-05-19 18:00:00,2025-05-19,18,0,22.8,19.9,0.0,0.0,3.0,80.0,7.8,3600.00
91,2025-05-19 19:00:00,2025-05-19,19,0,21.2,18.5,0.0,0.0,3.0,99.0,10.6,3600.00
92,2025-05-19 20:00:00,2025-05-19,20,0,19.4,16.5,0.0,0.0,2.0,72.0,15.1,3600.00
93,2025-05-19 21:00:00,2025-05-19,21,0,18.2,15.4,0.0,0.0,2.0,54.0,14.5,3472.99
94,2025-05-19 22:00:00,2025-05-19,22,0,16.5,13.6,0.0,0.0,0.0,1.0,15.3,0.00
95,2025-05-19 23:00:00,2025-05-19,23,0,15.6,13.1,0.0,0.0,0.0,10.0,14.0,0.00
96,2025-05-20 00:00:00,2025-05-20,0,0,15.2,13.0,0.0,0.0,3.0,91.0,12.6,0.00
97,2025-05-20 01:00:00,2025-05-20,1,0,14.4,12.4,0.0,0.0,3.0,84.0,11.9,0.00
98,2025-05-20 02:00:00,2025-05-20,2,0,13.7,11.8,0.0,0.0,0.0,7.0,10.9,0.00
99,2025-05-20 03:00:00,2025-05-20,3,0,12.6,10.7,0.0,0.0,0.0,8.0,10.9,0.00
100,2025-05-20 04:00:00,2025-05-20,4,0,12.0,10.0,0.0,0.0,0.0,1.0,10.6,0.00
101,2025-05-20 05:00:00,2025-05-20,5,0,11.4,9.5,0.0,0.0,0.0,0.0,9.8,0.00
102,2025-05-20 06:00:00,2025-05-20,6,0,10.9,9.0,0.0,0.0,0.0,1.0,8.9,0.00
103,2025-05-20 07:00:00,2025-05-20,7,0,11.3,9.3,0.0,0.0,0.0,0.0,9.4,2096.72
104,2025-05-20 08:00:00,2025-05-20,8,0,12.8,11.0,0.0,0.0,0.0,0.0,7.6,3600.00
105,2025-05-20 09:00:00,2025-05-20,9,0,14.9,13.2,0.0,0.0,0.0,10.0,7.0,3600.00
106,2025-05-20 10:00:00,2025-05-20,10,0,17.4,15.8,0.0,0.0,0.0,19.0,6.9,3600.00
107,2025-05-20 11:00:00,2025-05-20,11,0,19.8,18.6,0.0,0.0,1.0,46.0,7.9,3600.00
108,2025-05-20 12:00:00,2025-05-20,12,0,21.6,20.5,0.0,0.0,2.0,70.0,9.8,3600.00
109,2025-05-20 13:00:00,2025-05-20,13,0,22.8,21.7,0.0,0.0,3.0,100.0,10.2,3600.00
110,2025-05-20 14:00:00,2025-05-20,14,0,23.1,21.2,0.0,0.0,1.0,48.0,12.8,3600.00
111,2025-05-20 15:00:00,2025-05-20,15,0,22.3,19.0,0.0,0.0,1.0,37.0,18.0,3600.00
112,2025-05-20 16:00:00,2025-05-20,16,0,21.5,18.3,0.0,0.0,0.0,5.0,18.5,3600.00
113,2025-05-20 17:00:00,2025-05-20,17,0,21.1,17.6,0.0,0.0,0.0,12.0,17.5,3600.00
114,2025-05-20 18:00:00,2025-05-20,18,0,20.3,16.1,0.0,0.0,3.0,99.0,17.3,3600.00
115,2025-05-20 19:00:00,2025-05-20,19,0,19.0,15.1,0.0,0.0,3.0,100.0,15.4,3600.00
116,2025-05-20 20:00:00,2025-05-20,20,0,17.3,14.1,0.0,0.0,3.0,100.0,13.3,3600.00
117,2025-05-20 21:00:00,2025-05-20,21,0,15.6,12.9,0.0,0.0,3.0,100.0,11.3,1865.63
118,2025-05-20 22:00:00,2025-05-20,22,0,14.0,11.7,0.0,0.0,3.0,100.0,10.1,0.00
119,2025-05-20 23:00:00,2025-05-20,23,0,12.8,10.7,0.0,0.0,3.0,100.0,9.6,0.00
120,2025-05-21 00:00:00,2025-05-21,0,0,11.9,10.1,0.0,0.0,3.0,99.0,8.4,0.00
121,2025-05-21 01:00:00,2025-05-21,1,0,11.4,9.8,0.0,0.0,3.0,100.0,7.1,0.00
122,2025-05-21 02:00:00,2025-05-21,2,0,11.1,9.5,0.0,0.0,3.0,100.0,6.6,0.00
123,2025-05-21 03:00:00,2025-05-21,3,0,9.8,8.7,0.0,0.0,3.0,100.0,3.5,0.00
124,2025-05-21 04:00:00,2025-05-21,4,0,9.6,8.6,0.0,0.0,3.0,100.0,3.3,0.00
125,2025-05-21 05:00:00,2025-05-21,5,0,9.1,7.7,0.0,0.0,3.0,100.0,5.9,0.00
126,2025-05-21 06:00:00,2025-05-21,6,0,8.8,7.5,0.0,0.0,3.0,95.0,5.3,0.00
127,2025-05-21 07:00:00,2025-05-21,7,0,9.1,7.6,0.0,0.0,3.0,99.0,6.4,1689.73
128,2025-05-21 08:00:00,2025-05-21,8,0,10.8,9.8,0.0,0.0,3.0,100.0,3.8,3600.00
129,2025-05-21 09:00:00,2025-05-21,9,0,12.5,11.6,0.0,0.0,3.0,100.0,2.9,1260.80
130,2025-05-21 10:00:00,2025-05-21,10,0,13.8,12.5,0.0,0.0,3.0,100.0,4.3,0.00
131,2025-05-21 11:00:00,2025-05-21,11,0,15.5,13.7,0.0,0.0,3.0,100.0,5.5,99.88
132,2025-05-21 12:00:00,2025-05-21,12,0,16.7,14.6,0.0,0.0,3.0,100.0,6.2,402.35
133,2025-05-21 13:00:00,2025-05-21,13,0,18.0,15.7,0.0,0.0,3.0,100.0,6.6,3448.38
134,2025-05-21 14:00:00,2025-05-21,14,0,18.4,15.8,0.0,0.0,3.0,100.0,8.3,2962.27
135,2025-05-21 15:00:00,2025-05-21,15,0,19.9,17.9,0.0,0.0,3.0,96.0,11.2,3600.00
136,2025-05-21 16:00:00,2025-05-21,16,0,19.0,15.6,0.0,0.0,3.0,92.0,13.5,3600.00
137,2025-05-21 17:00:00,2025-05-21,17,0,18.0,14.7,0.0,0.0,3.0,100.0,15.2,3600.00
138,2025-05-21 18:00:00,2025-05-21,18,0,15.7,12.8,0.1,0.0,51.0,100.0,17.6,3600.00
139,2025-05-21 19:00:00,2025-05-21,19,0,14.5,11.4,0.0,0.0,3.0,100.0,16.2,3600.00
140,2025-05-21 20:00:00,2025-05-21,20,0,13.2,10.0,0.0,0.0,3.0,94.0,15.3,3600.00
141,2025-05-21 21:00:00,2025-05-21,21,0,12.2,9.1,0.0,0.0,3.0,88.0,14.3,2252.22
142,2025-05-21 22:00:00,2025-05-21,22,0,11.2,8.3,0.0,0.0,0.0,7.0,12.9,0.00
143,2025-05-21 23:00:00,2025-05-21,23,0,10.7,8.1,0.0,0.0,0.0,8.0,10.3,0.00
144,2025-05-22 00:00:00,2025-05-22,0,0,10.5,8.0,0.0,0.0,1.0,38.0,9.1,0.00
145,2025-05-22 01:00:00,2025-05-22,1,0,10.5,8.0,0.0,0.0,2.0,69.0,9.3,0.00
146,2025-05-22 02:00:00,2025-05-22,2,0,11.0,8.3,0.0,0.0,3.0,100.0,10.2,0.00
147,2025-05-22 03:00:00,2025-05-22,3,0,11.0,8.2,0.0,0.0,3.0,100.0,10.6,0.00
148,2025-05-22 04:00:00,2025-05-22,4,0,10.4,7.8,0.0,0.0,3.0,100.0,10.1,0.00
149,2025-05-22 05:00:00,2025-05-22,5,0,9.8,7.2,0.0,0.0,3.0,94.0,10.0,0.00
150,2025-05-22 06:00:00,2025-05-22,6,0,9.6,7.1,0.0,0.0,3.0,84.0,9.7,0.00
151,2025-05-22 07:00:00,2025-05-22,7,0,10.6,8.2,0.0,0.0,3.0,100.0,9.6,0.00
152,2025-05-22 08:00:00,2025-05-22,8,0,11.3,7.9,0.0,0.0,3.0,100.0,15.3,0.00
153,2025-05-22 09:00:00,2025-05-22,9,0,12.2,8.4,0.0,0.0,3.0,100.0,17.6,1243.68
154,2025-05-22 10:00:00,2025-05-22,10,0,12.3,8.7,0.0,0.0,3.0,100.0,17.1,0.00
155,2025-05-22 11:00:00,2025-05-22,11,0,11.7,8.6,0.2,0.0,51.0,100.0,14.8,0.00
156,2025-05-22 12:00:00,2025-05-22,12,0,11.9,8.7,0.2,0.0,51.0,100.0,15.1,0.00
157,2025-05-22 13:00:00,2025-05-22,13,0,11.8,8.5,0.2,0.0,51.0,100.0,14.7,0.00
158,2025-05-22 14:00:00,2025-05-22,14,0,12.6,9.0,0.0,0.0,3.0,100.0,14.9,0.00
159,2025-05-22 15:00:00,2025-05-22,15,0,13.0,9.3,0.0,0.0,3.0,98.0,15.4,0.00
160,2025-05-22 16:00:00,2025-05-22,16,0,13.4,9.3,0.0,0.0,3.0,83.0,16.3,1142.16
161,2025-05-22 17:00:00,2025-05-22,17,0,14.0,9.7,0.0,0.0,1.0,29.0,16.4,3600.00
162,2025-05-22 18:00:00,2025-05-22,18,0,13.8,9.3,0.0,0.0,1.0,22.0,17.3,3600.00
163,2025-05-22 19:00:00,2025-05-22,19,0,13.1,8.8,0.0,0.0,1.0,23.0,16.6,3600.00
164,2025-05-22 20:00:00,2025-05-22,20,0,12.4,8.2,0.0,0.0,1.0,29.0,15.4,3600.00
165,2025-05-22 21:00:00,2025-05-22,21,0,11.4,7.5,0.0,0.0,0.0,5.0,14.3,3600.00
166,2025-05-22 22:00:00,2025-05-22,22,0,10.2,7.2,0.0,0.0,0.0,1.0,9.2,0.00
167,2025-05-22 23:00:00,2025-05-22,23,0,9.4,6.9,0.0,0.0,0.0,9.0,6.7,0.00
168,2025-05-23 00:00:00,2025-05-23,0,0,8.8,6.5,0.0,0.0,0.0,17.0,6.0,0.00
169,2025-05-23 01:00:00,2025-05-23,1,0,8.3,5.9,0.0,0.0,1.0,29.0,6.6,0.00
170,2025-05-23 02:00:00,2025-05-23,2,0,7.8,5.5,0.0,0.0,1.0,35.0,6.4,0.00
171,2025-05-23 03:00:00,2025-05-23,3,0,6.3,3.5,0.0,0.0,1.0,20.0,9.0,0.00
172,2025-05-23 04:00:00,2025-05-23,4,0,6.2,3.4,0.0,0.0,1.0,36.0,9.0,0.00
173,2025-05-23 05:00:00,2025-05-23,5,0,6.3,3.6,0.0,0.0,1.0,46.0,9.0,0.00
174,2025-05-23 06:00:00,2025-05-23,6,0,6.5,3.8,0.0,0.0,1.0,49.0,9.1,0.00
175,2025-05-23 07:00:00,2025-05-23,7,0,7.4,4.7,0.0,0.0,1.0,45.0,9.9,1091.24
176,2025-05-23 08:00:00,2025-05-23,8,0,9.2,6.5,0.0,0.0,2.0,54.0,10.1,3600.00
177,2025-05-23 09:00:00,2025-05-23,9,0,10.5,6.7,0.0,0.0,1.0,42.0,16.0,3600.00
178,2025-05-23 10:00:00,2025-05-23,10,0,11.6,7.8,0.0,0.0,2.0,71.0,15.5,3600.00
179,2025-05-23 11:00:00,2025-05-23,11,0,12.1,8.0,0.0,0.0,2.0,61.0,17.2,3600.00
180,2025-05-23 12:00:00,2025-05-23,12,0,12.4,8.5,0.0,0.0,3.0,100.0,16.0,3600.00
181,2025-05-23 13:00:00,2025-05-23,13,0,13.2,9.1,0.0,0.0,2.0,66.0,16.6,3600.00
182,2025-05-23 14:00:00,2025-05-23,14,0,13.7,9.5,0.0,0.0,3.0,88.0,17.2,3600.00
183,2025-05-23 15:00:00,2025-05-23,15,0,13.9,9.7,0.0,0.0,3.0,88.0,18.5,3600.00
184,2025-05-23 16:00:00,2025-05-23,16,0,13.5,9.6,0.0,0.0,2.0,68.0,16.1,3317.94
185,2025-05-23 17:00:00,2025-05-23,17,0,14.1,10.3,0.0,0.0,2.0,54.0,14.4,3600.00
186,2025-05-23 18:00:00,2025-05-23,18,0,14.5,11.5,0.0,0.0,0.0,9.0,9.3,3600.00
187,2025-05-23 19:00:00,2025-05-23,19,0,14.6,11.7,0.0,0.0,0.0,11.0,9.2,3600.00
188,2025-05-23 20:00:00,2025-05-23,20,0,14.2,11.5,0.0,0.0,0.0,5.0,7.3,3600.00
189,2025-05-23 21:00:00,2025-05-23,21,0,13.2,11.8,0.0,0.0,0.0,14.0,2.3,3600.00
190,2025-05-23 22:00:00,2025-05-23,22,0,12.2,11.0,0.0,0.0,3.0,99.0,0.6,0.00
191,2025-05-23 23:00:00,2025-05-23,23,0,12.4,10.9,0.0,0.0,3.0,100.0,2.9,0.00
192,2025-05-24 00:00:00,2025-05-24,0,0,11.6,9.4,0.0,0.0,3.0,99.0,7.0,0.00
193,2025-05-24 01:00:00,2025-05-24,1,0,10.9,8.3,0.0,0.0,3.0,98.0,8.7,0.00
194,2025-05-24 02:00:00,2025-05-24,2,0,10.2,7.4,0.0,0.0,3.0,100.0,10.4,0.00
195,2025-05-24 03:00:00,2025-05-24,3,0,9.4,6.0,0.0,0.0,3.0,100.0,13.1,0.00
196,2025-05-24 04:00:00,2025-05-24,4,0,9.3,5.4,0.0,0.0,3.0,100.0,14.4,0.00
197,2025-05-24 05:00:00,2025-05-24,5,0,9.7,5.6,0.0,0.0,3.0,100.0,15.3,0.00
198,2025-05-24 06:00:00,2025-05-24,6,0,9.8,5.7,0.2,0.0,51.0,100.0,16.1,0.00
199,2025-05-24 07:00:00,2025-05-24,7,0,10.4,6.1,0.0,0.0,3.0,100.0,16.8,0.00
200,2025-05-24 08:00:00,2025-05-24,8,0,11.1,7.1,0.0,0.0,3.0,100.0,16.2,0.00
201,2025-05-24 09:00:00,2025-05-24,9,0,11.4,7.8,0.0,0.0,3.0,100.0,15.4,0.00
202,2025-05-24 10:00:00,2025-05-24,10,0,12.0,8.8,0.3,0.0,51.0,100.0,16.2,0.00
203,2025-05-24 11:00:00,2025-05-24,11,0,12.0,9.1,0.8,0.0,53.0,100.0,17.5,0.00
204,2025-05-24 12:00:00,2025-05-24,12,0,11.9,9.0,1.1,0.0,55.0,100.0,19.5,0.00
205,2025-05-24 13:00:00,2025-05-24,13,0,11.8,8.9,1.3,0.0,61.0,100.0,21.4,0.00
206,2025-05-24 14:00:00,2025-05-24,14,0,13.3,10.4,0.7,0.0,53.0,100.0,23.2,0.00
207,2025-05-24 15:00:00,2025-05-24,15,0,13.5,11.1,0.8,0.0,53.0,100.0,20.9,0.00
208,2025-05-24 16:00:00,2025-05-24,16,0,15.1,13.7,0.4,0.0,51.0,100.0,17.2,0.00
209,2025-05-24 17:00:00,2025-05-24,17,0,16.4,14.9,0.1,0.0,51.0,100.0,20.4,0.00
210,2025-05-24 18:00:00,2025-05-24,18,0,16.4,14.9,0.1,0.0,51.0,100.0,19.8,0.00
211,2025-05-24 19:00:00,2025-05-24,19,0,16.6,15.3,0.0,0.0,3.0,100.0,17.4,0.00
212,2025-05-24 20:00:00,2025-05-24,20,0,16.5,14.9,0.0,0.0,3.0,100.0,18.6,0.00
213,2025-05-24 21:00:00,2025-05-24,21,0,15.9,14.3,0.0,0.0,3.0,100.0,18.0,0.00
214,2025-05-24 22:00:00,2025-05-24,22,0,15.4,13.7,0.0,0.0,3.0,100.0,18.2,0.00
215,2025-05-24 23:00:00,2025-05-24,23,0,15.1,13.5,0.0,0.0,3.0,100.0,17.5,0.00
216,2025-05-25 00:00:00,2025-05-25,0,0,15.0,13.4,0.1,0.0,51.0,100.0,17.3,0.00
217,2025-05-25 01:00:00,2025-05-25,1,0,14.7,13.0,0.2,0.0,51.0,100.0,17.9,0.00
218,2025-05-25 02:00:00,2025-05-25,2,0,14.5,12.9,0.6,0.0,53.0,100.0,17.7,0.00
219,2025-05-25 03:00:00,2025-05-25,3,0,15.1,13.6,0.0,0.0,3.0,100.0,17.7,0.00
220,2025-05-25 04:00:00,2025-05-25,4,0,15.2,13.3,0.0,0.0,3.0,100.0,19.1,0.00
221,2025-05-25 05:00:00,2025-05-25,5,0,14.9,12.8,0.0,0.0,3.0,100.0,19.8,0.00
222,2025-05-25 06:00:00,2025-05-25,6,0,14.7,12.6,0.3,0.0,51.0,100.0,19.5,0.00
223,2025-05-25 07:00:00,2025-05-25,7,0,14.5,12.5,0.3,0.0,51.0,100.0,19.7,0.00
224,2025-05-25 08:00:00,2025-05-25,8,0,14.9,12.8,0.0,0.0,3.0,100.0,20.5,0.00
225,2025-05-25 09:00:00,2025-05-25,9,0,15.1,13.0,0.5,0.0,53.0,100.0,20.7,0.00
226,2025-05-25 10:00:00,2025-05-25,10,0,15.2,12.7,0.2,0.0,51.0,100.0,24.2,0.00
227,2025-05-25 11:00:00,2025-05-25,11,0,16.4,13.8,0.1,0.0,51.0,13.0,23.9,1646.55
228,2025-05-25 12:00:00,2025-05-25,12,0,18.8,16.0,0.1,0.0,51.0,45.0,26.1,3600.00
229,2025-05-25 13:00:00,2025-05-25,13,0,18.7,15.4,0.1,0.0,51.0,58.0,26.6,3600.00
230,2025-05-25 14:00:00,2025-05-25,14,0,18.8,16.1,0.0,0.0,2.0,52.0,22.2,3600.00
231,2025-05-25 15:00:00,2025-05-25,15,0,19.3,16.2,0.1,0.0,51.0,100.0,24.3,3600.00
232,2025-05-25 16:00:00,2025-05-25,16,0,19.0,15.7,0.3,0.0,51.0,100.0,24.8,3600.00
233,2025-05-25 17:00:00,2025-05-25,17,0,18.7,15.6,0.1,0.0,51.0,27.0,22.3,3600.00
234,2025-05-25 18:00:00,2025-05-25,18,0,19.0,16.0,0.1,0.0,51.0,52.0,21.2,3600.00
235,2025-05-25 19:00:00,2025-05-25,19,0,17.5,14.7,0.1,0.0,51.0,100.0,19.9,3600.00
236,2025-05-25 20:00:00,2025-05-25,20,0,16.7,14.6,0.1,0.0,51.0,100.0,15.7,129.47
237,2025-05-25 21:00:00,2025-05-25,21,0,16.0,13.4,0.0,0.0,3.0,90.0,16.5,0.00
238,2025-05-25 22:00:00,2025-05-25,22,0,14.7,12.2,0.0,0.0,2.0,70.0,15.1,0.00
239,2025-05-25 23:00:00,2025-05-25,23,0,13.5,10.9,0.0,0.0,3.0,92.0,15.0,0.00
240,2025-05-26 00:00:00,2025-05-26,0,0,13.2,10.7,0.0,0.0,3.0,100.0,14.8,0.00
241,2025-05-26 01:00:00,2025-05-26,1,0,12.6,10.2,0.0,0.0,3.0,96.0,14.0,0.00
242,2025-05-26 02:00:00,2025-05-26,2,0,12.2,9.9,0.0,0.0,2.0,57.0,13.4,0.00
243,2025-05-26 03:00:00,2025-05-26,3,0,11.6,9.1,0.0,0.0,1.0,23.0,14.8,0.00
244,2025-05-26 04:00:00,2025-05-26,4,0,11.6,9.4,0.0,0.0,3.0,100.0,13.1,0.00
245,2025-05-26 05:00:00,2025-05-26,5,0,11.7,9.7,0.0,0.0,0.0,8.0,12.6,0.00
246,2025-05-26 06:00:00,2025-05-26,6,0,11.2,8.9,0.0,0.0,0.0,0.0,13.4,0.00
247,2025-05-26 07:00:00,2025-05-26,7,0,11.4,9.1,0.0,0.0,1.0,21.0,13.7,2465.70
248,2025-05-26 08:00:00,2025-05-26,8,0,12.6,10.4,0.0,0.0,3.0,98.0,13.2,3600.00
249,2025-05-26 09:00:00,2025-05-26,9,0,13.9,10.8,0.0,0.0,3.0,94.0,17.7,3600.00
250,2025-05-26 10:00:00,2025-05-26,10,0,15.0,11.6,0.0,0.0,2.0,51.0,18.6,3600.00
251,2025-05-26 11:00:00,2025-05-26,11,0,16.0,12.5,0.0,0.0,2.0,79.0,18.6,3600.00
252,2025-05-26 12:00:00,2025-05-26,12,0,16.9,13.6,0.0,0.0,3.0,98.0,17.9,3600.00
253,2025-05-26 13:00:00,2025-05-26,13,0,17.8,14.4,0.1,0.0,51.0,69.0,18.9,3600.00
254,2025-05-26 14:00:00,2025-05-26,14,0,18.1,14.5,0.0,0.0,3.0,92.0,20.0,3600.00
255,2025-05-26 15:00:00,2025-05-26,15,0,18.1,13.9,0.0,0.0,3.0,84.0,22.1,3600.00
256,2025-05-26 16:00:00,2025-05-26,16,0,18.5,14.3,0.0,0.0,3.0,83.0,21.5,3600.00
257,2025-05-26 17:00:00,2025-05-26,17,0,17.7,13.3,0.0,0.0,3.0,88.0,22.0,2933.03

,FullDate,date,hour,minute,Kanaal,Programma,Lengte_sec,Kijkers
0,2025-05-16 20:15:38,2025-05-16,20,0,VRT 1,THUIS,1489,937648
1,2025-05-16 19:00:05,2025-05-16,19,0,VRT 1,HET 7 UUR-JOURNAAL,2685,760119
2,2025-05-16 19:46:40,2025-05-16,19,0,VRT 1,IEDEREEN BEROEMD,1331,581626
3,2025-05-16 20:43:22,2025-05-16,20,0,VTM,I CAN SEE YOUR VOICE,5500,527119
4,2025-05-16 20:08:26,2025-05-16,20,0,VTM,FAMILIE,1468,526533
5,2025-05-16 18:28:54,2025-05-16,18,0,VRT 1,BLOKKEN,1708,496405
6,2025-05-16 18:59:48,2025-05-16,18,0,VTM,NIEUWS 19U VTM,3334,423571
7,2025-05-16 20:42:52,2025-05-16,20,0,VRT 1,LA VIE EN ROSE,2832,411246
8,2025-05-16 13:00:04,2025-05-16,13,0,VRT 1,HET 1 UUR-JOURNAAL,1744,330006
9,2025-05-16 21:30:46,2025-05-16,21,0,VRT CANVAS,RIDLEY,5310,320467
10,2025-05-16 18:10:34,2025-05-16,18,0,VRT 1,DAGELIJKSE KOST,927,269784
11,2025-05-16 20:40:03,2025-05-16,20,0,PLAY4,THE REAL HOUSEWIVES OF ANTWERP,2748,220478
12,2025-05-16 12:59:48,2025-05-16,12,0,VTM,NIEUWS 13U VTM,1602,214474
13,2025-05-16 20:37:28,2025-05-16,20,0,VRT CANVAS,DE AFSPRAAK,3047,173242
14,2025-05-16 14:33:41,2025-05-16,14,0,VRT 1,FLIKKEN MAASTRICHT,3000,163422
15,2025-05-16 22:05:55,2025-05-16,22,0,VRT 1,HET JOURNAAL LAAT,1593,156745
16,2025-05-16 22:38:57,2025-05-16,22,0,VTM,"EEN ECHTE JOB, VROEDVROUW AN",3048,156633
17,2025-05-16 22:38:03,2025-05-16,22,0,VRT 1,GIRO MAGAZINE,922,156226
18,2025-05-16 17:05:29,2025-05-16,17,0,VRT 1,RECHT OP RECHT,3328,155065
19,2025-05-16 21:31:58,2025-05-16,21,0,VRT 1,DE CLUB,1899,133372
20,2025-05-17 21:00:05,2025-05-17,21,0,VRT 1,EUROVISIE SONGFESTIVAL,14970,706321
21,2025-05-17 19:00:05,2025-05-17,19,0,VRT 1,HET 7 UUR-JOURNAAL,2194,619944
22,2025-05-17 20:13:59,2025-05-17,20,0,VRT 1,FC DE KAMPIOENEN,1625,478527
23,2025-05-17 18:59:48,2025-05-17,18,0,VTM,NIEUWS 19U VTM,2697,411287
24,2025-05-17 20:44:17,2025-05-17,20,0,VRT 1,EUROVISION HALLO BASEL,938,395763
25,2025-05-17 19:46:27,2025-05-17,19,0,VRT 1,IEDEREEN BEROEMD,1532,361120
26,2025-05-17 19:56:19,2025-05-17,19,0,VTM,HET ECHTE LEVEN IN DE ZOO,1470,300931
27,2025-05-17 13:00:05,2025-05-17,13,0,VRT 1,HET 1 UUR-JOURNAAL,1557,289328
28,2025-05-18 01:10:17,2025-05-18,1,0,VRT 1,HET JOURNAAL LAAT,1228,250420
29,2025-05-17 20:53:28,2025-05-17,20,0,VRT CANVAS,OXEN,2675,216830
30,2025-05-17 20:31:50,2025-05-17,20,0,VTM,SKYSCRAPER,5316,190055
31,2025-05-17 14:38:18,2025-05-17,14,0,VRT 1,FLIKKEN MAASTRICHT,3025,173143
32,2025-05-17 18:12:23,2025-05-17,18,0,VRT 1,DOWN THE ROAD,2665,172740
33,2025-05-17 12:59:48,2025-05-17,12,0,VTM,NIEUWS 13U VTM,1574,171490
34,2025-05-17 12:30:44,2025-05-17,12,0,VRT 1,DE MARKT,1615,156236
35,2025-05-17 20:10:24,2025-05-17,20,0,VRT CANVAS,DE OVERLEVERS,2402,129904
36,2025-05-17 13:32:18,2025-05-17,13,0,VRT 1,ANDERMANS ZAKEN,3091,129271
37,2025-05-17 16:52:36,2025-05-17,16,0,VRT 1,RECHT OP RECHT,3529,121567
38,2025-05-17 23:07:06,2025-05-17,23,0,PLAY4,SPORTS LATE NIGHT,2043,120548
39,2025-05-17 12:00:13,2025-05-17,12,0,EUROSPORT 1 (NL),CYCL. GIRO D'ITALIA,17292,107122
40,2025-05-18 20:00:03,2025-05-18,20,0,PLAY4,DE MOL,3927,1026738
41,2025-05-18 20:04:12,2025-05-18,20,0,VRT 1,CHATEAU PLANCKAERT,2501,832797
42,2025-05-18 19:00:09,2025-05-18,19,0,VRT 1,HET 7 UUR-JOURNAAL,1389,743731
43,2025-05-18 19:23:32,2025-05-18,19,0,VRT 1,SPORTWEEKEND,2044,717046
44,2025-05-18 19:58:52,2025-05-18,19,0,VTM,DANCING WITH THE STARS,5873,678050
45,2025-05-18 20:47:54,2025-05-18,20,0,VRT 1,FLIKKEN MAASTRICHT,2943,518866
46,2025-05-18 18:59:48,2025-05-18,18,0,VTM,NIEUWS 19U VTM,2834,481123
47,2025-05-18 13:00:05,2025-05-18,13,0,VRT 1,HET 1 UUR-JOURNAAL,1742,373388
48,2025-05-18 21:59:22,2025-05-18,21,0,VTM2,"JONAS & JELLE, FROM ZERO TO HERO",3477,297267
49,2025-05-18 18:10:55,2025-05-18,18,0,VRT 1,DAGELIJKSE KOST,2732,249029
50,2025-05-18 11:00:15,2025-05-18,11,0,VRT 1,DE ZEVENDE DAG,7045,240211
51,2025-05-18 22:03:22,2025-05-18,22,0,VTM,ALLOO BIJ DE VERKEERSPOLITIE,3204,231551
52,2025-05-18 12:59:44,2025-05-18,12,0,VTM,NIEUWS 13U VTM,2428,221932
53,2025-05-18 21:38:54,2025-05-18,21,0,VRT 1,DE IDEALE WERELD,2274,212453
54,2025-05-18 20:00:09,2025-05-18,20,0,VRT CANVAS,APPLES NEVER FALL,2568,208880
55,2025-05-18 17:26:50,2025-05-18,17,0,EUROSPORT 1 (NL),KOP OVER KOP,2181,195482
56,2025-05-18 22:20:07,2025-05-18,22,0,VRT 1,HET JOURNAAL LAAT,1007,184427
57,2025-05-18 22:18:07,2025-05-18,22,0,PLAY4,SPORTS LATE NIGHT,3241,171901
58,2025-05-18 22:41:41,2025-05-18,22,0,VRT 1,GIRO MAGAZINE,1150,165839
59,2025-05-18 12:35:35,2025-05-18,12,0,EUROSPORT 1 (NL),CYCL. GIRO D'ITALIA,15418,152270
60,2025-05-19 20:14:56,2025-05-19,20,0,VRT 1,THUIS,1419,772643
61,2025-05-19 19:00:05,2025-05-19,19,0,VRT 1,HET 7 UUR-JOURNAAL,2765,755738
62,2025-05-19 18:59:48,2025-05-19,18,0,VTM,NIEUWS 19U VTM,3471,597882
63,2025-05-19 20:39:30,2025-05-19,20,0,VRT 1,GLORIA MUNDI,3104,571035
64,2025-05-19 19:47:38,2025-05-19,19,0,VRT 1,IEDEREEN BEROEMD,1282,536836
65,2025-05-19 20:10:06,2025-05-19,20,0,VTM,FAMILIE,1525,523749
66,2025-05-19 18:28:54,2025-05-19,18,0,VRT 1,BLOKKEN,1710,432185
67,2025-05-19 21:32:51,2025-05-19,21,0,VRT 1,"ZELFDE DEUR, 20 JAAR LATER",2400,376259
68,2025-05-19 21:17:21,2025-05-19,21,0,PLAY4,BLIND GEKOCHT,3448,376109
69,2025-05-19 20:46:18,2025-05-19,20,0,VTM,ZE ZEGGEN DAT,3094,326126
70,2025-05-19 13:00:03,2025-05-19,13,0,VRT 1,HET 1 UUR-JOURNAAL,1590,311684
71,2025-05-19 22:15:05,2025-05-19,22,0,VRT 1,HET JOURNAAL LAAT,1507,234280
72,2025-05-19 18:11:27,2025-05-19,18,0,VRT 1,DAGELIJKSE KOST,972,218653
73,2025-05-19 12:59:48,2025-05-19,12,0,VTM,NIEUWS 13U VTM,1676,205470
74,2025-05-19 19:59:08,2025-05-19,19,0,PLAY4,DE TAFEL VAN GERT,3772,190278
75,2025-05-19 18:22:03,2025-05-19,18,0,VTM,MILO,1535,188093
76,2025-05-19 20:33:54,2025-05-19,20,0,VRT CANVAS,DE AFSPRAAK,2722,170017
77,2025-05-19 22:23:53,2025-05-19,22,0,VRT CANVAS,CAMPUS CUP,2801,157438
78,2025-05-19 21:56:29,2025-05-19,21,0,VTM,BAR GOENS,2759,148483
79,2025-05-19 21:20:44,2025-05-19,21,0,VRT CANVAS,EXTRA TIME,3709,140205
80,2025-05-20 20:18:26,2025-05-20,20,0,VRT 1,THUIS,1446,820812
81,2025-05-20 19:00:05,2025-05-20,19,0,VRT 1,HET 7 UUR-JOURNAAL,2853,736567
82,2025-05-20 19:50:07,2025-05-20,19,0,VRT 1,IEDEREEN BEROEMD,1320,630561
83,2025-05-20 20:43:48,2025-05-20,20,0,VRT 1,MET DE WIND MEE,2564,582662
84,2025-05-20 18:59:48,2025-05-20,18,0,VTM,NIEUWS 19U VTM,3247,505032
85,2025-05-20 20:05:37,2025-05-20,20,0,VTM,FAMILIE,1470,454459
86,2025-05-20 18:29:17,2025-05-20,18,0,VRT 1,BLOKKEN,1709,444528
87,2025-05-20 20:41:17,2025-05-20,20,0,VTM,HUIS GEMAAKT,3453,400905
88,2025-05-20 13:00:05,2025-05-20,13,0,VRT 1,HET 1 UUR-JOURNAAL,1723,346888
89,2025-05-20 21:27:45,2025-05-20,21,0,VRT 1,POLITIE 24/7,2620,240513
90,2025-05-20 18:12:16,2025-05-20,18,0,VRT 1,DAGELIJKSE KOST,929,240256
91,2025-05-20 21:55:25,2025-05-20,21,0,VTM,BAR GOENS,2851,200510
92,2025-05-20 22:10:20,2025-05-20,22,0,VRT CANVAS,CAMPUS CUP,2664,183512
93,2025-05-20 22:13:45,2025-05-20,22,0,VRT 1,HET JOURNAAL LAAT,1840,178987
94,2025-05-20 12:59:48,2025-05-20,12,0,VTM,NIEUWS 13U VTM,1734,178409
95,2025-05-20 21:19:08,2025-05-20,21,0,PLAY4,ASSISEN,2511,174855
96,2025-05-20 19:59:02,2025-05-20,19,0,PLAY4,DE TAFEL VAN GERT,4026,162479
97,2025-05-20 18:25:32,2025-05-20,18,0,VTM,MILO,1331,151186
98,2025-05-20 17:11:20,2025-05-20,17,0,VRT 1,RECHT OP RECHT,3175,149068
99,2025-05-20 15:07:28,2025-05-20,15,0,VRT 1,FLIKKEN MAASTRICHT,3028,138657
100,2025-05-21 20:18:21,2025-05-21,20,0,VRT 1,THUIS,1417,806473
101,2025-05-21 19:00:05,2025-05-21,19,0,VRT 1,HET 7 UUR-JOURNAAL,2899,763154
102,2025-05-21 19:49:53,2025-05-21,19,0,VRT 1,IEDEREEN BEROEMD,1210,606468
103,2025-05-21 18:59:48,2025-05-21,18,0,VTM,NIEUWS 19U VTM,3245,556517
104,2025-05-21 18:29:12,2025-05-21,18,0,VRT 1,BLOKKEN,1709,521698
105,2025-05-21 20:43:12,2025-05-21,20,0,VRT 1,"ONS HUIS, NIEUW HUIS",3825,512040
106,2025-05-21 20:06:29,2025-05-21,20,0,VTM,FAMILIE,1477,465875
107,2025-05-21 20:39:27,2025-05-21,20,0,VTM,WAT VERDIENT VLAANDEREN?,3139,357181
108,2025-05-21 13:00:05,2025-05-21,13,0,VRT 1,HET 1 UUR-JOURNAAL,1594,328350
109,2025-05-21 21:17:33,2025-05-21,21,0,PLAY4,VIVA LA FETA,3267,313083
110,2025-05-21 18:12:13,2025-05-21,18,0,VRT 1,DAGELIJKSE KOST,969,276702
111,2025-05-21 18:23:22,2025-05-21,18,0,VTM,MILO,1446,211331
112,2025-05-21 17:06:33,2025-05-21,17,0,VRT 1,RECHT OP RECHT,3495,189077
113,2025-05-21 21:45:40,2025-05-21,21,0,VTM,BAR GOENS,2136,188760
114,2025-05-21 12:59:48,2025-05-21,12,0,VTM,NIEUWS 13U VTM,1638,184916
115,2025-05-21 21:01:31,2025-05-21,21,0,PLAY6,VB. C3 UEFA FIN - TOTTENHAM/MANCHESTER UNITED,6031,176584
116,2025-05-21 20:37:38,2025-05-21,20,0,VRT CANVAS,DE AFSPRAAK,2904,176545
117,2025-05-21 19:59:02,2025-05-21,19,0,PLAY4,DE TAFEL VAN GERT,3890,175830
118,2025-05-21 22:23:04,2025-05-21,22,0,VRT CANVAS,CAMPUS CUP,2948,174906
119,2025-05-21 20:00:03,2025-05-21,20,0,VRT CANVAS,TER ZAKE,2115,151359
120,2025-05-22 20:17:18,2025-05-22,20,0,VRT 1,THUIS,1540,798657
121,2025-05-22 19:00:05,2025-05-22,19,0,VRT 1,HET 7 UUR-JOURNAAL,2761,745037
122,2025-05-22 19:48:23,2025-05-22,19,0,VRT 1,IEDEREEN BEROEMD,1335,602612
123,2025-05-22 18:59:48,2025-05-22,18,0,VTM,NIEUWS 19U VTM,3416,506594
124,2025-05-22 18:29:01,2025-05-22,18,0,VRT 1,BLOKKEN,1708,488115
125,2025-05-22 20:43:35,2025-05-22,20,0,VTM,HUIS GEMAAKT,3402,459562
126,2025-05-22 20:08:32,2025-05-22,20,0,VTM,FAMILIE,1471,439141
127,2025-05-22 20:43:53,2025-05-22,20,0,VRT 1,WONDER BOVEN WONDER,2610,396281
128,2025-05-22 13:00:04,2025-05-22,13,0,VRT 1,HET 1 UUR-JOURNAAL,1784,344288
129,2025-05-22 18:12:01,2025-05-22,18,0,VRT 1,DAGELIJKSE KOST,974,271622
130,2025-05-22 21:29:24,2025-05-22,21,0,VRT 1,112 HULP IS ONDERWEG,2689,252959
131,2025-05-22 12:59:48,2025-05-22,12,0,VTM,NIEUWS 13U VTM,1675,224387
132,2025-05-22 21:19:06,2025-05-22,21,0,PLAY4,KAMP JEROOM,2715,222022
133,2025-05-22 22:15:51,2025-05-22,22,0,VRT 1,HET JOURNAAL LAAT,1508,212665
134,2025-05-22 21:58:24,2025-05-22,21,0,VTM,BAR GOENS,2640,211108
135,2025-05-22 19:59:03,2025-05-22,19,0,PLAY4,DE TAFEL VAN GERT,4047,198891
136,2025-05-22 22:47:48,2025-05-22,22,0,VTM,TELEFACTS,2873,193554
137,2025-05-22 18:23:06,2025-05-22,18,0,VTM,MILO,1477,185612
138,2025-05-22 20:37:41,2025-05-22,20,0,VRT CANVAS,DE AFSPRAAK,2875,173402
139,2025-05-22 22:19:01,2025-05-22,22,0,VRT CANVAS,CAMPUS CUP,2828,170921
140,2025-05-23 20:17:16,2025-05-23,20,0,VRT 1,THUIS,1435,786790
141,2025-05-23 19:00:05,2025-05-23,19,0,VRT 1,HET 7 UUR-JOURNAAL,2984,729945
142,2025-05-23 19:51:18,2025-05-23,19,0,VRT 1,IEDEREEN BEROEMD,1214,598271
143,2025-05-23 18:29:33,2025-05-23,18,0,VRT 1,BLOKKEN,1710,498063
144,2025-05-23 18:59:53,2025-05-23,18,0,VTM,NIEUWS 19U VTM,3287,454132
145,2025-05-23 20:42:16,2025-05-23,20,0,VTM,I CAN SEE YOUR VOICE,5367,412540
146,2025-05-23 20:07:22,2025-05-23,20,0,VTM,FAMILIE,1473,394309
147,2025-05-23 13:00:05,2025-05-23,13,0,VRT 1,HET 1 UUR-JOURNAAL,1747,324163
148,2025-05-23 20:43:03,2025-05-23,20,0,VRT 1,LA VIE EN ROSE,2824,312164
149,2025-05-23 18:12:32,2025-05-23,18,0,VRT 1,DAGELIJKSE KOST,922,256112
150,2025-05-23 21:34:07,2025-05-23,21,0,VRT CANVAS,RIDLEY,5318,224022
151,2025-05-23 20:38:57,2025-05-23,20,0,VRT CANVAS,DE AFSPRAAK,3149,214238
152,2025-05-23 12:59:48,2025-05-23,12,0,VTM,NIEUWS 13U VTM,1656,189416
153,2025-05-23 20:00:03,2025-05-23,20,0,VRT CANVAS,TER ZAKE,2180,185751
154,2025-05-23 17:14:33,2025-05-23,17,0,VRT 1,HAAT,3080,168537
155,2025-05-23 22:36:48,2025-05-23,22,0,VTM,"EEN ECHTE JOB, VROEDVROUW AN",3161,146601
156,2025-05-23 22:03:27,2025-05-23,22,0,VRT 1,HET JOURNAAL LAAT,1849,143701
157,2025-05-23 20:40:03,2025-05-23,20,0,PLAY4,THE REAL HOUSEWIVES OF ANTWERP,2688,139467
158,2025-05-23 15:31:05,2025-05-23,15,0,VRT 1,FLIKKEN MAASTRICHT,2974,116985
159,2025-05-23 22:41:07,2025-05-23,22,0,VRT 1,GIRO MAGAZINE,1081,116199
160,2025-05-24 19:00:06,2025-05-24,19,0,VRT 1,HET 7 UUR-JOURNAAL,2245,623399
161,2025-05-24 18:59:48,2025-05-24,18,0,VTM,NIEUWS 19U VTM,2683,478956
162,2025-05-24 20:21:16,2025-05-24,20,0,VRT 1,FC DE KAMPIOENEN,1967,425989
163,2025-05-24 20:56:45,2025-05-24,20,0,VRT 1,CHANTAL,2964,354804
164,2025-05-24 13:00:04,2025-05-24,13,0,VRT 1,HET 1 UUR-JOURNAAL,1559,345994
165,2025-05-24 19:48:09,2025-05-24,19,0,VRT 1,IEDEREEN BEROEMD,1852,333782
166,2025-05-24 19:56:46,2025-05-24,19,0,VTM,HET ECHTE LEVEN IN DE ZOO,1509,296223
167,2025-05-24 21:47:00,2025-05-24,21,0,VRT 1,DE JAREN 80 VOOR TIENERS,3387,287581
168,2025-05-24 12:59:48,2025-05-24,12,0,VTM,NIEUWS 13U VTM,1603,214651
169,2025-05-24 22:45:35,2025-05-24,22,0,VRT 1,HET JOURNAAL LAAT,1083,210499
170,2025-05-24 12:34:24,2025-05-24,12,0,VRT 1,DE MARKT,1424,209949
171,2025-05-24 20:33:06,2025-05-24,20,0,VTM,"JONAS & JELLE, FROM ZERO TO HERO",3477,205004
172,2025-05-24 21:47:53,2025-05-24,21,0,VTM,CRUELLA,7229,177451
173,2025-05-24 12:41:08,2025-05-24,12,0,EUROSPORT 1 (NL),CYCL. GIRO D'ITALIA,15639,153584
174,2025-05-24 20:34:06,2025-05-24,20,0,VRT CANVAS,OXEN,2634,139946
175,2025-05-24 18:08:10,2025-05-24,18,0,VRT 1,DOWN THE ROAD,3028,134110
176,2025-05-24 22:26:18,2025-05-24,22,0,PLAY4,SPORTS LATE NIGHT,2226,133659
177,2025-05-24 23:11:58,2025-05-24,23,0,VRT 1,GIRO MAGAZINE,1026,132233
178,2025-05-24 12:06:17,2025-05-24,12,0,VRT 1,DE WEEK VAN BRUZZ,1564,108686
179,2025-05-24 20:35:04,2025-05-24,20,0,VTM3,MOMENTUM,5120,81115
180,2025-05-25 19:00:04,2025-05-25,19,0,VRT 1,HET 7 UUR-JOURNAAL,1552,743261
181,2025-05-25 20:08:50,2025-05-25,20,0,VRT 1,CHATEAU PLANCKAERT,2429,728096
182,2025-05-25 19:26:12,2025-05-25,19,0,VRT 1,SPORTWEEKEND,2058,651307
183,2025-05-25 19:56:58,2025-05-25,19,0,VTM,DANCING WITH THE STARS,6297,602060
184,2025-05-25 20:50:30,2025-05-25,20,0,VRT 1,FLIKKEN MAASTRICHT,2740,507669
185,2025-05-25 18:59:48,2025-05-25,18,0,VTM,NIEUWS 19U VTM,2625,472644
186,2025-05-25 13:00:05,2025-05-25,13,0,VRT 1,HET 1 UUR-JOURNAAL,1521,413897
187,2025-05-25 21:38:07,2025-05-25,21,0,VRT 1,DE NOODCENTRALE,2307,269236
188,2025-05-25 11:00:04,2025-05-25,11,0,VRT 1,DE ZEVENDE DAG,7003,249483
189,2025-05-25 22:18:47,2025-05-25,22,0,VRT 1,HET JOURNAAL LAAT,1036,246733
190,2025-05-25 12:59:48,2025-05-25,12,0,VTM,NIEUWS 13U VTM,2246,218814
191,2025-05-25 21:56:53,2025-05-25,21,0,PLAY4,SPORTS LATE NIGHT,2762,217229
192,2025-05-25 18:11:38,2025-05-25,18,0,VRT 1,DAGELIJKSE KOST,2724,202191
193,2025-05-25 22:08:49,2025-05-25,22,0,VTM,ALLOO BIJ DE VERKEERSPOLITIE,3542,200694
194,2025-05-25 11:37:29,2025-05-25,11,0,EUROSPORT 1 (NL),CYCL. GIRO D'ITALIA,16970,136108
195,2025-05-25 18:20:00,2025-05-25,18,0,VTM,HET ECHTE LEVEN IN DE ZOO,1508,113621
196,2025-05-25 20:00:14,2025-05-25,20,0,VRT CANVAS,APPLES NEVER FALL,2643,107412
197,2025-05-25 18:26:59,2025-05-25,18,0,DAZN PRO LEAGUE 1 (NL),VB. JUPILER PRO LEAGUE - R. UNION ST.-G. - KAA...,6545,106159
198,2025-05-25 16:57:40,2025-05-25,16,0,EUROSPORT 1 (NL),KOP OVER KOP,1786,101423
199,2025-05-25 20:00:03,2025-05-25,20,0,PLAY4,GEUBELS EN DE BELGEN,2072,95813

,FullDate,date,hour,minute,Kanaal,Programma,Lengte_sec,Kijkers
0,2025-06-06 20:17:52,2025-06-06,20,0,VRT 1,THUIS,1470,None
1,2025-06-06 19:00:04,2025-06-06,19,0,VRT 1,HET 7 UUR-JOURNAAL,2598,None
2,2025-06-06 18:29:07,2025-06-06,18,0,VRT 1,BLOKKEN,1710,None
3,2025-06-06 18:59:48,2025-06-06,18,0,VTM,NIEUWS 19U VTM,3201,None
4,2025-06-06 21:37:08,2025-06-06,21,0,VRT 1,DE DAG VAN VANDAAG,3206,None
5,2025-06-06 20:05:28,2025-06-06,20,0,VTM,FAMILIE,1544,None
6,2025-06-06 20:41:26,2025-06-06,20,0,VTM,HUIS GEMAAKT,3945,None
7,2025-06-06 13:00:04,2025-06-06,13,0,VRT 1,HET 1 UUR-JOURNAAL,1653,None

In [8]:
def mergen(kijkcijfers, weer):
  kijkcijfersWeer = pd.merge(kijkcijfers, weer, on=['date', 'hour'], how='left')
  kijkcijfersWeer = kijkcijfersWeer[['FullDate', 'date', 'hour', 'Kanaal', 'Programma', 'Lengte_sec', 'Kijkers', 'Temperatuur', 'Gevoelstemp', 'Regen', 'Sneeuw', 'Weercode', 'Bewolking', 'Windsnelheid', 'Zonnenschijn']]
  kijkcijfersWeer.dropna(inplace=True)
  return kijkcijfersWeer

In [9]:
histKijkcijfersWeer = mergen(histKijkcijfersClean, histWeerdataClean)
print(histKijkcijfersWeer)

               FullDate        date  hour                  Kanaal  \
0   2025-05-16 20:15:38  2025-05-16    20                   VRT 1
1   2025-05-16 19:00:05  2025-05-16    19                   VRT 1
2   2025-05-16 19:46:40  2025-05-16    19                   VRT 1
3   2025-05-16 20:43:22  2025-05-16    20                     VTM
4   2025-05-16 20:08:26  2025-05-16    20                     VTM
..                  ...         ...   ...                     ...
195 2025-05-25 18:20:00  2025-05-25    18                     VTM
196 2025-05-25 20:00:14  2025-05-25    20              VRT CANVAS
197 2025-05-25 18:26:59  2025-05-25    18  DAZN PRO LEAGUE 1 (NL)
198 2025-05-25 16:57:40  2025-05-25    16        EUROSPORT 1 (NL)
199 2025-05-25 20:00:03  2025-05-25    20                   PLAY4

                                             Programma  Lengte_sec  Kijkers  \
0                                                THUIS        1489   937648
1                                   HET 7 UUR-JOURNAAL        2685   760119
2                                     IEDEREEN BEROEMD        1331   581626
3                                 I CAN SEE YOUR VOICE        5500   527119
4                                              FAMILIE        1468   526533
..                                                 ...         ...      ...
195                          HET ECHTE LEVEN IN DE ZOO        1508   113621
196                                  APPLES NEVER FALL        2643   107412
197  VB. JUPILER PRO LEAGUE - R. UNION ST.-G. - KAA...        6545   106159
198                                       KOP OVER KOP        1786   101423
199                               GEUBELS EN DE BELGEN        2072    95813

     Temperatuur  Gevoelstemp  Regen  Sneeuw  Weercode  Bewolking  \
0           12.3          8.6    0.0     0.0       3.0      100.0
1           12.6          9.0    0.0     0.0       3.0      100.0
2           12.6          9.0    0.0     0.0       3.0      100.0
3           12.3          8.6    0.0     0.0       3.0      100.0
4           12.3          8.6    0.0     0.0       3.0      100.0
..           ...          ...    ...     ...       ...        ...
195         19.0         16.0    0.1     0.0      51.0       52.0
196         16.7         14.6    0.1     0.0      51.0      100.0
197         19.0         16.0    0.1     0.0      51.0       52.0
198         19.0         15.7    0.3     0.0      51.0      100.0
199         16.7         14.6    0.1     0.0      51.0      100.0

     Windsnelheid  Zonnenschijn
0            18.4          0.00
1            18.8       1895.07
2            18.8       1895.07
3            18.4          0.00
4            18.4          0.00
..            ...           ...
195          21.2       3600.00
196          15.7        129.47
197          21.2       3600.00
198          24.8       3600.00
199          15.7        129.47

[200 rows x 15 columns]

In [10]:
teVoorspellenData = pd.merge(teVoorspellenClean, histWeerdataClean, on=['date', 'hour', 'minute'], how='left')
teVoorspellenData = teVoorspellenData.drop(columns=['datetime', 'minute'])
print(teVoorspellenData)

             FullDate        date  hour Kanaal           Programma  \
0 2025-06-06 20:17:52  2025-06-06    20  VRT 1               THUIS
1 2025-06-06 19:00:04  2025-06-06    19  VRT 1  HET 7 UUR-JOURNAAL
2 2025-06-06 18:29:07  2025-06-06    18  VRT 1             BLOKKEN
3 2025-06-06 18:59:48  2025-06-06    18    VTM      NIEUWS 19U VTM
4 2025-06-06 21:37:08  2025-06-06    21  VRT 1  DE DAG VAN VANDAAG
5 2025-06-06 20:05:28  2025-06-06    20    VTM             FAMILIE
6 2025-06-06 20:41:26  2025-06-06    20    VTM        HUIS GEMAAKT
7 2025-06-06 13:00:04  2025-06-06    13  VRT 1  HET 1 UUR-JOURNAAL

   Lengte_sec Kijkers  Temperatuur  Gevoelstemp  Regen  Sneeuw  Weercode  \
0        1470    None         17.1         15.7    0.1     0.0      51.0
1        2598    None         17.6         16.1    0.1     0.0      51.0
2        1710    None         18.0         16.3    0.1     0.0      51.0
3        3201    None         18.0         16.3    0.1     0.0      51.0
4        3206    None         16.4         15.0    0.0     0.0       3.0
5        1544    None         17.1         15.7    0.1     0.0      51.0
6        3945    None         17.1         15.7    0.1     0.0      51.0
7        1653    None         17.9         15.8    0.6     0.0      53.0

   Bewolking  Windsnelheid  Zonnenschijn
0       85.0           9.9       3600.00
1       77.0          10.9       3600.00
2       65.0          12.8       3600.00
3       65.0          12.8       3600.00
4       84.0           9.3       3600.00
5       85.0           9.9       3600.00
6       85.0           9.9       3600.00
7       32.0          18.6         37.35

In [11]:
def tijdFeatures(df):
    df['date'] = pd.to_datetime(df['date'])
    #feestdagen
    feestdagen = holidays.BE()
    df['isFeestdag'] = df['date'].apply(lambda x: 1 if x in feestdagen else 0)
    #dag van de week
    df['Weekdag'] = df['date'].dt.weekday
    #weekend
    df['isWeekend'] = df['Weekdag'].apply(lambda x: 1 if x >= 5 else 0)
    #seizoenen
    df['Seizoen'] = df['date'].apply(seizoenFinder)

    return df

#seizoen
def seizoenFinder(datum):
    inputDatum = datum.date()
    Y = inputDatum.year
    seizoenen = {
        'lente': (date(Y, 3, 20), date(Y, 6, 20)),
        'zomer': (date(Y, 6, 21), date(Y, 9, 22)),
        'herfst':   (date(Y, 9, 23), date(Y, 12, 20)),
        'winter': (date(Y, 12, 21), date(Y + 1, 3, 19)),
    }

    for seizoen, (start, end) in seizoenen.items():
        if start <= inputDatum <= end:
            return seizoen
    return 'winter'

In [12]:
teVoorspellenData = tijdFeatures(teVoorspellenData)
histKijkcijfersWeer = tijdFeatures(histKijkcijfersWeer)
histWeerdataClean = tijdFeatures(histWeerdataClean)
histWeerdataClean.drop(columns=['minute'], inplace=True)
display(teVoorspellenData.head())
display(histKijkcijfersWeer.head())
display(histWeerdataClean.head())

,FullDate,date,hour,Kanaal,Programma,Lengte_sec,Kijkers,Temperatuur,Gevoelstemp,Regen,Sneeuw,Weercode,Bewolking,Windsnelheid,Zonnenschijn,isFeestdag,Weekdag,isWeekend,Seizoen
0,2025-06-06 20:17:52,2025-06-06,20,VRT 1,THUIS,1470,None,17.1,15.7,0.1,0.0,51.0,85.0,9.9,3600.0,0,4,0,lente
1,2025-06-06 19:00:04,2025-06-06,19,VRT 1,HET 7 UUR-JOURNAAL,2598,None,17.6,16.1,0.1,0.0,51.0,77.0,10.9,3600.0,0,4,0,lente
2,2025-06-06 18:29:07,2025-06-06,18,VRT 1,BLOKKEN,1710,None,18.0,16.3,0.1,0.0,51.0,65.0,12.8,3600.0,0,4,0,lente
3,2025-06-06 18:59:48,2025-06-06,18,VTM,NIEUWS 19U VTM,3201,None,18.0,16.3,0.1,0.0,51.0,65.0,12.8,3600.0,0,4,0,lente
4,2025-06-06 21:37:08,2025-06-06,21,VRT 1,DE DAG VAN VANDAAG,3206,None,16.4,15.0,0.0,0.0,3.0,84.0,9.3,3600.0,0,4,0,lente

,FullDate,date,hour,Kanaal,Programma,Lengte_sec,Kijkers,Temperatuur,Gevoelstemp,Regen,Sneeuw,Weercode,Bewolking,Windsnelheid,Zonnenschijn,isFeestdag,Weekdag,isWeekend,Seizoen
0,2025-05-16 20:15:38,2025-05-16,20,VRT 1,THUIS,1489,937648,12.3,8.6,0.0,0.0,3.0,100.0,18.4,0.00,0,4,0,lente
1,2025-05-16 19:00:05,2025-05-16,19,VRT 1,HET 7 UUR-JOURNAAL,2685,760119,12.6,9.0,0.0,0.0,3.0,100.0,18.8,1895.07,0,4,0,lente
2,2025-05-16 19:46:40,2025-05-16,19,VRT 1,IEDEREEN BEROEMD,1331,581626,12.6,9.0,0.0,0.0,3.0,100.0,18.8,1895.07,0,4,0,lente
3,2025-05-16 20:43:22,2025-05-16,20,VTM,I CAN SEE YOUR VOICE,5500,527119,12.3,8.6,0.0,0.0,3.0,100.0,18.4,0.00,0,4,0,lente
4,2025-05-16 20:08:26,2025-05-16,20,VTM,FAMILIE,1468,526533,12.3,8.6,0.0,0.0,3.0,100.0,18.4,0.00,0,4,0,lente

,datetime,date,hour,Temperatuur,Gevoelstemp,Regen,Sneeuw,Weercode,Bewolking,Windsnelheid,Zonnenschijn,isFeestdag,Weekdag,isWeekend,Seizoen
0,2025-05-16 00:00:00,2025-05-16,0,11.6,8.6,0.0,0.0,0.0,0.0,12.7,0.0,0,4,0,lente
1,2025-05-16 01:00:00,2025-05-16,1,11.1,8.0,0.0,0.0,0.0,0.0,12.1,0.0,0,4,0,lente
2,2025-05-16 02:00:00,2025-05-16,2,10.3,7.2,0.0,0.0,0.0,0.0,11.5,0.0,0,4,0,lente
3,2025-05-16 03:00:00,2025-05-16,3,9.1,6.2,0.0,0.0,0.0,0.0,10.5,0.0,0,4,0,lente
4,2025-05-16 04:00:00,2025-05-16,4,8.4,5.7,0.0,0.0,0.0,0.0,10.0,0.0,0,4,0,lente

In [13]:
def lagFeatures(df, hist):
  df['Kijkers'] = None
  df['teVoorspellen'] = True
  hist['teVoorspellen'] = False
  df = pd.concat([hist, df], ignore_index=True)
  # Sorteer op tijd binnen elke groep
  df = df.sort_values(['Programma', 'FullDate'])

  df = df.sort_values(['Programma', 'FullDate'])

  # Bereken gemiddelde kijkers per Programma (op basis van historische data)
  kijkers_mean = df.groupby('Programma')['Kijkers'].transform('mean')

  # Bereken lag features per programma
  for i in range(1, 4):
      df[f'Kijkers_lag_{i}'] = df.groupby('Programma')['Kijkers'].shift(i)
      df[f'Kijkers_lag_{i}'] = df[f'Kijkers_lag_{i}'].fillna(df.groupby('Programma')['Kijkers'].transform('mean'))

  return df

In [14]:
pred_hist_df = lagFeatures(teVoorspellenData, histKijkcijfersWeer)
print("lagfeatures toegevoegd: ")
# display(pred_hist_df.dtypes)
pred_hist_df = pred_hist_df[pred_hist_df['teVoorspellen']]
pred_hist_df.drop(columns=['teVoorspellen'], inplace=True)
display(pred_hist_df.tail(10))
print(pred_hist_df[pred_hist_df.isna().any(axis=1)])

lagfeatures toegevoegd:

C:\Users\krist\AppData\Local\Temp\ipykernel_20168\3750620475.py:17: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[f'Kijkers_lag_{i}'] = df[f'Kijkers_lag_{i}'].fillna(df.groupby('Programma')['Kijkers'].transform('mean'))
C:\Users\krist\AppData\Local\Temp\ipykernel_20168\3750620475.py:17: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[f'Kijkers_lag_{i}'] = df[f'Kijkers_lag_{i}'].fillna(df.groupby('Programma')['Kijkers'].transform('mean'))
C:\Users\krist\AppData\Local\Temp\ipykernel_20168\3750620475.py:17: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[f'Kijkers_lag_{i}'] = df[f'Kijkers_lag_{i}'].fillna(df.groupby('Programma')['Kijkers'].transform('mean'))

,FullDate,date,hour,Kanaal,Programma,Lengte_sec,Kijkers,Temperatuur,Gevoelstemp,Regen,...,Bewolking,Windsnelheid,Zonnenschijn,isFeestdag,Weekdag,isWeekend,Seizoen,Kijkers_lag_1,Kijkers_lag_2,Kijkers_lag_3
202,2025-06-06 18:29:07,2025-06-06,18,VRT 1,BLOKKEN,1710,None,18.0,16.3,0.1,...,65.0,12.8,3600.00,0,4,0,lente,498063.0,488115.0,521698.0
204,2025-06-06 21:37:08,2025-06-06,21,VRT 1,DE DAG VAN VANDAAG,3206,None,16.4,15.0,0.0,...,84.0,9.3,3600.00,0,4,0,lente,NaN,NaN,NaN
205,2025-06-06 20:05:28,2025-06-06,20,VTM,FAMILIE,1544,None,17.1,15.7,0.1,...,85.0,9.9,3600.00,0,4,0,lente,394309.0,439141.0,465875.0
207,2025-06-06 13:00:04,2025-06-06,13,VRT 1,HET 1 UUR-JOURNAAL,1653,None,17.9,15.8,0.6,...,32.0,18.6,37.35,0,4,0,lente,413897.0,345994.0,324163.0
201,2025-06-06 19:00:04,2025-06-06,19,VRT 1,HET 7 UUR-JOURNAAL,2598,None,17.6,16.1,0.1,...,77.0,10.9,3600.00,0,4,0,lente,743261.0,623399.0,729945.0
206,2025-06-06 20:41:26,2025-06-06,20,VTM,HUIS GEMAAKT,3945,None,17.1,15.7,0.1,...,85.0,9.9,3600.00,0,4,0,lente,459562.0,400905.0,430233.5
203,2025-06-06 18:59:48,2025-06-06,18,VTM,NIEUWS 19U VTM,3201,None,18.0,16.3,0.1,...,65.0,12.8,3600.00,0,4,0,lente,472644.0,478956.0,454132.0
200,2025-06-06 20:17:52,2025-06-06,20,VRT 1,THUIS,1470,None,17.1,15.7,0.1,...,85.0,9.9,3600.00,0,4,0,lente,786790.0,798657.0,806473.0

               FullDate       date  hour Kanaal           Programma  \
202 2025-06-06 18:29:07 2025-06-06    18  VRT 1             BLOKKEN
204 2025-06-06 21:37:08 2025-06-06    21  VRT 1  DE DAG VAN VANDAAG
205 2025-06-06 20:05:28 2025-06-06    20    VTM             FAMILIE
207 2025-06-06 13:00:04 2025-06-06    13  VRT 1  HET 1 UUR-JOURNAAL
201 2025-06-06 19:00:04 2025-06-06    19  VRT 1  HET 7 UUR-JOURNAAL
206 2025-06-06 20:41:26 2025-06-06    20    VTM        HUIS GEMAAKT
203 2025-06-06 18:59:48 2025-06-06    18    VTM      NIEUWS 19U VTM
200 2025-06-06 20:17:52 2025-06-06    20  VRT 1               THUIS

     Lengte_sec Kijkers  Temperatuur  Gevoelstemp  Regen  ...  Bewolking  \
202        1710    None         18.0         16.3    0.1  ...       65.0
204        3206    None         16.4         15.0    0.0  ...       84.0
205        1544    None         17.1         15.7    0.1  ...       85.0
207        1653    None         17.9         15.8    0.6  ...       32.0
201        2598    None         17.6         16.1    0.1  ...       77.0
206        3945    None         17.1         15.7    0.1  ...       85.0
203        3201    None         18.0         16.3    0.1  ...       65.0
200        1470    None         17.1         15.7    0.1  ...       85.0

     Windsnelheid  Zonnenschijn  isFeestdag  Weekdag  isWeekend  Seizoen  \
202          12.8       3600.00           0        4          0    lente
204           9.3       3600.00           0        4          0    lente
205           9.9       3600.00           0        4          0    lente
207          18.6         37.35           0        4          0    lente
201          10.9       3600.00           0        4          0    lente
206           9.9       3600.00           0        4          0    lente
203          12.8       3600.00           0        4          0    lente
200           9.9       3600.00           0        4          0    lente

     Kijkers_lag_1 Kijkers_lag_2  Kijkers_lag_3
202       498063.0      488115.0       521698.0
204            NaN           NaN            NaN
205       394309.0      439141.0       465875.0
207       413897.0      345994.0       324163.0
201       743261.0      623399.0       729945.0
206       459562.0      400905.0       430233.5
203       472644.0      478956.0       454132.0
200       786790.0      798657.0       806473.0

[8 rows x 22 columns]

In [15]:
def oneHot(df):
  with open('./models/oneHotEncoder.pkl', 'rb') as oneHotFile:
    oneHotEnc = pickle.load(oneHotFile)

  lageKard = df[[ 'hour','Kanaal', 'isFeestdag', 'Weekdag', 'Seizoen']]
  dfOneHot = oneHotEnc.transform(lageKard)

  oneHotOutp = pd.DataFrame(dfOneHot.toarray(), 
                            columns=oneHotEnc.get_feature_names_out(), 
                            index=lageKard.index)

  df = df.drop(columns=['hour', 'Kanaal', 'isFeestdag', 'Weekdag', 'Seizoen'])
  df = pd.concat([df, oneHotOutp], axis = 1)
  return df

def target(df):
  #target encoding voor medium kardinaliteiten
  with open('./models/oneHotTarget.pkl', 'rb') as f:
    targetEnc = pickle.load(f)
  medKardinaliteit = df[['date', 'Programma', 'Lengte_sec', 'Temperatuur', 'Gevoelstemp', 'Regen', 'Bewolking', 'Windsnelheid', 'Zonnenschijn']]
  #verdere feature engineering op vorig model
  target = targetEnc.transform(medKardinaliteit)
  df = df.drop(columns=['date', 'Programma', 'Lengte_sec', 'Temperatuur', 'Gevoelstemp', 'Regen', 'Bewolking', 'Windsnelheid', 'Zonnenschijn'])
  f = pd.concat([df, target], axis=1)

  return f

In [16]:
teVoorspellenData = oneHot(pred_hist_df)
print("onehotencoding: ")
display(teVoorspellenData.head())
# Target encoding
targetOneHotEnc = target(teVoorspellenData)
print("targetencoding: ")
display(targetOneHotEnc.head())

onehotencoding:

,FullDate,date,Programma,Lengte_sec,Kijkers,Temperatuur,Gevoelstemp,Regen,Sneeuw,Weercode,...,Weekdag_1,Weekdag_2,Weekdag_3,Weekdag_4,Weekdag_5,Weekdag_6,Seizoen_herfst,Seizoen_lente,Seizoen_winter,Seizoen_zomer
202,2025-06-06 18:29:07,2025-06-06,BLOKKEN,1710,None,18.0,16.3,0.1,0.0,51.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
204,2025-06-06 21:37:08,2025-06-06,DE DAG VAN VANDAAG,3206,None,16.4,15.0,0.0,0.0,3.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
205,2025-06-06 20:05:28,2025-06-06,FAMILIE,1544,None,17.1,15.7,0.1,0.0,51.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
207,2025-06-06 13:00:04,2025-06-06,HET 1 UUR-JOURNAAL,1653,None,17.9,15.8,0.6,0.0,53.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
201,2025-06-06 19:00:04,2025-06-06,HET 7 UUR-JOURNAAL,2598,None,17.6,16.1,0.1,0.0,51.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0

targetencoding:

,FullDate,Kijkers,Sneeuw,Weercode,isWeekend,Kijkers_lag_1,Kijkers_lag_2,Kijkers_lag_3,hour_0,hour_1,...,Seizoen_zomer,date,Programma,Lengte_sec,Temperatuur,Gevoelstemp,Regen,Bewolking,Windsnelheid,Zonnenschijn
202,2025-06-06 18:29:07,None,0.0,51.0,0,498063.0,488115.0,521698.0,0.0,0.0,...,0.0,2025-06-06,589.000000,1710,18.0,16.3,0.1,65.0,12.8,3600.00
204,2025-06-06 21:37:08,None,0.0,3.0,0,NaN,NaN,NaN,0.0,0.0,...,0.0,2025-06-06,920.032052,3206,16.4,15.0,0.0,84.0,9.3,3600.00
205,2025-06-06 20:05:28,None,0.0,51.0,0,394309.0,439141.0,465875.0,0.0,0.0,...,0.0,2025-06-06,1403.000000,1544,17.1,15.7,0.1,85.0,9.9,3600.00
207,2025-06-06 13:00:04,None,0.0,53.0,0,413897.0,345994.0,324163.0,0.0,0.0,...,0.0,2025-06-06,1676.000000,1653,17.9,15.8,0.6,32.0,18.6,37.35
201,2025-06-06 19:00:04,None,0.0,51.0,0,743261.0,623399.0,729945.0,0.0,0.0,...,0.0,2025-06-06,1677.000000,2598,17.6,16.1,0.1,77.0,10.9,3600.00

In [17]:
teVoorspellenProgramma = teVoorspellenData['Programma']
teVoorspellenData = targetOneHotEnc.select_dtypes(include=[np.number])
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
teVoorspellenData.dtypes
display(teVoorspellenData)

,Sneeuw,Weercode,isWeekend,Kijkers_lag_1,Kijkers_lag_2,Kijkers_lag_3,hour_0,hour_1,hour_2,hour_6,hour_7,hour_8,hour_9,hour_10,hour_11,hour_12,hour_13,hour_14,hour_15,hour_16,hour_17,hour_18,hour_19,hour_20,hour_21,hour_22,hour_23,Kanaal_AB3,Kanaal_CANVAS,Kanaal_CAZ,Kanaal_Canvas,Kanaal_DAZN_PRO_LEAGUE_1_(NL),Kanaal_EEN,Kanaal_ELEVEN_PRO_LEAGUE_1_NL,Kanaal_EUROSPORT_1_(NL),Kanaal_KETNET,Kanaal_LA_UNE,Kanaal_OP_12,Kanaal_PLAY4,Kanaal_PLAY5,Kanaal_PLAY6,Kanaal_PLAY_SPORTS_OPEN,Kanaal_Q2,Kanaal_RTL-TVI,Kanaal_TF1,Kanaal_VIER,Kanaal_VIJF,Kanaal_VITAYA,Kanaal_VRT_1,Kanaal_VRT_CANVAS,Kanaal_VTM,Kanaal_VTM2,Kanaal_VTM3,Kanaal_VTM4,Kanaal_VTM_GOLD,Kanaal_ZES,isFeestdag_0,isFeestdag_1,Weekdag_0,Weekdag_1,Weekdag_2,Weekdag_3,Weekdag_4,Weekdag_5,Weekdag_6,Seizoen_herfst,Seizoen_lente,Seizoen_winter,Seizoen_zomer,Programma,Lengte_sec,Temperatuur,Gevoelstemp,Regen,Bewolking,Windsnelheid,Zonnenschijn
202,0.0,51.0,0,498063.0,488115.0,521698.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,589.000000,1710,18.0,16.3,0.1,65.0,12.8,3600.00
204,0.0,3.0,0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,920.032052,3206,16.4,15.0,0.0,84.0,9.3,3600.00
205,0.0,51.0,0,394309.0,439141.0,465875.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1403.000000,1544,17.1,15.7,0.1,85.0,9.9,3600.00
207,0.0,53.0,0,413897.0,345994.0,324163.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1676.000000,1653,17.9,15.8,0.6,32.0,18.6,37.35
201,0.0,51.0,0,743261.0,623399.0,729945.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1677.000000,2598,17.6,16.1,0.1,77.0,10.9,3600.00
206,0.0,51.0,0,459562.0,400905.0,430233.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1853.295495,3945,17.1,15.7,0.1,85.0,9.9,3600.00
203,0.0,51.0,0,472644.0,478956.0,454132.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,2553.000000,3201,18.0,16.3,0.1,65.0,12.8,3600.00
200,0.0,51.0,0,786790.0,798657.0,806473.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,3786.000000,1470,17.1,15.7,0.1,85.0,9.9,3600.00

In [20]:
try:
    with open('./models/optunaBestModel.pkl', 'rb') as file:
        lgbm = pickle.load(file)
except Exception as e:
    print("Kon model niet laden:", e)
    exit(1)

predictions = lgbm.predict(teVoorspellenData)
predictions = np.round(predictions).astype(int)
resultaten = pd.DataFrame({
    'Predicted': predictions,
    'Programma': teVoorspellenProgramma,
})
display(resultaten)

     Predicted           Programma
202     456969             BLOKKEN
204     114918  DE DAG VAN VANDAAG
205     421794             FAMILIE
207     342148  HET 1 UUR-JOURNAAL
201     653613  HET 7 UUR-JOURNAAL
206     424696        HUIS GEMAAKT
203     475103      NIEUWS 19U VTM
200     683309               THUIS